const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const WAT_FILE = path.join(__dirname, 'pose_calculations.wat');
const WASM_FILE = path.join(__dirname, 'pose_calculations.wasm');
const TS_FILE = path.join(__dirname, 'pose_calculations.d.ts');

// Ensure wabt is installed
try {
  require.resolve('wabt');
} catch (e) {
  console.error('wabt is not installed. Please run: npm install wabt');
  process.exit(1);
}

// Compile WAT to WASM
console.log('Compiling WAT to WASM...');
try {
  execSync(`npx wabt wat2wasm ${WAT_FILE} -o ${WASM_FILE}`);
  console.log('WASM compilation successful');
} catch (error) {
  console.error('Failed to compile WAT to WASM:', error);
  process.exit(1);
}

// Generate TypeScript declarations
console.log('Generating TypeScript declarations...');
const typeDeclarations = `// Generated by build.js
declare module 'pose_calculations' {
  export function calculate_angle(
    x1: number,
    y1: number,
    x2: number,
    y2: number,
    x3: number,
    y3: number
  ): number;
}
`;

try {
  fs.writeFileSync(TS_FILE, typeDeclarations);
  console.log('TypeScript declarations generated successfully');
} catch (error) {
  console.error('Failed to generate TypeScript declarations:', error);
  process.exit(1);
}

console.log('Build completed successfully'); 