#!/usr/bin/env python3
"""
Helper: print review_queue.json entries and optionally open them with macOS `open`.

Reads backend/scripts/output/review_queue.json (generated by e2e_posture_v1_smoke.py
--video-dir batch runs) and prints each video's absolute path with a macOS `open`
command so you can watch the video side-by-side with the model's verdict.

Usage:
    # Print all entries (all priorities)
    python scripts/open_review_videos.py

    # Print only Priority-1 high-confidence FPs
    python scripts/open_review_videos.py --priority 1

    # Print + actually open the videos with macOS `open`
    python scripts/open_review_videos.py --open

    # Non-default review queue path
    python scripts/open_review_videos.py --queue /path/to/review_queue.json
"""

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_QUEUE = SCRIPT_DIR / "output" / "review_queue.json"

PRIORITY_LABELS = {
    1: "HIGH-CONF FP  (model says fault but labeled good_form)",
    2: "HIGH-CONF FN  (model says good_form but labeled fault)",
    3: "BORDERLINE    (model near threshold ±0.05)",
}


def load_queue(path: str) -> dict:
    try:
        with open(path) as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"ERROR: review_queue.json not found at {path}", file=sys.stderr)
        print("Run a batch with --video-dir first to generate it.", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"ERROR: Failed to parse {path}: {e}", file=sys.stderr)
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description="Print / open videos from the PostureV1 review queue",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python scripts/open_review_videos.py
  python scripts/open_review_videos.py --priority 1
  python scripts/open_review_videos.py --priority 2 --open
  python scripts/open_review_videos.py --queue /tmp/my_queue.json
        """,
    )
    parser.add_argument(
        "--queue",
        default=str(DEFAULT_QUEUE),
        metavar="PATH",
        help=f"Path to review_queue.json (default: {DEFAULT_QUEUE})",
    )
    parser.add_argument(
        "--priority",
        type=int,
        default=None,
        choices=[1, 2, 3],
        help="Filter to a specific priority (1=high-conf FP, 2=high-conf FN, 3=borderline)",
    )
    parser.add_argument(
        "--open",
        action="store_true",
        dest="do_open",
        help="Open each video with macOS `open` command (requires macOS)",
    )
    args = parser.parse_args()

    data = load_queue(args.queue)
    items = data.get("items", [])

    if args.priority is not None:
        items = [x for x in items if x.get("priority") == args.priority]

    if not items:
        print("No items in review queue" + (f" at priority {args.priority}" if args.priority else "") + ".")
        print(f"Queue generated at: {data.get('generated_at', '?')}")
        return

    # Header
    print(f"\n{'=' * 80}")
    print(f"PostureV1 Review Queue")
    print(f"  Generated: {data.get('generated_at', '?')}")
    print(f"  Video dir: {data.get('video_dir', '?')}")
    print(f"  Total in queue: {data.get('total_in_queue', len(items))}")
    summary = data.get("priority_summary", {})
    print(f"  P1 high-conf FP: {summary.get('P1_high_conf_FP', 0)}  "
          f"P2 high-conf FN: {summary.get('P2_high_conf_FN', 0)}  "
          f"P3 borderline: {summary.get('P3_borderline', 0)}")
    if args.priority:
        print(f"  Filtered to: Priority {args.priority}")
    print(f"{'=' * 80}\n")

    for i, item in enumerate(items, 1):
        prio = item.get("priority", "?")
        prio_label = PRIORITY_LABELS.get(prio, f"Priority {prio}")
        abs_path = item.get("abs_path", item.get("filename", "?"))

        print(f"[{i}/{len(items)}] P{prio} — {prio_label}")
        print(f"  File:     {item.get('filename', '?')}")
        print(f"  Label:    {item.get('label_used', '?')}  (folder: {item.get('folder_label', '?')})")
        print(f"  Decision: {item.get('decision', '?')}  prob_fault={item.get('prob_fault', '?'):.4f}  "
              f"conf={item.get('confidence', 0):.3f}")
        if item.get("duration_sec") is not None:
            print(f"  Duration: {item['duration_sec']:.1f}s")
        if item.get("missing_ratio") is not None:
            print(f"  Missing:  {item['missing_ratio']:.1%}")
        if item.get("flags"):
            print(f"  Flags:    {item['flags']}")
        print(f"  Reason:   {item.get('reason', '?')}")
        print(f"  Action:   {item.get('suggested_action', '?')}")
        print(f"  Path:     {abs_path}")
        print(f"  open:     open \"{abs_path}\"")
        print()

        if args.do_open:
            if not os.path.isfile(abs_path):
                print(f"  WARNING: file not found at {abs_path}, skipping open", file=sys.stderr)
            elif sys.platform != "darwin":
                print(f"  WARNING: --open only works on macOS (sys.platform={sys.platform})", file=sys.stderr)
            else:
                subprocess.run(["open", abs_path], check=False)

    # Footer: instructions for updating labels_override.json
    print(f"{'=' * 80}")
    print("NEXT STEP: Update labels_override.json")
    print("  After watching the videos, edit:")
    print("    backend/test_videos/labels_override.json")
    print("  Valid values: good_form | posture_fault | other_fault | messy")
    print("  Example entry:")
    print('    "1678_posture_fault_1.mp4": "good_form"')
    print()
    print("  Then re-run the batch to see updated metrics:")
    print("    python scripts/e2e_posture_v1_smoke.py \\")
    print("      --video-dir test_videos/fault/ \\")
    print("      --labels-override test_videos/labels_override.json \\")
    print("      --metrics-scope posture_only")
    print(f"{'=' * 80}\n")


if __name__ == "__main__":
    main()
