/**
 * Exercise catalog — 63 exercises.
 * defaultIncrementLb: smallest safe weight step for each exercise/equipment type.
 * defaultRepIntent: rep range intent (never a single target — always {min, max}).
 *
 * allowedEquipment rules:
 *   bodyweight          = true no-external-load movements only
 *   weighted_bodyweight = bodyweight pattern with added external load (belt/vest/plate)
 *   other               = catch-all; not tagged on individual exercises (handled by getExercisesForEquipmentType)
 */

import type { Exercise, ExerciseId, EquipmentType } from "./types";

export const EXERCISES: Exercise[] = [
  // ── Barbell compounds ──────────────────────────────────────────────────
  {
    id: "barbell_back_squat",
    name: "Back Squat",
    primaryMuscles: ["quadriceps", "glutes", "hamstrings"],
    movementPattern: "squat",
    defaultLoadType: "barbell_plates",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 4, max: 8 },
    allowedEquipment: ["barbell"],
  },
  {
    id: "barbell_bench_press",
    name: "Barbell Bench Press",
    primaryMuscles: ["chest", "triceps", "anterior deltoid"],
    movementPattern: "horizontal_push",
    defaultLoadType: "barbell_plates",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 4, max: 8 },
    allowedEquipment: ["barbell"],
  },
  {
    id: "barbell_overhead_press",
    name: "Overhead Press",
    primaryMuscles: ["deltoids", "triceps", "upper traps"],
    movementPattern: "vertical_push",
    defaultLoadType: "barbell_plates",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 4, max: 8 },
    allowedEquipment: ["barbell"],
  },
  {
    id: "barbell_row",
    name: "Barbell Row",
    primaryMuscles: ["lats", "rhomboids", "biceps"],
    movementPattern: "horizontal_pull",
    defaultLoadType: "barbell_plates",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 4, max: 8 },
    allowedEquipment: ["barbell"],
  },
  {
    id: "deadlift",
    name: "Deadlift",
    primaryMuscles: ["hamstrings", "glutes", "erectors", "lats"],
    movementPattern: "hinge",
    defaultLoadType: "barbell_plates",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 3, max: 6 },
    allowedEquipment: ["barbell"],
  },
  {
    id: "incline_bench",
    name: "Incline Bench Press",
    primaryMuscles: ["upper chest", "triceps", "anterior deltoid"],
    movementPattern: "horizontal_push",
    defaultLoadType: "barbell_plates",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 5, max: 10 },
    allowedEquipment: ["barbell", "dumbbell", "machine_plate_loaded", "machine_selectorized"],
  },
  {
    id: "rdl",
    name: "Romanian Deadlift",
    primaryMuscles: ["hamstrings", "glutes", "erectors"],
    movementPattern: "hinge",
    defaultLoadType: "barbell_plates",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 6, max: 10 },
    allowedEquipment: ["barbell", "dumbbell"],
  },
  {
    id: "hip_thrust",
    name: "Hip Thrust",
    primaryMuscles: ["glutes", "hamstrings"],
    movementPattern: "hip_extension",
    defaultLoadType: "barbell_plates",
    defaultIncrementLb: 10,
    defaultRepIntent: { min: 8, max: 15 },
    // dumbbell hip thrust is a common gym movement; plate-loaded machine variant exists
    allowedEquipment: ["barbell", "dumbbell", "machine_plate_loaded"],
  },
  {
    id: "t_bar_row",
    name: "T-Bar Row",
    primaryMuscles: ["lats", "rhomboids", "biceps"],
    movementPattern: "horizontal_pull",
    defaultLoadType: "barbell_plates",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 6, max: 10 },
    allowedEquipment: ["barbell"],
  },
  {
    id: "skullcrusher",
    name: "Skull Crusher",
    primaryMuscles: ["triceps"],
    movementPattern: "elbow_extension",
    defaultLoadType: "barbell_plates",
    defaultIncrementLb: 2.5,
    defaultRepIntent: { min: 8, max: 12 },
    allowedEquipment: ["barbell", "dumbbell"],
  },
  // ── Smith Machine ──────────────────────────────────────────────────────
  {
    id: "smith_squat",
    name: "Smith Machine Squat",
    primaryMuscles: ["quadriceps", "glutes"],
    movementPattern: "squat",
    defaultLoadType: "barbell_plates",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 6, max: 12 },
    allowedEquipment: ["smith"],
  },
  {
    id: "smith_bench_press",
    name: "Smith Machine Bench Press",
    primaryMuscles: ["chest", "triceps", "anterior deltoid"],
    movementPattern: "horizontal_push",
    defaultLoadType: "barbell_plates",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 6, max: 12 },
    allowedEquipment: ["smith"],
  },
  {
    id: "smith_incline_press",
    name: "Smith Machine Incline Press",
    primaryMuscles: ["upper chest", "triceps", "anterior deltoid"],
    movementPattern: "horizontal_push",
    defaultLoadType: "barbell_plates",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 8, max: 12 },
    allowedEquipment: ["smith"],
  },
  {
    id: "smith_ohp",
    name: "Smith Machine Shoulder Press",
    primaryMuscles: ["deltoids", "triceps"],
    movementPattern: "vertical_push",
    defaultLoadType: "barbell_plates",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 8, max: 12 },
    allowedEquipment: ["smith"],
  },
  {
    id: "smith_rdl",
    name: "Smith Machine Romanian Deadlift",
    primaryMuscles: ["hamstrings", "glutes", "erectors"],
    movementPattern: "hinge",
    defaultLoadType: "barbell_plates",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 8, max: 12 },
    allowedEquipment: ["smith"],
  },
  {
    id: "smith_split_squat",
    name: "Smith Machine Split Squat",
    primaryMuscles: ["quadriceps", "glutes"],
    movementPattern: "squat",
    defaultLoadType: "barbell_plates",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 8, max: 12 },
    allowedEquipment: ["smith"],
  },
  {
    id: "smith_hip_thrust",
    name: "Smith Machine Hip Thrust",
    primaryMuscles: ["glutes", "hamstrings"],
    movementPattern: "hip_extension",
    defaultLoadType: "barbell_plates",
    defaultIncrementLb: 10,
    defaultRepIntent: { min: 10, max: 15 },
    allowedEquipment: ["smith"],
  },
  {
    id: "smith_calf_raise",
    name: "Smith Machine Calf Raise",
    primaryMuscles: ["gastrocnemius", "soleus"],
    movementPattern: "plantarflexion",
    defaultLoadType: "barbell_plates",
    defaultIncrementLb: 10,
    defaultRepIntent: { min: 12, max: 20 },
    allowedEquipment: ["smith"],
  },
  // ── Plate-Loaded Machines ──────────────────────────────────────────────
  {
    id: "hack_squat",
    name: "Hack Squat",
    primaryMuscles: ["quadriceps", "glutes"],
    movementPattern: "squat",
    defaultLoadType: "machine_plate_loaded",
    defaultIncrementLb: 10,
    defaultRepIntent: { min: 6, max: 12 },
    allowedEquipment: ["machine_plate_loaded"],
  },
  {
    id: "leg_press",
    name: "Leg Press",
    primaryMuscles: ["quadriceps", "glutes", "hamstrings"],
    movementPattern: "squat",
    defaultLoadType: "machine_plate_loaded",
    defaultIncrementLb: 10,
    defaultRepIntent: { min: 8, max: 15 },
    allowedEquipment: ["machine_plate_loaded", "machine_selectorized"],
  },
  {
    id: "plate_loaded_chest_press",
    name: "Plate-Loaded Chest Press",
    primaryMuscles: ["chest", "triceps", "anterior deltoid"],
    movementPattern: "horizontal_push",
    defaultLoadType: "machine_plate_loaded",
    defaultIncrementLb: 10,
    defaultRepIntent: { min: 8, max: 15 },
    allowedEquipment: ["machine_plate_loaded"],
  },
  {
    id: "plate_loaded_row",
    name: "Plate-Loaded Row",
    primaryMuscles: ["lats", "rhomboids", "biceps"],
    movementPattern: "horizontal_pull",
    defaultLoadType: "machine_plate_loaded",
    defaultIncrementLb: 10,
    defaultRepIntent: { min: 8, max: 15 },
    allowedEquipment: ["machine_plate_loaded"],
  },
  {
    id: "plate_loaded_pulldown",
    name: "Plate-Loaded Pulldown",
    primaryMuscles: ["lats", "biceps"],
    movementPattern: "vertical_pull",
    defaultLoadType: "machine_plate_loaded",
    defaultIncrementLb: 10,
    defaultRepIntent: { min: 8, max: 12 },
    allowedEquipment: ["machine_plate_loaded"],
  },
  // ── Pin-Loaded / Selectorized Machines ────────────────────────────────
  {
    id: "leg_extension",
    name: "Leg Extension",
    primaryMuscles: ["quadriceps"],
    movementPattern: "knee_extension",
    defaultLoadType: "machine_stack",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 10, max: 15 },
    allowedEquipment: ["machine_selectorized"],
  },
  {
    id: "leg_curl",
    name: "Leg Curl",
    primaryMuscles: ["hamstrings"],
    movementPattern: "knee_flexion",
    defaultLoadType: "machine_stack",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 10, max: 15 },
    allowedEquipment: ["machine_selectorized"],
  },
  {
    id: "machine_chest_press",
    name: "Machine Chest Press",
    primaryMuscles: ["chest", "triceps"],
    movementPattern: "horizontal_push",
    defaultLoadType: "machine_stack",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 8, max: 15 },
    allowedEquipment: ["machine_selectorized"],
  },
  {
    id: "lat_pulldown",
    name: "Lat Pulldown",
    primaryMuscles: ["lats", "biceps"],
    movementPattern: "vertical_pull",
    defaultLoadType: "machine_stack",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 8, max: 12 },
    allowedEquipment: ["cable_stack", "machine_selectorized"],
  },
  {
    id: "row_machine",
    name: "Row Machine",
    primaryMuscles: ["lats", "rhomboids"],
    movementPattern: "horizontal_pull",
    defaultLoadType: "machine_stack",
    defaultIncrementLb: 10,
    defaultRepIntent: { min: 8, max: 15 },
    allowedEquipment: ["machine_selectorized", "machine_plate_loaded"],
  },
  {
    id: "pec_deck",
    name: "Pec Deck / Chest Fly Machine",
    primaryMuscles: ["chest", "anterior deltoid"],
    movementPattern: "fly",
    defaultLoadType: "machine_stack",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 10, max: 15 },
    allowedEquipment: ["machine_selectorized"],
  },
  {
    id: "ab_crunch_machine",
    name: "Ab Crunch Machine",
    primaryMuscles: ["rectus abdominis"],
    movementPattern: "spinal_flexion",
    defaultLoadType: "machine_stack",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 12, max: 20 },
    allowedEquipment: ["machine_selectorized"],
  },
  {
    id: "calf_raise",
    name: "Calf Raise",
    primaryMuscles: ["gastrocnemius", "soleus"],
    movementPattern: "plantarflexion",
    defaultLoadType: "machine_stack",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 12, max: 20 },
    allowedEquipment: ["machine_selectorized", "machine_plate_loaded", "smith"],
  },
  {
    id: "adductor_machine",
    name: "Hip Adductor",
    primaryMuscles: ["hip adductors"],
    movementPattern: "hip_adduction",
    defaultLoadType: "machine_stack",
    defaultIncrementLb: 10,
    defaultRepIntent: { min: 12, max: 20 },
    allowedEquipment: ["machine_selectorized"],
  },
  {
    id: "abductor_machine",
    name: "Hip Abductor",
    primaryMuscles: ["hip abductors", "glutes"],
    movementPattern: "hip_abduction",
    defaultLoadType: "machine_stack",
    defaultIncrementLb: 10,
    defaultRepIntent: { min: 12, max: 20 },
    allowedEquipment: ["machine_selectorized"],
  },
  {
    id: "machine_curl",
    name: "Machine Curl",
    primaryMuscles: ["biceps"],
    movementPattern: "elbow_flexion",
    defaultLoadType: "machine_stack",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 10, max: 15 },
    allowedEquipment: ["machine_selectorized"],
  },
  {
    id: "machine_tricep_extension",
    name: "Machine Triceps Extension",
    primaryMuscles: ["triceps"],
    movementPattern: "elbow_extension",
    defaultLoadType: "machine_stack",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 10, max: 15 },
    allowedEquipment: ["machine_selectorized"],
  },
  {
    id: "assisted_pull_up_dip",
    name: "Assisted Pull-Up / Dip",
    primaryMuscles: ["lats", "chest", "triceps"],
    movementPattern: "vertical_pull",
    defaultLoadType: "machine_stack",
    defaultIncrementLb: 10,
    defaultRepIntent: { min: 5, max: 15 },
    allowedEquipment: ["machine_selectorized"],
  },
  // ── Cable ─────────────────────────────────────────────────────────────
  {
    id: "seated_cable_row",
    name: "Seated Cable Row",
    primaryMuscles: ["lats", "rhomboids", "biceps"],
    movementPattern: "horizontal_pull",
    defaultLoadType: "machine_stack",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 8, max: 12 },
    allowedEquipment: ["cable_stack"],
  },
  {
    id: "tricep_pushdown",
    name: "Tricep Pushdown",
    primaryMuscles: ["triceps"],
    movementPattern: "elbow_extension",
    defaultLoadType: "cable",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 10, max: 15 },
    allowedEquipment: ["cable_stack"],
  },
  {
    id: "cable_curl",
    name: "Cable Curl",
    primaryMuscles: ["biceps"],
    movementPattern: "elbow_flexion",
    defaultLoadType: "cable",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 10, max: 15 },
    allowedEquipment: ["cable_stack"],
  },
  {
    id: "chest_fly",
    name: "Cable Fly",
    primaryMuscles: ["chest", "anterior deltoid"],
    movementPattern: "fly",
    defaultLoadType: "cable",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 10, max: 15 },
    allowedEquipment: ["cable_stack"],
  },
  {
    id: "cable_lateral_raise",
    name: "Cable Lateral Raise",
    primaryMuscles: ["medial deltoid"],
    movementPattern: "shoulder_abduction",
    defaultLoadType: "cable",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 12, max: 20 },
    allowedEquipment: ["cable_stack"],
  },
  {
    id: "cable_overhead_tricep",
    name: "Cable Overhead Triceps Extension",
    primaryMuscles: ["triceps"],
    movementPattern: "elbow_extension",
    defaultLoadType: "cable",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 10, max: 15 },
    allowedEquipment: ["cable_stack"],
  },
  {
    id: "face_pull",
    name: "Face Pull",
    primaryMuscles: ["posterior deltoid", "rotator cuff", "rhomboids"],
    movementPattern: "shoulder_extension",
    defaultLoadType: "cable",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 12, max: 20 },
    allowedEquipment: ["cable_stack"],
  },
  // ── Dumbbell ──────────────────────────────────────────────────────────
  {
    id: "dumbbell_bench_press",
    name: "Dumbbell Bench Press",
    primaryMuscles: ["chest", "triceps"],
    movementPattern: "horizontal_push",
    defaultLoadType: "dumbbell_pair",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 8, max: 12 },
    allowedEquipment: ["dumbbell"],
  },
  {
    id: "dumbbell_shoulder_press",
    name: "Dumbbell Shoulder Press",
    primaryMuscles: ["deltoids", "triceps"],
    movementPattern: "vertical_push",
    defaultLoadType: "dumbbell_pair",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 8, max: 12 },
    allowedEquipment: ["dumbbell"],
  },
  {
    id: "dumbbell_row",
    name: "Dumbbell Row",
    primaryMuscles: ["lats", "rhomboids"],
    movementPattern: "horizontal_pull",
    defaultLoadType: "dumbbell_pair",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 8, max: 12 },
    allowedEquipment: ["dumbbell"],
  },
  {
    id: "bicep_curl",
    name: "Bicep Curl",
    primaryMuscles: ["biceps"],
    movementPattern: "elbow_flexion",
    defaultLoadType: "dumbbell_pair",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 10, max: 15 },
    allowedEquipment: ["dumbbell"],
  },
  {
    id: "hammer_curl",
    name: "Hammer Curl",
    primaryMuscles: ["biceps", "brachialis"],
    movementPattern: "elbow_flexion",
    defaultLoadType: "dumbbell_pair",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 10, max: 15 },
    allowedEquipment: ["dumbbell"],
  },
  {
    id: "lateral_raise",
    name: "Lateral Raise",
    primaryMuscles: ["medial deltoid"],
    movementPattern: "shoulder_abduction",
    defaultLoadType: "dumbbell_pair",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 12, max: 20 },
    allowedEquipment: ["dumbbell", "cable_stack", "machine_selectorized"],
  },
  {
    id: "rear_delt_fly",
    name: "Rear Delt Fly",
    primaryMuscles: ["posterior deltoid", "rhomboids"],
    movementPattern: "shoulder_extension",
    defaultLoadType: "dumbbell_pair",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 12, max: 20 },
    allowedEquipment: ["dumbbell", "cable_stack", "machine_selectorized"],
  },
  {
    id: "goblet_squat",
    name: "Goblet Squat",
    primaryMuscles: ["quadriceps", "glutes", "core"],
    movementPattern: "squat",
    defaultLoadType: "dumbbell_pair",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 8, max: 15 },
    allowedEquipment: ["dumbbell"],
  },
  {
    id: "dumbbell_rdl",
    name: "Dumbbell Romanian Deadlift",
    primaryMuscles: ["hamstrings", "glutes", "erectors"],
    movementPattern: "hinge",
    defaultLoadType: "dumbbell_pair",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 8, max: 12 },
    allowedEquipment: ["dumbbell"],
  },
  // ── Barbell accessories ────────────────────────────────────────────────
  {
    id: "barbell_front_squat",
    name: "Front Squat",
    primaryMuscles: ["quadriceps", "glutes", "core"],
    movementPattern: "squat",
    defaultLoadType: "barbell_plates",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 4, max: 8 },
    allowedEquipment: ["barbell"],
  },
  {
    id: "barbell_curl",
    name: "Barbell Curl",
    primaryMuscles: ["biceps"],
    movementPattern: "elbow_flexion",
    defaultLoadType: "barbell_plates",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 8, max: 12 },
    allowedEquipment: ["barbell"],
  },
  // ── Multi-equipment ────────────────────────────────────────────────────
  {
    id: "split_squat",
    name: "Bulgarian Split Squat",
    primaryMuscles: ["quadriceps", "glutes"],
    movementPattern: "squat",
    defaultLoadType: "dumbbell_pair",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 8, max: 12 },
    // barbell (on back), dumbbell, bodyweight (unloaded); smith has its own exercise
    allowedEquipment: ["barbell", "dumbbell", "bodyweight"],
  },
  {
    id: "step_up",
    name: "Step-Up",
    primaryMuscles: ["quadriceps", "glutes"],
    movementPattern: "squat",
    defaultLoadType: "dumbbell_pair",
    defaultIncrementLb: 5,
    defaultRepIntent: { min: 8, max: 12 },
    allowedEquipment: ["dumbbell", "bodyweight"],
  },
  // ── Bodyweight (pure — no external load) ──────────────────────────────
  {
    id: "pull_up",
    name: "Pull-Up",
    primaryMuscles: ["lats", "biceps"],
    movementPattern: "vertical_pull",
    defaultLoadType: "fixed",
    defaultIncrementLb: 0,
    defaultRepIntent: { min: 5, max: 12 },
    // weighted_bodyweight: add external load via dip belt / vest / plate
    allowedEquipment: ["bodyweight", "weighted_bodyweight"],
  },
  {
    id: "dip",
    name: "Dip",
    primaryMuscles: ["triceps", "chest"],
    movementPattern: "vertical_push",
    defaultLoadType: "fixed",
    defaultIncrementLb: 0,
    defaultRepIntent: { min: 6, max: 12 },
    allowedEquipment: ["bodyweight", "weighted_bodyweight"],
  },
  {
    id: "chin_up",
    name: "Chin-Up",
    primaryMuscles: ["lats", "biceps"],
    movementPattern: "vertical_pull",
    defaultLoadType: "fixed",
    defaultIncrementLb: 0,
    defaultRepIntent: { min: 5, max: 12 },
    allowedEquipment: ["bodyweight", "weighted_bodyweight"],
  },
  {
    id: "push_up",
    name: "Push-Up",
    primaryMuscles: ["chest", "triceps", "anterior deltoid"],
    movementPattern: "horizontal_push",
    defaultLoadType: "fixed",
    defaultIncrementLb: 0,
    defaultRepIntent: { min: 8, max: 20 },
    allowedEquipment: ["bodyweight", "weighted_bodyweight"],
  },
  {
    id: "bodyweight_squat",
    name: "Bodyweight Squat",
    primaryMuscles: ["quadriceps", "glutes"],
    movementPattern: "squat",
    defaultLoadType: "fixed",
    defaultIncrementLb: 0,
    defaultRepIntent: { min: 15, max: 30 },
    allowedEquipment: ["bodyweight"],
  },
  {
    id: "inverted_row",
    name: "Inverted Row",
    primaryMuscles: ["lats", "rhomboids", "biceps"],
    movementPattern: "horizontal_pull",
    defaultLoadType: "fixed",
    defaultIncrementLb: 0,
    defaultRepIntent: { min: 8, max: 15 },
    allowedEquipment: ["bodyweight"],
  },
  {
    id: "hanging_leg_raise",
    name: "Hanging Leg Raise",
    primaryMuscles: ["rectus abdominis", "hip flexors"],
    movementPattern: "spinal_flexion",
    defaultLoadType: "fixed",
    defaultIncrementLb: 0,
    defaultRepIntent: { min: 10, max: 20 },
    allowedEquipment: ["bodyweight"],
  },
];

/** Fast lookup by ExerciseId. Returns undefined if not found. */
export function getExercise(id: ExerciseId): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id);
}

/** Case-insensitive name search. Returns all exercises whose name contains the query. */
export function searchExercises(query: string): Exercise[] {
  if (!query.trim()) return EXERCISES;
  const q = query.toLowerCase();
  return EXERCISES.filter(
    (e) =>
      e.name.toLowerCase().includes(q) ||
      e.primaryMuscles.some((m) => m.toLowerCase().includes(q)) ||
      (e.movementPattern ?? "").toLowerCase().includes(q),
  );
}

/**
 * Returns exercises compatible with the given equipment type.
 * "other" is a catch-all — returns all exercises.
 */
export function getExercisesForEquipmentType(type: EquipmentType): Exercise[] {
  if (type === "other") return EXERCISES;
  return EXERCISES.filter((e) => e.allowedEquipment.includes(type));
}
