"""
Dynamic form analysis service module.

This service uses the database-backed exercise configurations to analyze form.
It replaces the hardcoded rule-based analysis with a dynamic rules engine.
"""
import logging
import json
from typing import Dict, List, Any, Optional, Tuple, TypedDict, Union
from uuid import UUID, uuid4
import math # ADDED for posture calculations
import numpy as np # ADDED for np.mean
from datetime import datetime # ADDED

from sqlalchemy.ext.asyncio import AsyncSession
from app.core.config import Settings
from app.models.enums import FormCheckStatus, FeedbackType, FeedbackSeverity

from app.services.exercise_config_service import ExerciseConfigService
from app.services.form_check_service import FormCheckService
from app.models.exercise_config import ExerciseConfig, MovementPhaseTrigger, Condition
from app.models.form_check import FormCheck, FeedbackItem
from app.models.video import Video
from app.core.exceptions import ValidationError, NotFoundException, ServerErrorException
from app.constants.angles import POSE_LANDMARK_NAMES # ADDED for posture rule keypoint name mapping

logger = logging.getLogger(__name__)

# Define a structure for the issues that will be generated by rule evaluators
class StructuredIssue(TypedDict, total=False): # total=False allows for optional keys
    rule_type: str # e.g., "joint_angle", "rom", "posture", "symmetry"
    joint_name: Optional[str]
    compared_to_joint: Optional[str] # For symmetry
    details: str # Human-readable description of the issue
    severity: str # e.g., "low", "medium", "high" (can map to FeedbackSeverity enum)
    phase: str # Movement phase in which issue occurred
    rep_index: int # 0-indexed
    frame_index_in_rep: Optional[int] # Optional: frame number within the current repetition
    timestamp_in_video: Optional[float] # Optional: actual video timestamp
    # Specific data related to the issue, e.g.:
    current_value: Optional[float]
    expected_value: Optional[Any] # Could be a single value, a range [min, max], or a dict
    deviation: Optional[float]

class DynamicFormAnalysisService:
    """
    Service for analyzing exercise form using dynamic configurations.
    
    This service replaces hardcoded form analysis with dynamic database-backed rules.
    """
    
    def __init__(self, db: AsyncSession, settings: Settings, exercise_config_service: ExerciseConfigService, form_check_service: FormCheckService, ai_service=None):
        self.db = db
        self.settings = settings
        self.exercise_config_service = exercise_config_service
        self.form_check_service = form_check_service
        self.ai_service = ai_service  # Enhanced AIService for ML-based form analysis

    async def _get_exercise_config_model_async(self, exercise_template_id: UUID) -> Optional[ExerciseConfig]:
        """
        Get the active exercise configuration model for an exercise template.
        """
        config_model = await self.exercise_config_service.get_active_config_for_exercise_async(exercise_id=exercise_template_id)
        return config_model
    
    async def segment_repetitions(
        self, 
        angle_data_sequence: List[Dict[str, Any]], # Expects each dict to have 'frame_num' and 'angles'
        config: ExerciseConfig
    ) -> List[List[Dict[str, Any]]]:
        """
        Segments a sequence of angle data into repetitions based on movement phase transitions
        defined in the ExerciseConfig.
        Each repetition is a list of angle data frames (dictionaries).
        """
        logger.info(f"Attempting to segment {len(angle_data_sequence)} frames into repetitions using config: {config.name}")
        
        if not angle_data_sequence:
            logger.warning("Angle data sequence is empty. No repetitions to segment.")
            return []
        if not config or not config.movement_phases or not isinstance(config.movement_phases, dict):
            logger.warning("Insufficient or invalid config for segmentation: missing or malformed movement_phases.")
            return []

        # Ensure movement_phases has a defined start_phase_name, typically the first key or a marked one.
        # And an end_phase_name that signifies a rep completion or loop back to start.
        # For simplicity, let's assume the config has a 'start_phase_name' field and an 'end_phase_action'
        # on the phase that completes a rep (e.g., 'loop_to_start_phase').
        # These would ideally be part of the ExerciseConfig schema for clarity.
        # For now, we'll infer a plausible start (e.g., first phase listed or a phase named 'start').
        
        # Try to find a phase explicitly named 'start' or 'start_phase'
        # Fallback to the first phase defined if no explicit start is found.
        potential_start_phases = [name for name in config.movement_phases.keys() if "start" in name.lower()]
        if potential_start_phases:
            current_phase_name = potential_start_phases[0]
        elif config.movement_phases:
            current_phase_name = list(config.movement_phases.keys())[0]
        else:
            logger.error("No movement phases defined in config. Cannot segment.")
            return []

        logger.info(f"Initial segmentation phase: {current_phase_name}")

        repetitions: List[List[Dict[str, Any]]] = []
        current_rep_frames: List[Dict[str, Any]] = []
        
        # Default to first phase in config if 'start_phase_name' is not explicit in config schema
        # This is a simplification; a robust config should define the entry point phase.
        # For now, assume a phase like 'start_phase' or the first one defined is the entry.
        
        # Helper to evaluate triggers
        def _check_trigger(frame_angles: Dict[str, float], trigger_condition: Dict[str, Any]) -> bool:
            joint_name = trigger_condition.get("joint")
            condition_type = trigger_condition.get("condition") # e.g., "angle"
            target_value = trigger_condition.get("value")
            comparator = trigger_condition.get("comparator") # e.g., "<", ">", "peaks"

            if not all([joint_name, condition_type, target_value, comparator]):
                logger.warning(f"Malformed trigger condition: {trigger_condition}. Skipping.")
                return False

            current_angle = frame_angles.get(joint_name)
            if current_angle is None:
                # logger.debug(f"Joint {joint_name} not in frame angles for trigger check. Frame: {frame_angles}")
                return False

            if condition_type == "angle":
                if comparator == "<": return current_angle < target_value
                if comparator == "<=": return current_angle <= target_value
                if comparator == ">": return current_angle > target_value
                if comparator == ">=": return current_angle >= target_value
                if comparator == "==": return abs(current_angle - target_value) < 1e-5 # float equality
                # Add more comparators/conditions like 'velocity_peaks', 'crosses_threshold' if needed
            # else:
                # logger.warning(f"Unsupported trigger condition type: {condition_type}")
            return False

        for frame_data in angle_data_sequence:
            # Ensure frame_data contains 'angles'; if not, it might be an empty frame from previous steps
            # Add current_phase_name to frame_data before appending to current_rep_frames
            augmented_frame_data = {**frame_data, 'phase_context': current_phase_name}

            if not frame_data or "angles" not in frame_data or frame_data["angles"] is None:
                if current_rep_frames: # If we've started collecting a rep
                    current_rep_frames.append(augmented_frame_data) # Add the problematic frame with phase context
                continue # Skip phase transition logic for this frame, but keep it if rep started

            # Add frame to current rep FIRST.
            current_rep_frames.append(augmented_frame_data)

            frame_angles = frame_data["angles"]
            phase_changed_this_frame = False

            current_phase_definition = config.movement_phases.get(current_phase_name) # Returns MovementPhaseDefinition object or None
            
            # Check if current_phase_definition is a valid MovementPhaseDefinition model instance
            if not current_phase_definition or not hasattr(current_phase_definition, 'triggers'): # Check for attribute presence
                logger.error(f"Config for phase '{current_phase_name}' is missing, not a MovementPhaseDefinition, or has no triggers. Halting segmentation. Phase Def: {type(current_phase_definition)}")
                break 
            
            # Access triggers directly as an attribute if it's a Pydantic model
            # The triggers attribute should be Dict[str, MovementPhaseTrigger]
            phase_triggers_dict = current_phase_definition.triggers 
            if not isinstance(phase_triggers_dict, dict): # Ensure it's a dict as expected by schema
                 logger.error(f"Triggers for phase '{current_phase_name}' are not a dictionary. Triggers: {type(phase_triggers_dict)}. Halting segmentation.")
                 break
            
            # Priority: Check for triggers that end the current rep and start a new one
            # This assumes a specific trigger key like 'end_rep_and_loop_to_phase' or similar
            # in the phase_triggers that signifies completion of a full rep.
            # Example: 'ascent_phase' triggers might point back to 'start_phase', indicating rep end.
            
            next_phase_for_new_rep = None
            # The 'next_rep_starts_phase' is a hypothetical key, actual logic would depend on config structure.
            # For now, let's assume a transition back to the initial start_phase signifies a rep end.
            # A more robust FSM would have explicit "end_rep" flags or transitions.
            # We'll rely on 'next' trigger target_phase for now.

            next_trigger_obj = phase_triggers_dict.get("next") # This should be a MovementPhaseTrigger object
            if next_trigger_obj and isinstance(next_trigger_obj, MovementPhaseTrigger) and next_trigger_obj.conditions:
                for condition_obj in next_trigger_obj.conditions: # condition_obj is a Condition model
                    if self._check_trigger_condition_model(frame_angles, condition_obj): # Pass Condition model
                        new_phase_name = next_trigger_obj.target_phase
                        if new_phase_name and new_phase_name in config.movement_phases:
                            # Check if this transition completes a rep (e.g., to initial start phase from a non-start phase)
                            # This is a simplified rep boundary detection.
                            is_rep_completion = (new_phase_name == potential_start_phases[0] and 
                                                 current_phase_name != potential_start_phases[0] and 
                                                 len(current_rep_frames) > 1) # Avoid single-frame "reps" on immediate loopback

                            if is_rep_completion:
                                # The current_rep_frames INCLUDES the frame that triggered the transition.
                                # This frame is part of the COMPLETED rep.
                                repetitions.append(list(current_rep_frames))
                                logger.info(f"Completed Rep {len(repetitions)} ending with phase '{current_phase_name}' ({len(current_rep_frames)} frames). Transitioning to '{new_phase_name}' for new rep.")
                                current_rep_frames.clear() # Start a new rep
                                # The new rep will start with the *next* frame processed by the outer loop.
                                # The current frame that completed the rep should NOT be the first frame of the new rep.
                                logger.debug(f"Frame {frame_data.get('frame_num', 'N/A')}: Phase transition from '{current_phase_name}' to '{new_phase_name}'.")
                                current_phase_name = new_phase_name
                                phase_changed_this_frame = True
                                break # Process only one transition per frame
                            else: # This 'else' corresponds to 'if new_phase_name and new_phase_name in config.movement_phases' not 'is_rep_completion'
                                # This branch is executed if the transition is to a new phase, but it does NOT complete a rep.
                                # For example, moving from 'descent' to 'bottom_hold'.
                                logger.debug(f"Frame {frame_data.get('frame_num', 'N/A')}: Phase transition (within rep) from '{current_phase_name}' to '{new_phase_name}'.")
                                current_phase_name = new_phase_name
                                phase_changed_this_frame = True
                                break # Process only one transition per frame
                        else: # This 'else' corresponds to 'if new_phase_name and new_phase_name in config.movement_phases'
                            logger.warning(f"Invalid target phase '{new_phase_name}' specified in 'next' trigger for '{current_phase_name}'. Target phase does not exist in config.movement_phases.")
                            # Potentially break or continue, depending on desired behavior for invalid config target.
                            # For now, let's assume we don't transition and try other triggers for this frame.
                
                # Optionally, check for "previous" phase transitions if phase_changed_this_frame is still False
            if not phase_changed_this_frame:
                previous_trigger_obj = phase_triggers_dict.get("previous")
                if previous_trigger_obj and isinstance(previous_trigger_obj, MovementPhaseTrigger) and previous_trigger_obj.conditions:
                    for condition_obj in previous_trigger_obj.conditions:
                         if self._check_trigger_condition_model(frame_angles, condition_obj):
                            prev_phase_name = previous_trigger_obj.target_phase
                            if prev_phase_name and prev_phase_name in config.movement_phases:
                                logger.debug(f"Frame {frame_data.get('frame_num', 'N/A')}: Phase transition (backwards) from '{current_phase_name}' to '{prev_phase_name}'.")
                                current_phase_name = prev_phase_name
                                phase_changed_this_frame = True
                                break
                            else:
                                logger.warning(f"Invalid target phase '{prev_phase_name}' in 'previous' trigger for '{current_phase_name}'.")

        # After loop, add any remaining frames as the last (potentially incomplete) rep
        # only if they represent progress beyond just the initial state or a single frame.
        if current_rep_frames and (len(current_rep_frames) > 1 or current_phase_name != potential_start_phases[0]):
            repetitions.append(list(current_rep_frames))
            logger.info(f"Added final (potentially incomplete) Rep {len(repetitions)} with {len(current_rep_frames)} frames, ending in phase '{current_phase_name}'.")

        if not repetitions:
            logger.warning(f"Segmentation did not yield any repetitions for config '{config.name}'.")
        else:
            logger.info(f"Successfully segmented into {len(repetitions)} repetitions.")
        
        return repetitions

    def _check_trigger_condition_model(self, frame_angles: Dict[str, float], condition_model: Condition) -> bool:
        """Helper to evaluate a single Condition model."""
        # condition_model is already a Condition Pydantic object
        joint_name = condition_model.joint
        # condition_type = condition_model.condition # This field is on the Condition model
        target_value = condition_model.value
        comparator = condition_model.comparator

        if not all([joint_name, target_value is not None, comparator]): # target_value can be 0
            logger.warning(f"Malformed Condition model: {condition_model}. Skipping.")
            return False

        current_angle = frame_angles.get(joint_name)
        if current_angle is None:
            return False

        # Assuming condition_model.condition is always "angle" for now as per fixture
        if comparator == "<": return current_angle < target_value
        if comparator == "<=": return current_angle <= target_value
        if comparator == ">": return current_angle > target_value
        if comparator == ">=": return current_angle >= target_value
        if comparator == "==": return abs(current_angle - target_value) < 1e-5
        return False

    # --- BEGIN MODULAR RULE EVALUATOR STUBS ---
    # These will be implemented in detail in subsequent steps.

    async def _apply_joint_angle_rules(
        self,
        frame_angles: Dict[str, float],
        rep_index: int,
        current_phase_name: str,
        frame_timestamp: Optional[float],
        frame_index_in_rep: int,
        config: ExerciseConfig
    ) -> List[StructuredIssue]:
        logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep} ({current_phase_name}): Applying joint angle rules using ExerciseConfig ID {config.id}.")
        issues: List[StructuredIssue] = []

        if not current_phase_name:
            logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep}: No phase context for frame, skipping joint angle rules.")
            return issues

        jar_data = None
        # Try to get joint_angle_rules as a dictionary
        if hasattr(config, 'joint_angle_rules') and config.joint_angle_rules is not None:
            if hasattr(config.joint_angle_rules, 'model_dump') and callable(config.joint_angle_rules.model_dump):
                jar_data = config.joint_angle_rules.model_dump()
            elif isinstance(config.joint_angle_rules, dict):
                jar_data = config.joint_angle_rules
        
        if jar_data is None:
            logger.warning(f"Rep {rep_index}, Frame {frame_index_in_rep}: Could not obtain joint_angle_rules as a dict from config.")
            return issues

        # Get rules for all phases
        phase_rules_from_jar = jar_data.get("phases")
        if not isinstance(phase_rules_from_jar, dict):
            logger.warning(f"Rep {rep_index}, Frame {frame_index_in_rep}: 'phases' key missing or not a dict in joint_angle_rules.")
            return issues

        # Get rules for the current phase, fallback to "default" if current phase not found
        phase_specific_rules_data = phase_rules_from_jar.get(current_phase_name)
        if not phase_specific_rules_data:
            phase_specific_rules_data = phase_rules_from_jar.get("default")
        
        if not phase_specific_rules_data or not isinstance(phase_specific_rules_data, dict):
            logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep}: No specific or default phase rules found for phase '{current_phase_name}'.")
            return issues

        # Angle rules for the specific or default phase. This variable is what the subsequent loop expects.
        angle_rules_for_current_phase = phase_specific_rules_data.get("angles")
        if not angle_rules_for_current_phase or not isinstance(angle_rules_for_current_phase, dict):
            logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep}: No 'angles' dict in rules for phase '{current_phase_name}'.")
            return issues

        # THE REST OF THE METHOD (LOOPING THROUGH frame_angles.items() AND APPLYING RULES) REMAINS UNCHANGED
        # FROM ITS STATE *BEFORE* THE FAILED `jar_data` REFACTORING ATTEMPTS.
        # The following is the original logic for iterating and applying rules which should be preserved.
        for joint_name, angle in frame_angles.items():
            rule_for_joint = angle_rules_for_current_phase.get(joint_name) # Get specific rule for this joint
            
            if not rule_for_joint:
                rule_for_joint = angle_rules_for_current_phase.get("default") # Fallback to default rule for phase
                if not rule_for_joint:
                    logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep}: No rule for joint '{joint_name}' or default in phase '{current_phase_name}'.")
                continue

            if not isinstance(rule_for_joint, dict):
                logger.warning(f"Rep {rep_index}, Frame {frame_index_in_rep}: Rule for joint '{joint_name}' in phase '{current_phase_name}' is not a dict. Rule: {rule_for_joint}")
                continue

            logger.info(f"CHECKING RULE: Rep {rep_index}, Frame {frame_index_in_rep}, Phase: {current_phase_name}, Joint: {joint_name}, Angle: {angle}, Rule: {rule_for_joint}")

            try:
                min_angle = rule_for_joint.get("min_angle")
                max_angle = rule_for_joint.get("max_angle")
                ideal_angle = rule_for_joint.get("ideal_angle")
                tolerance = rule_for_joint.get("tolerance", 0)
                
                violation = None
                details_msg = ""
                deviation_val = 0

                if min_angle is not None and angle < min_angle:
                    violation = "below_min"
                    deviation_val = min_angle - angle
                    details_msg = f"{joint_name} angle ({angle:.1f}°) is below minimum ({min_angle:.1f}°)."
                elif max_angle is not None and angle > max_angle:
                    violation = "above_max"
                    deviation_val = angle - max_angle
                    details_msg = f"{joint_name} angle ({angle:.1f}°) is above maximum ({max_angle:.1f}°)."

                if not violation and ideal_angle is not None:
                    ideal_min = ideal_angle - tolerance
                    ideal_max = ideal_angle + tolerance
                    if angle < ideal_min:
                        violation = "below_ideal_range"
                        deviation_val = ideal_min - angle
                        details_msg = f"{joint_name} angle ({angle:.1f}°) is below ideal range ({ideal_min:.1f}° - {ideal_max:.1f}°)."
                    elif angle > ideal_max:
                        violation = "above_ideal_range"
                        deviation_val = angle - ideal_max
                        details_msg = f"{joint_name} angle ({angle:.1f}°) is above ideal range ({ideal_min:.1f}° - {ideal_max:.1f}°)."
                
                if violation:
                    severity_val: FeedbackSeverity
                    if tolerance > 0: # Avoid division by zero if tolerance is 0
                        if deviation_val <= tolerance / 2:
                            severity_val = FeedbackSeverity.LOW
                        elif deviation_val <= tolerance:
                            severity_val = FeedbackSeverity.MEDIUM
                        else: # deviation_val > tolerance
                            severity_val = FeedbackSeverity.HIGH
                    elif deviation_val > 0: # If tolerance is zero or less, any deviation is high
                        severity_val = FeedbackSeverity.HIGH
                    else: # No deviation and zero/negative tolerance (should not happen with valid config)
                        severity_val = FeedbackSeverity.LOW # Default to LOW if no deviation

                    # The original logic that bumped LOW to MEDIUM for min/max violations is removed
                    # to align with typical deviation/tolerance based severity bands.

                    issues.append(StructuredIssue(
                        rule_type="joint_angle",
                        joint_name=joint_name,
                        details=f"{details_msg} During {current_phase_name} phase.",
                        severity=severity_val.value,
                        phase=current_phase_name,
                        rep_index=rep_index,
                        frame_index_in_rep=frame_index_in_rep,
                        timestamp_in_video=frame_timestamp,
                        current_value=round(angle, 2),
                        expected_value={"ideal_angle": ideal_angle, "tolerance": tolerance, "ideal_range": [round(ideal_angle - tolerance,1), round(ideal_angle+tolerance,1)] if ideal_angle is not None else None, "min_angle": min_angle, "max_angle": max_angle},
                        deviation=round(deviation_val, 2),
                        violation_type=violation
                    ))
            except Exception as e:
                logger.error(f"Error processing rule for joint {joint_name} in phase {current_phase_name}: {e}", exc_info=True)
                issues.append(StructuredIssue(
                    rule_type="internal_error",
                    details=f"Error processing joint angle rule for {joint_name}: {str(e)}",
                    severity=FeedbackSeverity.ERROR.value,
                    phase=current_phase_name,
                    rep_index=rep_index
                ))

        return issues

    async def _apply_rom_rules(
        self,
        rep_angle_data: List[Dict[str, Any]], # Full data for the current repetition
        rep_index: int,
        config: ExerciseConfig
    ) -> List[StructuredIssue]:
        logger.debug(f"Rep {rep_index}: Applying ROM rules using ExerciseConfig ID {config.id}.")
        issues: List[StructuredIssue] = []

        if not config.rom_rules or not isinstance(config.rom_rules, list):
            logger.debug(f"Rep {rep_index}: No ROM rules defined in config or not a list. Skipping ROM checks.")
            return issues

        if not rep_angle_data:
            logger.warning(f"Rep {rep_index}: Repetition angle data is empty. Cannot apply ROM rules.")
            return issues

        for rom_rule_data in config.rom_rules:
            if not isinstance(rom_rule_data, dict): # Ensure rule is a dict (parsed from JSON)
                logger.warning(f"Rep {rep_index}: Encountered a ROM rule that is not a dictionary. Skipping rule: {rom_rule_data}")
                continue

            joint_name = rom_rule_data.get("joint_name")
            min_angle_overall_rule = rom_rule_data.get("min_angle_overall")
            max_angle_overall_rule = rom_rule_data.get("max_angle_overall")
            target_rom_rule = rom_rule_data.get("target_rom")
            tolerance_degrees_rule = rom_rule_data.get("tolerance_degrees", 10.0) # Default from schema

            if not joint_name or min_angle_overall_rule is None or max_angle_overall_rule is None:
                logger.warning(f"Rep {rep_index}: ROM rule for config {config.id} is missing joint_name, min_angle_overall, or max_angle_overall. Skipping rule: {rom_rule_data}")
                continue

            observed_min_angle_for_joint = float('inf')
            observed_max_angle_for_joint = float('-inf')
            joint_angles_for_rep: List[float] = []
            # Store first and last valid timestamp for potential use in StructuredIssue
            first_valid_timestamp: Optional[float] = None
            last_valid_timestamp: Optional[float] = None


            for frame_data in rep_angle_data:
                if frame_data and isinstance(frame_data.get("angles"), dict):
                    angle_value = frame_data["angles"].get(joint_name)
                    if angle_value is not None and isinstance(angle_value, (int, float)):
                        joint_angles_for_rep.append(angle_value)
                        observed_min_angle_for_joint = min(observed_min_angle_for_joint, angle_value)
                        observed_max_angle_for_joint = max(observed_max_angle_for_joint, angle_value)
                        
                        current_timestamp = frame_data.get("timestamp")
                        if current_timestamp is not None:
                            if first_valid_timestamp is None:
                                first_valid_timestamp = current_timestamp
                            last_valid_timestamp = current_timestamp
            
            if not joint_angles_for_rep: # No valid angles found for this joint in the rep
                logger.debug(f"Rep {rep_index}: No angle data found for joint '{joint_name}' in this repetition. Skipping ROM check for this joint.")
                continue

            # Check if observed min/max meet overall requirements
            violation_type: Optional[str] = None
            current_deviation = 0.0
            issue_description = ""
            expected_values_dict: Dict[str, Any] = {
                "rule_min_overall": min_angle_overall_rule,
                "rule_max_overall": max_angle_overall_rule,
                "target_rom": target_rom_rule,
                "tolerance_degrees": tolerance_degrees_rule
            }
            observed_rom_value = observed_max_angle_for_joint - observed_min_angle_for_joint

            if observed_min_angle_for_joint > min_angle_overall_rule:
                violation_type = "failed_to_reach_min_rom"
                current_deviation = observed_min_angle_for_joint - min_angle_overall_rule
                issue_description = f"{joint_name} did not reach required minimum angle. Observed min: {observed_min_angle_for_joint:.1f}°, Expected min: {min_angle_overall_rule:.1f}°."
            elif observed_max_angle_for_joint < max_angle_overall_rule:
                violation_type = "failed_to_reach_max_rom"
                current_deviation = max_angle_overall_rule - observed_max_angle_for_joint
                issue_description = f"{joint_name} did not reach required maximum angle. Observed max: {observed_max_angle_for_joint:.1f}°, Expected max: {max_angle_overall_rule:.1f}°."

            # If target ROM is specified, check that too, but only if no min/max violation occurred first.
            if not violation_type and target_rom_rule is not None:
                if abs(observed_rom_value - target_rom_rule) > tolerance_degrees_rule:
                    violation_type = "deviation_from_target_rom"
                    current_deviation = abs(observed_rom_value - target_rom_rule)
                    # Distinguish between too much or too little ROM if possible
                    if observed_rom_value > target_rom_rule:
                         issue_description = f"{joint_name} ROM ({observed_rom_value:.1f}°) exceeded target ROM ({target_rom_rule:.1f}°) by {current_deviation:.1f}° (more than {tolerance_degrees_rule:.1f}° tolerance)."
                    else:
                         issue_description = f"{joint_name} ROM ({observed_rom_value:.1f}°) was less than target ROM ({target_rom_rule:.1f}°) by {current_deviation:.1f}° (more than {tolerance_degrees_rule:.1f}° tolerance)."
            
            if violation_type:
                # Use tolerance_degrees_rule from the ROM rule for severity calculation,
                # as it's specific to ROM deviation rather than general angle tolerance.
                severity = self.calculate_severity(current_deviation, tolerance_degrees_rule)
                
                # Use a representative timestamp, e.g., midpoint of the rep, or None
                # For simplicity, can use first_valid_timestamp if available, or None.
                # A more sophisticated approach might find the exact frame of min/max violation.
                representative_timestamp = first_valid_timestamp 

                issues.append({
                    "rule_type": "rom",
                    "joint_name": joint_name,
                    "details": issue_description,
                    "severity": severity,
                    "phase": "full_repetition", # ROM issues are typically for the whole rep
                    "rep_index": rep_index,
                    "frame_index_in_rep": None, # ROM is rep-level
                    "timestamp_in_video": representative_timestamp, 
                    "current_value": {"observed_min": observed_min_angle_for_joint, "observed_max": observed_max_angle_for_joint, "observed_rom": observed_rom_value},
                    "expected_value": expected_values_dict,
                    "deviation": current_deviation,
                    "violation_type": violation_type
                })
        
        if issues:
            logger.debug(f"Rep {rep_index}: Found {len(issues)} ROM issues.")
        return issues

    async def _apply_posture_rules(
        self,
        frame_data: Dict[str, Any], # CHANGED: Takes full frame_data now
        rep_index: int,
        current_phase_name: str,
        frame_timestamp: Optional[float],
        frame_index_in_rep: int,
        config: ExerciseConfig
    ) -> List[StructuredIssue]:
        logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep} ({current_phase_name}): Applying posture rules using ExerciseConfig ID {config.id}.")
        issues: List[StructuredIssue] = []

        if not config.posture_rules or not isinstance(config.posture_rules, list):
            logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep}: No posture_rules defined in config or not a list. Skipping posture checks.")
            return issues

        raw_landmarks_for_frame = frame_data.get('raw_landmarks') # Expect this key in frame_data
        if not raw_landmarks_for_frame or not isinstance(raw_landmarks_for_frame, list):
            logger.warning(f"Rep {rep_index}, Frame {frame_index_in_rep}: 'raw_landmarks' missing or not a list in frame_data. Cannot apply posture rules.")
            return issues

        for posture_rule_data in config.posture_rules:
            if not isinstance(posture_rule_data, dict):
                logger.warning(f"Rep {rep_index}, Frame {frame_index_in_rep}: Encountered a posture rule that is not a dictionary. Skipping: {posture_rule_data}")
                continue

            rule_name = posture_rule_data.get("rule_name", "Unnamed Posture Rule")
            applicable_phases = posture_rule_data.get("applicable_phases")
            conditions = posture_rule_data.get("conditions") # Expected to be List[Dict]

            if applicable_phases and isinstance(applicable_phases, list) and current_phase_name not in applicable_phases:
                continue # Rule not for this phase

            if not conditions or not isinstance(conditions, list):
                logger.warning(f"Rep {rep_index}, Frame {frame_index_in_rep}: Posture rule '{rule_name}' has no conditions or conditions not a list. Skipping.")
                continue

            for condition_data in conditions:
                if not isinstance(condition_data, dict):
                    logger.warning(f"Rep {rep_index}, Frame {frame_index_in_rep}: Posture rule '{rule_name}' has a condition that is not a dictionary. Skipping condition: {condition_data}")
                    continue

                condition_type = condition_data.get("condition_type")
                
                # --- Handle 'vector_angle_from_vertical' condition type ---
                if condition_type == "vector_angle_from_vertical":
                    keypoints_for_vector = condition_data.get("keypoints_for_vector")
                    expected_angle_deg_config = condition_data.get("expected_angle_degrees")
                    max_deviation_deg_config = condition_data.get("max_deviation_degrees")

                    if not (isinstance(keypoints_for_vector, list) and len(keypoints_for_vector) == 2 and
                            all(isinstance(kp, str) for kp in keypoints_for_vector) and
                            isinstance(expected_angle_deg_config, (int, float)) and
                            isinstance(max_deviation_deg_config, (int, float))):
                        logger.warning(f"Rep {rep_index}, Frame {frame_index_in_rep}: Posture rule '{rule_name}', condition '{condition_type}' has malformed parameters. Skipping condition. Data: {condition_data}")
                        continue

                    kp1_name, kp2_name = keypoints_for_vector[0], keypoints_for_vector[1]
                    
                    coords1 = self._get_keypoint_coords_by_name(kp1_name, raw_landmarks_for_frame)
                    coords2 = self._get_keypoint_coords_by_name(kp2_name, raw_landmarks_for_frame)

                    if not coords1 or not coords2:
                        logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep}: Could not get coordinates for keypoints '{kp1_name}' or '{kp2_name}' for posture rule '{rule_name}'. Skipping condition.")
                        continue
                    
                    x1, y1 = coords1
                    x2, y2 = coords2

                    dx = x2 - x1
                    dy = y2 - y1 # Positive dy means p2 is "below" p1 in image coordinates

                    if dx == 0 and dy == 0: # Points are the same
                        logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep}: Keypoints '{kp1_name}' and '{kp2_name}' for posture rule '{rule_name}' are at the same position. Skipping vector calculation.")
                        continue

                    # Angle of vector (p1->p2) with positive Y-axis (pointing downwards).
                    # Result is in radians, range -pi to pi.
                    # 0 rad: vector points straight down.
                    # pi/2 rad (90 deg): vector points to the right.
                    # -pi/2 rad (-90 deg): vector points to the left.
                    # pi or -pi rad (180 deg): vector points straight up.
                    observed_angle_rad = math.atan2(dx, dy)
                    observed_angle_deg = math.degrees(observed_angle_rad)

                    # Calculate angular difference, handling wrapping.
                    # diff = 180 - abs(abs(a1 - a2) - 180)
                    angular_diff = 180.0 - abs(abs(observed_angle_deg - expected_angle_deg_config) - 180.0)

                    if angular_diff > max_deviation_deg_config:
                        severity_str = posture_rule_data.get("severity", FeedbackSeverity.MEDIUM.value)
                        calculated_severity = self.calculate_severity(angular_diff, max_deviation_deg_config) # Use condition's max_dev for severity threshold

                        issue_description = (
                            f"Posture issue: '{rule_name}'. Vector '{kp1_name}' to '{kp2_name}' "
                            f"angle ({observed_angle_deg:.1f}°) deviates from expected ({expected_angle_deg_config:.1f}°) "
                            f"by {angular_diff:.1f}°, exceeding max deviation of {max_deviation_deg_config:.1f}°."
                        )
                        issues.append({
                            "rule_type": "posture",
                            "joint_name": None, # Posture might involve multiple points, not a single "joint"
                            "details": issue_description,
                            "severity": calculated_severity,
                            "phase": current_phase_name,
                            "rep_index": rep_index,
                            "frame_index_in_rep": frame_index_in_rep,
                            "timestamp_in_video": frame_timestamp,
                            "current_value": {"observed_vector_angle_from_vertical_degrees": observed_angle_deg},
                            "expected_value": {
                                "vector_defined_by": keypoints_for_vector,
                                "expected_angle_from_vertical_degrees": expected_angle_deg_config,
                                "max_deviation_degrees": max_deviation_deg_config
                            },
                            "deviation": angular_diff,
                            "violation_type": f"{rule_name}_deviation" # Specific posture violation
                        })
                # Add other condition_types for posture here (e.g., distance between keypoints, planarity)
                else:
                    logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep}: Posture rule '{rule_name}' has unknown condition_type '{condition_type}'. Skipping condition.")

        if issues:
            logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep} ({current_phase_name}): Found {len(issues)} posture issues.")
        return issues

    async def _apply_symmetry_rules(
        self,
        frame_angles: Dict[str, float],
        rep_index: int,
        current_phase_name: str,
        frame_timestamp: Optional[float],
        frame_index_in_rep: int,
        config: ExerciseConfig
    ) -> List[StructuredIssue]:
        logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep} ({current_phase_name}): Applying symmetry rules using ExerciseConfig ID {config.id}.")
        issues: List[StructuredIssue] = []

        if not config.symmetry_rules or not isinstance(config.symmetry_rules, list):
            logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep}: No symmetry_rules defined in config or not a list. Skipping symmetry checks.")
            return issues

        for symmetry_rule_data in config.symmetry_rules:
            if not isinstance(symmetry_rule_data, dict):
                logger.warning(f"Rep {rep_index}, Frame {frame_index_in_rep}: Encountered a symmetry rule that is not a dictionary. Skipping: {symmetry_rule_data}")
                continue

            joint_pair = symmetry_rule_data.get("joint_pair") # Expected: List[str, str] or Tuple[str, str]
            max_diff_degrees_config = symmetry_rule_data.get("max_difference_degrees")
            applicable_phases = symmetry_rule_data.get("applicable_phases")

            if applicable_phases and isinstance(applicable_phases, list) and current_phase_name not in applicable_phases:
                continue # Rule not for this phase

            if not (isinstance(joint_pair, (list, tuple)) and len(joint_pair) == 2 and
                    all(isinstance(jp, str) for jp in joint_pair) and
                    isinstance(max_diff_degrees_config, (int, float))):
                logger.warning(f"Rep {rep_index}, Frame {frame_index_in_rep}: Symmetry rule has malformed joint_pair or max_difference_degrees. Skipping rule. Data: {symmetry_rule_data}")
                continue
            
            joint1_name, joint2_name = joint_pair[0], joint_pair[1]

            angle1 = frame_angles.get(joint1_name)
            angle2 = frame_angles.get(joint2_name)

            if angle1 is None or angle2 is None:
                # If one angle is missing, we can't check symmetry for this pair in this frame.
                # Could log this, or create a specific type of issue if symmetry is critical.
                logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep}: Missing angle for '{joint1_name}' or '{joint2_name}' for symmetry check. Skipping pair.")
                continue
            
            abs_difference = abs(angle1 - angle2)

            if abs_difference > max_diff_degrees_config:
                severity_str = symmetry_rule_data.get("severity", FeedbackSeverity.MEDIUM.value) # Default severity if not in rule data
                # Use max_diff_degrees_config as the tolerance for severity calculation
                calculated_severity = self.calculate_severity(abs_difference, max_diff_degrees_config) 

                issue_description = (
                    f"Symmetry issue: Difference between {joint1_name} ({angle1:.1f}°) and {joint2_name} ({angle2:.1f}°) "
                    f"is {abs_difference:.1f}°, exceeding max allowed difference of {max_diff_degrees_config:.1f}°."
                )
                issues.append({
                    "rule_type": "symmetry",
                    "joint_name": joint1_name, # Primary joint for reporting, or could be a list/tuple
                    "compared_to_joint": joint2_name, # The other joint in the symmetric pair
                    "details": issue_description,
                    "severity": calculated_severity,
                    "phase": current_phase_name,
                    "rep_index": rep_index,
                    "frame_index_in_rep": frame_index_in_rep,
                    "timestamp_in_video": frame_timestamp,
                    "current_value": {"joint1_angle": angle1, "joint2_angle": angle2, "difference": abs_difference},
                    "expected_value": {"max_difference_degrees": max_diff_degrees_config},
                    "deviation": abs_difference - max_diff_degrees_config, # Positive value indicates how much it exceeded the threshold
                    "violation_type": f"asymmetry_{joint1_name}_{joint2_name}"
                })

        if issues:
            logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep} ({current_phase_name}): Found {len(issues)} symmetry issues.")
        return issues

    # --- END MODULAR RULE EVALUATOR STUBS ---

    async def evaluate_rep(
        self, 
        rep_angle_data: List[Dict[str, Any]], # List of frame data for one rep
                                             # Each frame_data dict should have 'frame_num', 'timestamp', 'angles', 'raw_landmarks'
        rep_index: int, # Added rep_index for context
        config: ExerciseConfig
    ) -> Tuple[List[StructuredIssue], float]: # MODIFIED: Returns List[StructuredIssue]
        """
        Evaluates a single repetition against the exercise configuration by orchestrating
        calls to modular rule evaluators.
        """
        logger.info(f"Evaluating Repetition {rep_index} with {len(rep_angle_data)} frames using config: {config.name}")
        all_rep_issues: List[StructuredIssue] = []

        if not rep_angle_data or not config:
            logger.warning(f"Rep {rep_index}: Insufficient data for rep evaluation: missing angle data or config.")
            return [], 0.0 # Default score 0 if no data

        # 1. Per-frame analysis: Iterate through each frame in the repetition
        for frame_idx, frame_data in enumerate(rep_angle_data): # frame_data is now the comprehensive dict
            current_phase_name = frame_data.get("phase_context", "unknown")
            # if rep_index == 1:
            #     logger.info(f"DEBUG_BAD_REP: Processing frame_idx {frame_idx} for rep_index {rep_index}. Frame data: {json.dumps(frame_data, indent=2)}")

            # Ensure frame_data contains 'angles'; if not, it might be an empty frame from previous steps
            if not frame_data:
                logger.warning(f"Rep {rep_index}, Frame {frame_idx}: Skipping frame due to empty frame_data.")
                continue
            
            frame_angles = frame_data.get("angles")
            if frame_angles is None: # Can be an empty dict, but not None
                logger.warning(f"Rep {rep_index}, Frame {frame_idx}: Skipping frame due to missing 'angles' in frame_data.")
                # if rep_index == 1:
                #     logger.info(f"DEBUG_BAD_REP: Frame {frame_idx} for rep_index {rep_index} had no 'angles'.")
                continue

            # if rep_index == 1:
            #      logger.info(f"DEBUG_BAD_REP: Rep {rep_index}, Frame {frame_idx}, Angles pre-rules: {json.dumps(frame_angles)}")
            
            frame_timestamp = frame_data.get("timestamp") # Assuming timestamp is available per frame
            
            # 2. Get movement phase for the current frame from the context provided by segment_repetitions
            current_phase_name = frame_data.get('phase_context')
            if not current_phase_name:
                logger.warning(f"Rep {rep_index}, Frame {frame_idx}: Phase context missing from frame_data. Skipping rule checks for this frame.")
                continue
            
            logger.debug(f"Rep {rep_index}, Frame {frame_idx}: Processing with phase context: {current_phase_name}")

            # 3. Apply modular rule evaluators for the current frame
            all_rep_issues.extend(await self._apply_joint_angle_rules(
                frame_angles, rep_index, current_phase_name, frame_timestamp, frame_idx, config
            ))
            all_rep_issues.extend(await self._apply_posture_rules(
                frame_data, rep_index, current_phase_name, frame_timestamp, frame_idx, config # CHANGED: pass full frame_data
            ))
            all_rep_issues.extend(await self._apply_symmetry_rules(
                frame_angles, rep_index, current_phase_name, frame_timestamp, frame_idx, config
            ))

        # 4. Apply rules that evaluate the entire repetition (e.g., ROM)
        all_rep_issues.extend(await self._apply_rom_rules(
            rep_angle_data, rep_index, config
        ))
        
        # 5. Calculate score for the repetition based on aggregated issues
        # This scoring logic needs to be defined. For now, a simple placeholder.
        # Higher score is better. Start with 100 and deduct.
        current_rep_score = 100.0
        for issue in all_rep_issues:
            if issue.get("severity") == FeedbackSeverity.HIGH.value:
                current_rep_score -= 15
            elif issue.get("severity") == FeedbackSeverity.MEDIUM.value:
                current_rep_score -= 10
            elif issue.get("severity") == FeedbackSeverity.LOW.value:
                current_rep_score -= 5
        current_rep_score = max(0.0, current_rep_score) # Ensure score doesn't go below 0

        logger.info(f"Repetition {rep_index}: Evaluation complete. Found {len(all_rep_issues)} issues. Score: {current_rep_score:.2f}")
        
        # The old `generate_feedback` is now part of `analyze_form_dynamically` after collecting all issues.
        # `evaluate_rep` now returns the structured issues.
        return all_rep_issues, current_rep_score

    async def analyze_form_dynamically(self, video: Video) -> FormCheck:
        """
        Analyze form dynamically from a video object.
        
        This method handles the complete flow: fetching config, creating form check,
        and performing analysis. It also integrates with the enhanced AIService for
        ML-based form analysis when appropriate.
        
        Args:
            video: Video object with pose/angle data
            
        Returns:
            FormCheck object with analysis results
        """
        logger.info(f"Starting dynamic form analysis for Video ID: {video.id}")
        
        # Create a new form check for this analysis
        from app.schemas.form_check import FormCheckCreate
        form_check_data = FormCheckCreate(
            video_id=video.id,
            exercise_template_id=video.exercise_template_id if hasattr(video, 'exercise_template_id') else None,
            status="processing"
        )
        
        try:
            initial_form_check = await self.form_check_service.create_async(form_check_data)
        except Exception as e:
            logger.error(f"Failed to create form check for video {video.id}: {e}")
            # Create a minimal form check object for error handling
            initial_form_check = FormCheck(
                video_id=video.id,
                status=FormCheckStatus.FAILED,
                error_details=f"Failed to create form check: {str(e)}",
                score=0.0
            )
            return initial_form_check
        
        # Get exercise configuration
        exercise_config = None
        if hasattr(video, 'exercise_template_id') and video.exercise_template_id:
            try:
                exercise_config = await self._get_exercise_config_model_async(video.exercise_template_id)
            except Exception as e:
                logger.warning(f"Failed to get exercise config for video {video.id}: {e}")
        
        # Enhanced ML-based analysis for squats
        if (self.ai_service and 
            hasattr(video, 'exercise_type') and 
            video.exercise_type and 
            video.exercise_type.lower() == 'squat' and
            hasattr(video, 'raw_pose_data') and 
            video.raw_pose_data):
            
            try:
                logger.info(f"Using enhanced AIService for squat analysis on video {video.id}")
                
                # Get the best pose data for analysis
                pose_data = video.pose_data if hasattr(video, 'pose_data') and video.pose_data else video.raw_pose_data
                
                if pose_data:
                    # Find the best frame with highest confidence for analysis
                    best_frame = None
                    best_confidence = 0.0
                    
                    for frame_data in pose_data:
                        if frame_data and isinstance(frame_data, list):
                            # Calculate frame confidence (average of landmark confidences)
                            confidences = []
                            for landmark in frame_data:
                                if isinstance(landmark, dict) and 'visibility' in landmark:
                                    confidences.append(landmark['visibility'])
                            
                            if confidences:
                                frame_confidence = np.mean(confidences)
                                if frame_confidence > best_confidence:
                                    best_confidence = frame_confidence
                                    best_frame = frame_data
                    
                    if best_frame and best_confidence > 0.5:  # Minimum confidence threshold
                        # Call enhanced AIService analyze_form method
                        analysis_result = await self.ai_service.analyze_form(
                            landmarks=best_frame,
                            exercise_type='squat'
                        )
                        
                        # Update form check with ML results
                        initial_form_check.score = analysis_result.get('score', 0.0)
                        initial_form_check.overall_score = analysis_result.get('score', 0.0)
                        initial_form_check.summary = f"ML Analysis: {analysis_result.get('analysis_method', 'unknown')} method used"
                        initial_form_check.status = FormCheckStatus.COMPLETED
                        
                        # Convert AIService feedback to FeedbackItems
                        feedback_items = []
                        for feedback in analysis_result.get('feedback_structured', []):
                            feedback_item = FeedbackItem(
                                form_check_id=initial_form_check.id,
                                type=feedback.get('type', FeedbackType.TECHNIQUE),
                                message=feedback.get('message', ''),
                                timestamp=feedback.get('timestamp', 0.0),
                                severity=feedback.get('severity', FeedbackSeverity.INFO),
                                suggestions=feedback.get('suggestions', [])
                            )
                            feedback_items.append(feedback_item)
                        
                        initial_form_check.feedback_items = feedback_items
                        
                        logger.info(f"ML analysis completed for video {video.id}: score={initial_form_check.score:.1f}, method={analysis_result.get('analysis_method')}")
                        return initial_form_check
                    
            except Exception as e:
                logger.error(f"ML-based analysis failed for video {video.id}, falling back to rule-based: {e}")
        
        # Fall back to rule-based analysis if ML analysis isn't available or failed
        if exercise_config:
            return await self._analyze_form_dynamically_with_config(video, exercise_config, initial_form_check)
        else:
            # No config available, use basic rule-based analysis
            logger.warning(f"No exercise config available for video {video.id}, using basic analysis")
            initial_form_check.status = FormCheckStatus.COMPLETED
            initial_form_check.score = 50.0  # Default score when no analysis possible
            initial_form_check.summary = "Basic analysis completed - no exercise configuration available"
            return initial_form_check
    
    async def _analyze_form_dynamically_with_config(
        self,
        video: Video, # Video object with angle_data populated
        exercise_config: ExerciseConfig, # The active exercise configuration
        initial_form_check: FormCheck    # The existing FormCheck record to update
    ) -> FormCheck:
        config_name_for_log = exercise_config.name if exercise_config else "No Config Provided"
        logger.info(f"Starting dynamic form analysis for FormCheck ID: {initial_form_check.id}, Video ID: {video.id}, Config: {config_name_for_log}")

        if video.angle_data is None:
            logger.warning(f"Video ID {video.id} has no angle data (is None). Cannot perform dynamic analysis.")
            initial_form_check.status = FormCheckStatus.FAILED # Use enum member FAILED
            initial_form_check.error_details = "Angle data missing from video (was None)."
            initial_form_check.summary = "Analysis failed: Angle data not available."
            initial_form_check.score = 0.0
            # No db.commit() here, caller (Celery task) should handle session management
            return initial_form_check
        
        if not exercise_config:
            logger.warning(f"FormCheck {initial_form_check.id}: ExerciseConfig is missing. Cannot perform analysis.")
            initial_form_check.status = FormCheckStatus.FAILED # Use enum member FAILED
            initial_form_check.error_details = "Exercise configuration missing."
            initial_form_check.summary = "Analysis failed: Exercise configuration not available."
            initial_form_check.score = 0.0
            return initial_form_check

        all_reps_issues: List[StructuredIssue] = []
        all_reps_scores: List[float] = []
        total_valid_frames_analyzed = 0
        processed_repetitions: List[List[Dict[str, Any]]] = []

        try:
            # 1. Segment into repetitions
            logger.debug(f"FormCheck {initial_form_check.id}: Segmenting {len(video.angle_data)} frames into repetitions.")
            processed_repetitions = await self.segment_repetitions(
                angle_data_sequence=video.angle_data, # type: ignore # angle_data is List[Dict] typically
                config=exercise_config
            )

            if not processed_repetitions and not video.angle_data: # angle_data was an empty list
                logger.warning(f"FormCheck {initial_form_check.id}: Angle data was an empty list. No repetitions segmented.")
                initial_form_check.summary = "No repetitions detected (empty angle data)."
                initial_form_check.score = 0.0
                # Status will be set to COMPLETED later
            elif not processed_repetitions: # angle_data was non-empty, but still no reps found
                logger.warning(f"FormCheck {initial_form_check.id}: No repetitions were segmented from the (non-empty) angle data.")
                initial_form_check.summary = "No complete repetitions detected from provided angle data."
                initial_form_check.score = 0.0 # Or some other baseline score
                # initial_form_check.status can remain PROCESSING or be set based on policy
                # For now, let's assume if no reps, it's not an ERROR but perhaps needs review or score reflects it

            # 2. Evaluate each repetition
            for i, rep_angle_data in enumerate(processed_repetitions):
                logger.debug(f"FormCheck {initial_form_check.id}: Evaluating Rep {i + 1} with {len(rep_angle_data)} frames.")
                rep_issues, rep_score = await self.evaluate_rep(
                    rep_angle_data=rep_angle_data,
                    rep_index=i,
                    config=exercise_config
                )
                all_reps_issues.extend(rep_issues)
                all_reps_scores.append(rep_score)
                total_valid_frames_analyzed += len([f for f in rep_angle_data if f.get('angles')])

            # 3. Aggregate results and update FormCheck object
            if all_reps_scores:
                initial_form_check.score = float(np.mean(all_reps_scores)) # Example: average score
            elif processed_repetitions: # Reps were segmented but scores might be empty if evaluate_rep had issues
                 initial_form_check.score = 0.0 # Or a score indicating issues in rep evaluation
            else: # No reps segmented
                initial_form_check.score = 0.0
            
            # Create FeedbackItem objects from structured issues
            # This part should ideally be in FormCheckService or a shared utility if complex,
            # but for now, let's create them here and attach to the FormCheck. Session commit is handled by caller.
            
            # Clear existing feedback items if any (safer to do this before adding new ones)
            # This assumes initial_form_check.feedback_items is a mutable list, or relationship is handled by SQLAlchemy
            # If initial_form_check is from a session, modifying .feedback_items should mark for ORM events.
            # A more robust way is to delete existing items by form_check_id in the DB via service call before adding new ones,
            # which the Celery task already does in finalize_form_check_analysis_async.
            # So, here we just prepare the new items.
            
            new_feedback_items: List[FeedbackItem] = []
            for issue in all_reps_issues:
                # Map StructuredIssue to FeedbackItem fields
                # This mapping needs to be robust
                feedback_type_enum = FeedbackType.FORM # Default to FORM
                rule_type_str = issue.get("rule_type", "form").lower()

                if rule_type_str == "symmetry":
                    feedback_type_enum = FeedbackType.TECHNIQUE
                elif rule_type_str == "rom":
                    feedback_type_enum = FeedbackType.RANGE
                elif rule_type_str == "joint_angle":
                    feedback_type_enum = FeedbackType.JOINT_ANGLE
                elif rule_type_str == "posture":
                    feedback_type_enum = FeedbackType.POSTURE
                else:
                    try:
                        # Attempt direct mapping for other types or if 'form' was explicitly set
                        feedback_type_enum = FeedbackType(rule_type_str)
                    except ValueError:
                        logger.warning(f"Could not map rule_type '{rule_type_str}' to FeedbackType enum. Defaulting to FeedbackType.FORM.")
                        feedback_type_enum = FeedbackType.FORM
                
                severity_enum = FeedbackSeverity.LOW # Default to LOW
                try:
                    sev_val = issue.get("severity", "low") # Default severity to 'low' if missing
                    if isinstance(sev_val, str): # Ensure it's a string before .lower()
                        severity_enum = FeedbackSeverity(sev_val.lower()) # Attempt to map by value (lowercase)
                    else: # Log if not a string
                        logger.warning(f"issue.severity ('{sev_val}') is not a string, using default FeedbackSeverity.LOW.")
                        severity_enum = FeedbackSeverity.LOW
                except ValueError: # If mapping by value fails
                    logger.warning(f"Could not map severity '{issue.get('severity')}' to FeedbackSeverity enum. Defaulting to FeedbackSeverity.LOW.")
                    severity_enum = FeedbackSeverity.LOW
                
                # Prepare details for FeedbackItem, ensuring it's serializable JSON
                feedback_details = {
                    "rule_type": issue.get("rule_type"),
                    "joint_name": issue.get("joint_name"),
                    "compared_to_joint": issue.get("compared_to_joint"),
                    "phase": issue.get("phase"),
                    "rep_index": issue.get("rep_index"),
                    "frame_index_in_rep": issue.get("frame_index_in_rep"),
                    "current_value": issue.get("current_value"),
                    "expected_value": issue.get("expected_value"),
                    "deviation": issue.get("deviation"),
                    "violation_type": issue.get("violation_type")
                }
                # Filter out None values to keep payload clean
                feedback_details = {k: v for k, v in feedback_details.items() if v is not None}

                item = FeedbackItem(
                    form_check_id=initial_form_check.id,
                    rule_id=issue.get("rule_id", f"rule_type:{issue.get('rule_type', 'unknown')}"), # Fallback rule_id if not present
                    message=issue.get("details", "Form issue detected."), # Main human-readable message from StructuredIssue
                    type=feedback_type_enum,
                    severity=severity_enum,
                    details_payload=feedback_details, # Store the structured details from the issue
                    timestamp=issue.get("timestamp_in_video", 0.0), # Use 0.0 as a float default for timestamp
                    suggestions=[], # Suggestions to be populated later if applicable
                    # Directly populate specific fields from details for easier access/querying
                    rep_index=feedback_details.get("rep_index"),
                    movement_phase=feedback_details.get("phase"), # 'phase' in details maps to 'movement_phase'
                    joint_name=feedback_details.get("joint_name")
                )
                new_feedback_items.append(item)
            
            initial_form_check.feedback_items = new_feedback_items # Replace or append based on ORM setup

            # Generate a summary
            if not all_reps_issues and processed_repetitions:
                initial_form_check.summary = f"Good form! {len(processed_repetitions)} reps analyzed with no major issues detected."
            elif all_reps_issues: # Ensure this is elif
                initial_form_check.summary = f"{len(all_reps_issues)} issues found across {len(processed_repetitions)} reps. Score: {initial_form_check.score:.2f}"
            elif not processed_repetitions: # This should be another elif
                initial_form_check.summary = "No complete repetitions detected during analysis."
            else: # This is the final case
                initial_form_check.summary = "Analysis completed."

            # Update status
            initial_form_check.status = FormCheckStatus("completed") # Use enum value
            initial_form_check.error_details = None # Clear previous errors if successful
            initial_form_check.analysis_completed_at = datetime.utcnow()

            # Add some details to the FormCheck.form_metadata JSON field
            if initial_form_check.form_metadata is None: initial_form_check.form_metadata = {}
            initial_form_check.form_metadata["dynamic_analysis_version"] = "1.0"
            initial_form_check.form_metadata["reps_detected"] = len(processed_repetitions)
            initial_form_check.form_metadata["frames_analyzed"] = total_valid_frames_analyzed
            initial_form_check.form_metadata["config_used"] = exercise_config.name
            initial_form_check.form_metadata["config_version"] = exercise_config.version
            # initial_form_check.form_metadata["risk_level"] = self.calculate_overall_risk(initial_form_check.score, all_reps_issues) # Placeholder

            # Directly set reps_detected on the FormCheck model instance as well
            initial_form_check.reps_detected = len(processed_repetitions)

            logger.info(f"Analysis completed. Score: {initial_form_check.score}")

        except Exception as e:
            current_exception_type = type(e).__name__
            current_exception_msg = str(e)
            logger.error(f"Error dynamic analysis FormCheck {initial_form_check.id}: {current_exception_type}", exc_info=True)
            initial_form_check.status = FormCheckStatus("failed") # Use enum value, FAILED not ERROR here
            # Use form_metadata for error details too, or ensure error_details field exists
            # FormCheck model does not have error_details. Let's use form_metadata.
            if initial_form_check.form_metadata is None: initial_form_check.form_metadata = {}
            initial_form_check.form_metadata["error_details"] = f"FAIL: {current_exception_type} - {current_exception_msg}"
            initial_form_check.summary = "An error occurred during detailed form analysis."
            initial_form_check.score = 0.0 # Or keep previous score if partial analysis done
            # feedback_items might be partially populated or empty

            error_message_to_store = current_exception_msg
            if hasattr(e, 'message') and isinstance(getattr(e, 'message'), str): # For some custom exceptions
                 error_message_to_store = getattr(e, 'message')

            # initial_form_check.error_details = error_message_to_store
            setattr(initial_form_check, 'error_details', error_message_to_store) # Corrected variable name
            initial_form_check.score = 0.0
            # initial_form_check.reps_detected = 0 # Avoid setting if it was never calculated

        return initial_form_check
    
    def detect_movement_phase(
        self,
        phases_config: Any,
        joint_angles: Dict[str, float]
    ) -> str:
        """
        Detect the current movement phase based on joint angles.
        Accepts either a Pydantic model for phases (from ExerciseConfig) or a dict.
        """
        phase_items = []
        if hasattr(phases_config, 'items'):
            phase_items = phases_config.items()
        elif isinstance(phases_config, dict):
            phase_items = phases_config.items()
        else:
            logger.warning("Phases config is not a dictionary or Pydantic model. Cannot detect phase.")
            return "unknown"

        for phase_name, phase_data_model in phase_items:
            triggers_dict = {}
            if hasattr(phase_data_model, 'triggers') and phase_data_model.triggers:
                 if isinstance(phase_data_model.triggers, dict):
                    triggers_dict = phase_data_model.triggers
                 elif hasattr(phase_data_model.triggers, 'model_dump'): # Check if it's a Pydantic model
                    triggers_dict = phase_data_model.triggers.model_dump()

            # Get the MovementPhaseTrigger object for the "next" key
            next_trigger_definition: Optional[MovementPhaseTrigger] = None
            raw_next_trigger = triggers_dict.get("next")

            if isinstance(raw_next_trigger, MovementPhaseTrigger):
                next_trigger_definition = raw_next_trigger
            elif isinstance(raw_next_trigger, dict): # If it was dumped from a model or is a raw dict
                try:
                    next_trigger_definition = MovementPhaseTrigger(**raw_next_trigger)
                except Exception as e:
                    logger.warning(f"Could not parse 'next' trigger for phase {phase_name} into MovementPhaseTrigger: {e}")

            if not next_trigger_definition or not next_trigger_definition.conditions:
                continue # No "next" trigger or no conditions for it

            all_satisfied = True
            # Iterate over the conditions within the MovementPhaseTrigger
            for condition_model in next_trigger_definition.conditions:
                # condition_model is now expected to be a Condition object or a dict representing it
                joint = None
                value = None
                comparator = None

                if hasattr(condition_model, 'joint'): # If Pydantic model
                    joint = condition_model.joint
                    value = condition_model.value
                    comparator = condition_model.comparator
                elif isinstance(condition_model, dict): # If dict from model_dump or raw
                    joint = condition_model.get("joint")
                    value = condition_model.get("value")
                    comparator = condition_model.get("comparator")
                
                if joint not in joint_angles or value is None or not comparator:
                    all_satisfied = False
                    break 
                    
                angle = joint_angles.get(joint)
                if angle is None:
                    all_satisfied = False
                    break
                
                satisfied = False
                if comparator == "<" and (angle < value): satisfied = True
                elif comparator == ">" and (angle > value): satisfied = True
                elif comparator == "==" and (angle == value): satisfied = True
                elif comparator == "<=" and (angle <= value): satisfied = True
                elif comparator == ">=" and (angle >= value): satisfied = True
                
                if not satisfied:
                    all_satisfied = False
                    break
            
            if all_satisfied:
                return phase_name
        
        return "unknown"
    
    def check_joint_angles(
        self,
        rules_config: Any,
        joint_angles: Dict[str, float],
        phase: str
    ) -> List[Dict[str, Any]]:
        """
        Check joint angles against phase-specific rules.
        Accepts Pydantic model for rules_config (from ExerciseConfig) or dict.
        """
        issues = []
        
        phases_rules_model = None
        if hasattr(rules_config, 'phases'):
            phases_rules_model = rules_config.phases 
        elif isinstance(rules_config, dict) and "phases" in rules_config:
             phases_rules_model = rules_config["phases"]
        else:
            logger.warning("Joint angle rules 'phases' structure not found in config.")
            return issues

        current_phase_rules_model = None
        if phases_rules_model and hasattr(phases_rules_model, 'get'):
            current_phase_rules_model = phases_rules_model.get(phase)
            if not current_phase_rules_model and "default" in phases_rules_model:
                 current_phase_rules_model = phases_rules_model.get("default")
        elif phases_rules_model and isinstance(phases_rules_model, dict):
            current_phase_rules_model = phases_rules_model.get(phase)
            if not current_phase_rules_model and "default" in phases_rules_model:
                 current_phase_rules_model = phases_rules_model.get("default")

        if not current_phase_rules_model:
            return issues
        
        angle_rules_map = {}
        if hasattr(current_phase_rules_model, 'angles'):
            angle_rules_map = current_phase_rules_model.angles
        elif isinstance(current_phase_rules_model, dict) and "angles" in current_phase_rules_model:
            angle_rules_map = current_phase_rules_model["angles"]

        if not angle_rules_map:
            return issues

        for joint, rule_model in angle_rules_map.items():
            if joint not in joint_angles:
                continue
                
            angle = joint_angles[joint]
            
            min_angle = rule_model.min_angle if hasattr(rule_model, 'min_angle') else rule_model.get("min_angle")
            max_angle = rule_model.max_angle if hasattr(rule_model, 'max_angle') else rule_model.get("max_angle")
            ideal_angle = rule_model.ideal_angle if hasattr(rule_model, 'ideal_angle') else rule_model.get("ideal_angle")
            tolerance_val = getattr(rule_model, 'tolerance', None) if hasattr(rule_model, 'tolerance') else rule_model.get("tolerance")
            tolerance = tolerance_val if tolerance_val is not None else 15.0


            current_deviation = 0.0
            issue_type = None
            expected_val_dict: Dict[str, Any] = {}


            if min_angle is not None and angle < min_angle:
                current_deviation = min_angle - angle
                issue_type = "below_min"
                expected_val_dict = {"min": min_angle}
            elif max_angle is not None and angle > max_angle:
                current_deviation = angle - max_angle
                issue_type = "above_max"
                expected_val_dict = {"max": max_angle}
            elif ideal_angle is not None and tolerance is not None:
                lower_bound_ideal = ideal_angle - tolerance
                upper_bound_ideal = ideal_angle + tolerance
                if angle < lower_bound_ideal or angle > upper_bound_ideal:
                    current_deviation = (lower_bound_ideal - angle) if angle < lower_bound_ideal else (angle - upper_bound_ideal)
                    issue_type = "non_ideal"
                    expected_val_dict = {"ideal": ideal_angle, "tolerance": tolerance}
            
            if issue_type:
                severity_tolerance_val = getattr(rule_model, 'severity_tolerance', tolerance)
                issues.append({
                    "joint": joint,
                    "actual": angle,
                    "expected": expected_val_dict,
                    "issue_type": issue_type,
                    "deviation": current_deviation,
                    "severity": self.calculate_severity(current_deviation, severity_tolerance_val)
                })
        
        return issues
    
    def calculate_severity(self, deviation: float, tolerance_for_severity: float) -> str:
        """
        Calculate severity based on deviation from expected angle.
        Tolerance here refers to how much deviation is allowed before it's considered an issue for severity calculation.
        """
        if tolerance_for_severity <= 0:
            tolerance_for_severity = 15.0

        abs_deviation = abs(deviation)

        if abs_deviation == 0:
            return FeedbackSeverity.NONE.value
        elif abs_deviation <= tolerance_for_severity / 2:
            return FeedbackSeverity.LOW.value
        elif abs_deviation <= tolerance_for_severity:
            return FeedbackSeverity.MEDIUM.value
        else:
            return FeedbackSeverity.HIGH.value

    def generate_feedback(
        self,
        templates_config: Any,
        issues: List[Dict[str, Any]],
        phase: str
    ) -> List[Dict[str, Any]]:
        """
        Generate specific feedback based on issues and templates.
        Accepts Pydantic model for templates_config (from ExerciseConfig) or dict.
        """
        feedback_list = []
        
        template_items = []
        if hasattr(templates_config, 'items'):
             template_items = templates_config.items()
        elif isinstance(templates_config, dict):
            template_items = templates_config.items()
        else:
            logger.warning("Feedback templates config is not a dictionary or Pydantic model.")
            for issue in issues:
                 feedback_list.append({
                    "message": f"Issue detected with {issue.get('joint', 'unknown joint')}: {issue.get('issue_type', 'general issue')}. Actual: {issue.get('actual', 0):.1f}, Expected: {issue.get('expected', {})}.",
                    "severity": issue.get("severity", FeedbackSeverity.LOW.value),
                    "type": FeedbackType.FORM.value,
                    "details": f"Phase: {phase}, Deviation: {issue.get('deviation', 0):.1f}"
                })
            return feedback_list

        for issue in issues:
            matched_template_key = None
            if not matched_template_key and issue.get("issue_type"):
                for key, template_model in template_items:
                    if key == f"{issue.get('joint')}_{issue.get('issue_type')}":
                        matched_template_key = key
                        break
                if not matched_template_key:
                    for key, template_model in template_items:
                        if key == issue.get("issue_type"):
                            matched_template_key = key
                            break


            if matched_template_key:
                template_model = templates_config.get(matched_template_key)
                if template_model:
                    message = getattr(template_model, 'message', "Template message missing")
                    severity = getattr(template_model, 'severity', FeedbackSeverity.LOW.value)
                    feedback_type = getattr(template_model, 'type', FeedbackType.FORM.value)
                    details = getattr(template_model, 'details', None)
                    
                    feedback_list.append({
                        "message": message.format(joint=issue.get('joint'), actual=issue.get('actual'), expected=issue.get('expected')),
                        "severity": severity,
                        "type": feedback_type,
                        "details": details,
                        "raw_issue": issue
                    })
            else:
                feedback_list.append({
                    "message": f"Issue with {issue.get('joint', 'N/A')}: {issue.get('issue_type', 'general issue')}. Actual: {issue.get('actual', 0):.1f}, Expected: {issue.get('expected', {})}.",
                    "severity": issue.get("severity", FeedbackSeverity.LOW.value),
                    "type": FeedbackType.FORM.value,
                    "details": f"Phase: {phase}, Deviation: {issue.get('deviation', 0):.1f}"
                })
        return feedback_list
    
    async def create_feedback_items_in_db(
        self,
        form_check_id: UUID,
        feedback_data_list: List[Dict[str, Any]]
    ) -> List[FeedbackItem]:
        """
        Create FeedbackItem records in the database.
        
        Args:
            form_check_id (UUID): The ID of the FormCheck this feedback belongs to.
            feedback_data_list (List[Dict[str, Any]]): List of feedback data dictionaries.
            
        Returns:
            List[FeedbackItem]: List of created FeedbackItem objects.
        """
        created_items: List[FeedbackItem] = []
        if not feedback_data_list:
            return created_items

        for feedback_data in feedback_data_list:
            severity_value = feedback_data.get("severity")
            type_value = feedback_data.get("type")

            try:
                severity_enum = FeedbackSeverity(severity_value) if isinstance(severity_value, str) else FeedbackSeverity.INFO
            except ValueError:
                logger.warning(f"Invalid severity value: {severity_value}, defaulting to INFO.")
                severity_enum = FeedbackSeverity.INFO
            
            try:
                type_enum = FeedbackType(type_value) if isinstance(type_value, str) else FeedbackType.GENERAL
            except ValueError:
                logger.warning(f"Invalid feedback type value: {type_value}, defaulting to GENERAL.")
                type_enum = FeedbackType.GENERAL

            db_item = FeedbackItem(
                form_check_id=form_check_id,
                message=feedback_data.get("feedback_text", "N/A"),
                type=feedback_data.get("type"), 
                severity=feedback_data.get("severity"), 
                timestamp=feedback_data.get("timestamp"),
                
                details_payload=feedback_data.get("details_payload"),
                issue_specific_timestamp=feedback_data.get("timestamp_in_video"), 
                rep_index=feedback_data.get("rep_index"),
                movement_phase=feedback_data.get("movement_phase"),
                joint_name=feedback_data.get("joint_name")
            )
            self.db.add(db_item)
            created_items.append(db_item)
        
        try:
            await self.db.flush()
            for item in created_items:
                await self.db.refresh(item)
        except Exception as e:
            logger.error(f"Error creating feedback items in DB: {str(e)}")
            await self.db.rollback()
            return []
            
        return created_items

    def _get_keypoint_coords_by_name(
        self,
        keypoint_name: str,
        raw_landmarks_for_frame: List[Dict[str, Any]],
        # landmark_name_map: List[str] = POSE_LANDMARK_NAMES # This map is not directly used for lookup in the list of dicts
    ) -> Optional[Tuple[float, float]]:
        """
        Retrieves (x, y) coordinates for a named keypoint from a list of raw landmarks.
        The lookup is case-insensitive for keypoint_name against the 'name' in raw_landmarks_for_frame.
        """
        if not raw_landmarks_for_frame:
            return None
        
        search_keypoint_name_lower = keypoint_name.lower()

        for landmark_data in raw_landmarks_for_frame:
            if isinstance(landmark_data, dict) and "name" in landmark_data and "x" in landmark_data and "y" in landmark_data:
                current_landmark_name_lower = str(landmark_data["name"]).lower()
                if current_landmark_name_lower == search_keypoint_name_lower:
                    # Add confidence check here if needed, e.g.
                    # if landmark_data.get("confidence", 0.0) < MIN_CONFIDENCE_THRESHOLD:
                    #     logger.debug(f"Keypoint '{keypoint_name}' found but below confidence threshold.")
                    #     return None
                    return landmark_data["x"], landmark_data["y"]
            else:
                logger.debug(f"Skipping malformed landmark data entry: {landmark_data}")

        logger.warning(f"Keypoint name '{keypoint_name}' not found in provided raw_landmarks_for_frame.")
        return None

from fastapi import Depends
try:
    from app.core.deps import get_async_exercise_config_service
    from app.core.deps import get_async_form_check_service
except ImportError:
    logger.warning("get_async_exercise_config_service or get_async_form_check_service not found in app.core.deps, using placeholder(s). Ensure they are registered in api/deps.py.")
    # Placeholder for get_async_exercise_config_service if it wasn't imported
    if 'get_async_exercise_config_service' not in locals():
        async def get_async_exercise_config_service_placeholder():
            raise NotImplementedError("get_async_exercise_config_service provider not found.")
        get_async_exercise_config_service = get_async_exercise_config_service_placeholder
    # Placeholder for get_async_form_check_service if it wasn't imported
    if 'get_async_form_check_service' not in locals():
        async def get_async_form_check_service_placeholder():
            raise NotImplementedError("get_async_form_check_service provider not found.")
        get_async_form_check_service = get_async_form_check_service_placeholder

async def get_async_dynamic_form_analysis_service(
    # db: AsyncSession = Depends(get_async_db), # Original problematic dependency
    # settings: Settings = Depends(get_settings), # Original problematic dependency
    exercise_config_service: ExerciseConfigService = Depends(get_async_exercise_config_service),
    form_check_service: FormCheckService = Depends(get_async_form_check_service)
) -> DynamicFormAnalysisService:
    """Get dynamic form analysis service instance asynchronously."""
    from app.core.deps import get_async_db, get_settings # RE-ADDING LOCAL IMPORTS
    from sqlalchemy.ext.asyncio import AsyncSession 
    from fastapi import Depends 
    
    db: AsyncSession = Depends(get_async_db)
    settings: Settings = Depends(get_settings)
    
    return DynamicFormAnalysisService(
        db=db, 
        settings=settings, 
        exercise_config_service=exercise_config_service, 
        form_check_service=form_check_service
    )

# Placeholder for dependent service getters if they were previously in this file
# and need to be defined/imported for get_async_dynamic_form_analysis_service
# e.g.
# async def get_async_exercise_config_service(): ...
# async def get_async_form_check_service(): ... 