"""
Dynamic form analysis service module.

This service uses the database-backed exercise configurations to analyze form.
It replaces the hardcoded rule-based analysis with a dynamic rules engine.
"""
import logging
import json
from typing import Dict, List, Any, Optional, Tuple, TypedDict, Union
from uuid import UUID
import math # ADDED for posture calculations

from sqlalchemy.ext.asyncio import AsyncSession
from app.core.config import Settings

from app.services.exercise_config_service import ExerciseConfigService
from app.services.form_check_service import FormCheckService
from app.models.exercise_config import ExerciseConfig, MovementPhaseTrigger, Condition
from app.models.form_check import FormCheck, FeedbackItem
from app.models.video import Video
from app.models.enums import FeedbackType, FeedbackSeverity
from app.core.exceptions import ValidationError, NotFoundException, ServerErrorException
from app.constants.angles import POSE_LANDMARK_NAMES # ADDED for posture rule keypoint name mapping

logger = logging.getLogger(__name__)

# Define a structure for the issues that will be generated by rule evaluators
class StructuredIssue(TypedDict, total=False): # total=False allows for optional keys
    rule_type: str # e.g., "joint_angle", "rom", "posture", "symmetry"
    joint_name: Optional[str]
    compared_to_joint: Optional[str] # For symmetry
    details: str # Human-readable description of the issue
    severity: str # e.g., "low", "medium", "high" (can map to FeedbackSeverity enum)
    phase: str # Movement phase in which issue occurred
    rep_index: int # 0-indexed
    frame_index_in_rep: Optional[int] # Optional: frame number within the current repetition
    timestamp_in_video: Optional[float] # Optional: actual video timestamp
    # Specific data related to the issue, e.g.:
    current_value: Optional[float]
    expected_value: Optional[Any] # Could be a single value, a range [min, max], or a dict
    deviation: Optional[float]

class DynamicFormAnalysisService:
    """
    Service for analyzing exercise form using dynamic configurations.
    
    This service replaces hardcoded form analysis with dynamic database-backed rules.
    """
    
    def __init__(self, db: AsyncSession, settings: Settings, exercise_config_service: ExerciseConfigService, form_check_service: FormCheckService):
        self.db = db
        self.settings = settings
        self.exercise_config_service = exercise_config_service
        self.form_check_service = form_check_service

    async def _get_exercise_config_model_async(self, exercise_template_id: UUID) -> Optional[ExerciseConfig]:
        """
        Get the active exercise configuration model for an exercise template.
        """
        config_model = await self.exercise_config_service.get_active_config_for_exercise_async(exercise_id=exercise_template_id)
        return config_model
    
    async def segment_repetitions(
        self, 
        angle_data_sequence: List[Dict[str, Any]], # Expects each dict to have 'frame_num' and 'angles'
        config: ExerciseConfig
    ) -> List[List[Dict[str, Any]]]:
        """
        Segments a sequence of angle data into repetitions based on movement phase transitions
        defined in the ExerciseConfig.
        Each repetition is a list of angle data frames (dictionaries).
        """
        logger.info(f"Attempting to segment {len(angle_data_sequence)} frames into repetitions using config: {config.name}")
        
        if not angle_data_sequence:
            logger.warning("Angle data sequence is empty. No repetitions to segment.")
            return []
        if not config or not config.movement_phases or not isinstance(config.movement_phases, dict):
            logger.warning("Insufficient or invalid config for segmentation: missing or malformed movement_phases.")
            return []

        # Ensure movement_phases has a defined start_phase_name, typically the first key or a marked one.
        # And an end_phase_name that signifies a rep completion or loop back to start.
        # For simplicity, let's assume the config has a 'start_phase_name' field and an 'end_phase_action'
        # on the phase that completes a rep (e.g., 'loop_to_start_phase').
        # These would ideally be part of the ExerciseConfig schema for clarity.
        # For now, we'll infer a plausible start (e.g., first phase listed or a phase named 'start').
        
        # Try to find a phase explicitly named 'start' or 'start_phase'
        # Fallback to the first phase defined if no explicit start is found.
        potential_start_phases = [name for name in config.movement_phases.keys() if "start" in name.lower()]
        if potential_start_phases:
            current_phase_name = potential_start_phases[0]
        elif config.movement_phases:
            current_phase_name = list(config.movement_phases.keys())[0]
        else:
            logger.error("No movement phases defined in config. Cannot segment.")
            return []

        logger.info(f"Initial segmentation phase: {current_phase_name}")

        repetitions: List[List[Dict[str, Any]]] = []
        current_rep_frames: List[Dict[str, Any]] = []
        
        # Default to first phase in config if 'start_phase_name' is not explicit in config schema
        # This is a simplification; a robust config should define the entry point phase.
        # For now, assume a phase like 'start_phase' or the first one defined is the entry.
        
        # Helper to evaluate triggers
        def _check_trigger(frame_angles: Dict[str, float], trigger_condition: Dict[str, Any]) -> bool:
            joint_name = trigger_condition.get("joint")
            condition_type = trigger_condition.get("condition") # e.g., "angle"
            target_value = trigger_condition.get("value")
            comparator = trigger_condition.get("comparator") # e.g., "<", ">", "peaks"

            if not all([joint_name, condition_type, target_value, comparator]):
                logger.warning(f"Malformed trigger condition: {trigger_condition}. Skipping.")
                return False

            current_angle = frame_angles.get(joint_name)
            if current_angle is None:
                # logger.debug(f"Joint {joint_name} not in frame angles for trigger check. Frame: {frame_angles}")
                return False

            if condition_type == "angle":
                if comparator == "<": return current_angle < target_value
                if comparator == "<=": return current_angle <= target_value
                if comparator == ">": return current_angle > target_value
                if comparator == ">=": return current_angle >= target_value
                if comparator == "==": return abs(current_angle - target_value) < 1e-5 # float equality
                # Add more comparators/conditions like 'velocity_peaks', 'crosses_threshold' if needed
            # else:
                # logger.warning(f"Unsupported trigger condition type: {condition_type}")
            return False

        for frame_data in angle_data_sequence:
            # Ensure frame_data contains 'angles'; if not, it might be an empty frame from previous steps
            if not frame_data or "angles" not in frame_data or frame_data["angles"] is None:
                if current_rep_frames: # If we've started collecting a rep
                    current_rep_frames.append(frame_data) # Add the problematic frame
                continue # Skip phase transition logic for this frame, but keep it if rep started

            # Add frame to current rep FIRST.
            current_rep_frames.append(frame_data)

            frame_angles = frame_data["angles"]
            phase_changed_this_frame = False

            current_phase_config = config.movement_phases.get(current_phase_name)
            if not current_phase_config or not isinstance(current_phase_config, dict):
                logger.error(f"Config for phase '{current_phase_name}' is missing or malformed. Halting segmentation.")
                break 
            
            phase_triggers = current_phase_config.get("triggers", {})
            
            # Priority: Check for triggers that end the current rep and start a new one
            # This assumes a specific trigger key like 'end_rep_and_loop_to_phase' or similar
            # in the phase_triggers that signifies completion of a full rep.
            # Example: 'ascent_phase' triggers might point back to 'start_phase', indicating rep end.
            
            next_phase_for_new_rep = None
            if "next_rep_starts_phase" in phase_triggers: # Custom key to indicate rep boundary
                for trigger_condition in phase_triggers["next_rep_starts_phase"].get("conditions", []):
                    if _check_trigger(frame_angles, trigger_condition):
                        next_phase_for_new_rep = phase_triggers["next_rep_starts_phase"].get("target_phase")
                        break
            
            if next_phase_for_new_rep:
                if current_rep_frames: # If we have frames for the current rep
                    repetitions.append(list(current_rep_frames)) # Save completed rep
                    logger.info(f"Completed Rep {len(repetitions)} ending with phase '{current_phase_name}' ({len(current_rep_frames)} frames). Transitioning to '{next_phase_for_new_rep}' for new rep.")
                    current_rep_frames.clear() # Start a new rep
                current_phase_name = next_phase_for_new_rep
                current_rep_frames.append(frame_data) # Start new rep with current frame
                phase_changed_this_frame = True

                # If this frame_data was the *last* in the overall sequence,
                # then the current_rep_frames (which now holds only frame_data)
                # should not be added as a new rep after the loop.
                if frame_data is angle_data_sequence[-1]: 
                    logger.debug(f"Transition frame {frame_data.get('frame_num')} was the last in sequence. Clearing current_rep_frames to prevent final append.")
                    current_rep_frames.clear()
            else:
                # Check for normal "next" phase transitions
                if "next" in phase_triggers:
                    for trigger_condition in phase_triggers["next"].get("conditions", []):
                        if _check_trigger(frame_angles, trigger_condition):
                            new_phase_name = phase_triggers["next"].get("target_phase")
                            if new_phase_name and new_phase_name in config.movement_phases:
                                logger.debug(f"Frame {frame_data.get('frame_num', 'N/A')}: Phase transition from '{current_phase_name}' to '{new_phase_name}'.")
                                current_phase_name = new_phase_name
                                phase_changed_this_frame = True
                                break # Process only one transition per frame
                            else:
                                logger.warning(f"Invalid target phase '{new_phase_name}' in triggers for '{current_phase_name}'.")
                
                # Optionally, check for "previous" phase transitions if phase_changed_this_frame is still False
                # This logic might be complex if forward and backward transitions can occur simultaneously
                # For simplicity, prioritizing forward ("next") transitions first.
                if not phase_changed_this_frame and "previous" in phase_triggers:
                    for trigger_condition in phase_triggers["previous"].get("conditions", []):
                        if _check_trigger(frame_angles, trigger_condition):
                            prev_phase_name = phase_triggers["previous"].get("target_phase")
                            if prev_phase_name and prev_phase_name in config.movement_phases:
                                logger.debug(f"Frame {frame_data.get('frame_num', 'N/A')}: Phase transition (backwards) from '{current_phase_name}' to '{prev_phase_name}'.")
                                current_phase_name = prev_phase_name
                                phase_changed_this_frame = True
                                break
                            else:
                                logger.warning(f"Invalid target phase '{prev_phase_name}' in triggers for '{current_phase_name}'.")

        # After loop, add any remaining frames as the last (potentially incomplete) rep
        if current_rep_frames:
            repetitions.append(list(current_rep_frames))
            logger.info(f"Added final (potentially incomplete) Rep {len(repetitions)} with {len(current_rep_frames)} frames, ending in phase '{current_phase_name}'.")

        if not repetitions:
            logger.warning(f"Segmentation did not yield any repetitions for config '{config.name}'.")
        else:
            logger.info(f"Successfully segmented into {len(repetitions)} repetitions.")
        
        return repetitions

    # --- BEGIN MODULAR RULE EVALUATOR STUBS ---
    # These will be implemented in detail in subsequent steps.

    async def _apply_joint_angle_rules(
        self,
        frame_angles: Dict[str, float],
        rep_index: int,
        current_phase_name: str,
        frame_timestamp: Optional[float], # Added timestamp
        frame_index_in_rep: int, # Added frame index
        config: ExerciseConfig
    ) -> List[StructuredIssue]:
        logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep} ({current_phase_name}): Applying joint angle rules using ExerciseConfig ID {config.id}.")
        issues: List[StructuredIssue] = []

        if not config.joint_angle_rules or not isinstance(config.joint_angle_rules, dict):
            logger.warning(f"Rep {rep_index}, Frame {frame_index_in_rep}: No joint_angle_rules found in config or not a dict.")
            return issues

        rules_for_phases = config.joint_angle_rules.get("phases")
        if not rules_for_phases or not isinstance(rules_for_phases, dict):
            logger.warning(f"Rep {rep_index}, Frame {frame_index_in_rep}: 'phases' key missing or not a dict in joint_angle_rules.")
            return issues

        # Get rules for the current phase, fallback to "default" if current phase not found
        phase_specific_rules_data = rules_for_phases.get(current_phase_name)
        if not phase_specific_rules_data:
            phase_specific_rules_data = rules_for_phases.get("default")
        
        if not phase_specific_rules_data or not isinstance(phase_specific_rules_data, dict):
            logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep}: No specific or default angle rules found for phase '{current_phase_name}'.")
            return issues

        angle_rules_for_current_phase = phase_specific_rules_data.get("angles")
        if not angle_rules_for_current_phase or not isinstance(angle_rules_for_current_phase, dict):
            logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep}: No 'angles' defined in rules for phase '{current_phase_name}'.")
            return issues

        for joint_name, joint_rule_data in angle_rules_for_current_phase.items():
            if not isinstance(joint_rule_data, dict):
                logger.warning(f"Rep {rep_index}, Frame {frame_index_in_rep}: Rule data for joint '{joint_name}' in phase '{current_phase_name}' is not a dict. Skipping.")
                continue

            if joint_name not in frame_angles:
                # This joint has a rule but is not present in the current frame's detected angles.
                # Optionally log or create an issue if a normally expected joint is missing.
                # For now, we skip if the angle isn't available to check.
                logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep}: Joint '{joint_name}' has a rule but not found in frame_angles. Skipping rule for this joint.")
                continue

            actual_angle = frame_angles[joint_name]

            min_angle = joint_rule_data.get("min_angle")
            max_angle = joint_rule_data.get("max_angle")
            ideal_angle = joint_rule_data.get("ideal_angle")
            # Use tolerance from rule, default if not present (though schema makes it required with default)
            tolerance = joint_rule_data.get("tolerance", 15.0) 

            current_deviation = 0.0
            issue_description = ""
            expected_values_dict: Dict[str, Any] = {}
            violation_type: Optional[str] = None


            if min_angle is not None and actual_angle < min_angle:
                current_deviation = min_angle - actual_angle
                violation_type = "below_min"
                issue_description = f"{joint_name} angle ({actual_angle:.1f}°) is below minimum ({min_angle:.1f}°)."
                expected_values_dict = {"min_angle": min_angle, "max_angle": max_angle, "ideal_angle": ideal_angle, "tolerance": tolerance}
            elif max_angle is not None and actual_angle > max_angle:
                current_deviation = actual_angle - max_angle
                violation_type = "above_max"
                issue_description = f"{joint_name} angle ({actual_angle:.1f}°) is above maximum ({max_angle:.1f}°)."
                expected_values_dict = {"min_angle": min_angle, "max_angle": max_angle, "ideal_angle": ideal_angle, "tolerance": tolerance}
            elif ideal_angle is not None and tolerance is not None:
                lower_bound_ideal = ideal_angle - tolerance
                upper_bound_ideal = ideal_angle + tolerance
                if actual_angle < lower_bound_ideal:
                    current_deviation = lower_bound_ideal - actual_angle
                    violation_type = "below_ideal_range"
                    issue_description = f"{joint_name} angle ({actual_angle:.1f}°) is below ideal range ({lower_bound_ideal:.1f}° - {upper_bound_ideal:.1f}°)."
                    expected_values_dict = {"ideal_angle": ideal_angle, "tolerance": tolerance, "ideal_range": [lower_bound_ideal, upper_bound_ideal]}
                elif actual_angle > upper_bound_ideal:
                    current_deviation = actual_angle - upper_bound_ideal
                    violation_type = "above_ideal_range"
                    issue_description = f"{joint_name} angle ({actual_angle:.1f}°) is above ideal range ({lower_bound_ideal:.1f}° - {upper_bound_ideal:.1f}°)."
                    expected_values_dict = {"ideal_angle": ideal_angle, "tolerance": tolerance, "ideal_range": [lower_bound_ideal, upper_bound_ideal]}
            
            if violation_type and current_deviation > 0: # Ensure there's an actual deviation
                severity = self.calculate_severity(current_deviation, tolerance) # Use rule's tolerance for severity calculation

                issues.append({
                    "rule_type": "joint_angle",
                    "joint_name": joint_name,
                    "details": f"{issue_description} During {current_phase_name} phase.",
                    "severity": severity,
                    "phase": current_phase_name,
                    "rep_index": rep_index,
                    "frame_index_in_rep": frame_index_in_rep,
                    "timestamp_in_video": frame_timestamp,
                    "current_value": actual_angle,
                    "expected_value": expected_values_dict, # Store the relevant rule parameters
                    "deviation": current_deviation,
                    "violation_type": violation_type # Specific type of angle violation
                })
        
        if issues:
            logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep} ({current_phase_name}): Found {len(issues)} joint angle issues.")
        return issues

    async def _apply_rom_rules(
        self,
        rep_angle_data: List[Dict[str, Any]], # Full data for the current repetition
        rep_index: int,
        config: ExerciseConfig
    ) -> List[StructuredIssue]:
        logger.debug(f"Rep {rep_index}: Applying ROM rules using ExerciseConfig ID {config.id}.")
        issues: List[StructuredIssue] = []

        if not config.rom_rules or not isinstance(config.rom_rules, list):
            logger.debug(f"Rep {rep_index}: No ROM rules defined in config or not a list. Skipping ROM checks.")
            return issues

        if not rep_angle_data:
            logger.warning(f"Rep {rep_index}: Repetition angle data is empty. Cannot apply ROM rules.")
            return issues

        for rom_rule_data in config.rom_rules:
            if not isinstance(rom_rule_data, dict): # Ensure rule is a dict (parsed from JSON)
                logger.warning(f"Rep {rep_index}: Encountered a ROM rule that is not a dictionary. Skipping rule: {rom_rule_data}")
                continue

            joint_name = rom_rule_data.get("joint_name")
            min_angle_overall_rule = rom_rule_data.get("min_angle_overall")
            max_angle_overall_rule = rom_rule_data.get("max_angle_overall")
            target_rom_rule = rom_rule_data.get("target_rom")
            tolerance_degrees_rule = rom_rule_data.get("tolerance_degrees", 10.0) # Default from schema

            if not joint_name or min_angle_overall_rule is None or max_angle_overall_rule is None:
                logger.warning(f"Rep {rep_index}: ROM rule for config {config.id} is missing joint_name, min_angle_overall, or max_angle_overall. Skipping rule: {rom_rule_data}")
                continue

            observed_min_angle_for_joint = float('inf')
            observed_max_angle_for_joint = float('-inf')
            joint_angles_for_rep: List[float] = []
            # Store first and last valid timestamp for potential use in StructuredIssue
            first_valid_timestamp: Optional[float] = None
            last_valid_timestamp: Optional[float] = None


            for frame_data in rep_angle_data:
                if frame_data and isinstance(frame_data.get("angles"), dict):
                    angle_value = frame_data["angles"].get(joint_name)
                    if angle_value is not None and isinstance(angle_value, (int, float)):
                        joint_angles_for_rep.append(angle_value)
                        observed_min_angle_for_joint = min(observed_min_angle_for_joint, angle_value)
                        observed_max_angle_for_joint = max(observed_max_angle_for_joint, angle_value)
                        
                        current_timestamp = frame_data.get("timestamp")
                        if current_timestamp is not None:
                            if first_valid_timestamp is None:
                                first_valid_timestamp = current_timestamp
                            last_valid_timestamp = current_timestamp
            
            if not joint_angles_for_rep: # No valid angles found for this joint in the rep
                logger.debug(f"Rep {rep_index}: No angle data found for joint '{joint_name}' in this repetition. Skipping ROM check for this joint.")
                continue

            # Check if observed min/max meet overall requirements
            violation_type: Optional[str] = None
            current_deviation = 0.0
            issue_description = ""
            expected_values_dict: Dict[str, Any] = {
                "rule_min_overall": min_angle_overall_rule,
                "rule_max_overall": max_angle_overall_rule,
                "target_rom": target_rom_rule,
                "tolerance_degrees": tolerance_degrees_rule
            }
            observed_rom_value = observed_max_angle_for_joint - observed_min_angle_for_joint

            if observed_min_angle_for_joint > min_angle_overall_rule:
                violation_type = "failed_to_reach_min_rom"
                current_deviation = observed_min_angle_for_joint - min_angle_overall_rule
                issue_description = f"{joint_name} did not reach required minimum angle. Observed min: {observed_min_angle_for_joint:.1f}°, Expected min: {min_angle_overall_rule:.1f}°."
            elif observed_max_angle_for_joint < max_angle_overall_rule:
                violation_type = "failed_to_reach_max_rom"
                current_deviation = max_angle_overall_rule - observed_max_angle_for_joint
                issue_description = f"{joint_name} did not reach required maximum angle. Observed max: {observed_max_angle_for_joint:.1f}°, Expected max: {max_angle_overall_rule:.1f}°."

            # If target ROM is specified, check that too, but only if no min/max violation occurred first.
            if not violation_type and target_rom_rule is not None:
                if abs(observed_rom_value - target_rom_rule) > tolerance_degrees_rule:
                    violation_type = "deviation_from_target_rom"
                    current_deviation = abs(observed_rom_value - target_rom_rule)
                    # Distinguish between too much or too little ROM if possible
                    if observed_rom_value > target_rom_rule:
                         issue_description = f"{joint_name} ROM ({observed_rom_value:.1f}°) exceeded target ROM ({target_rom_rule:.1f}°) by {current_deviation:.1f}° (more than {tolerance_degrees_rule:.1f}° tolerance)."
                    else:
                         issue_description = f"{joint_name} ROM ({observed_rom_value:.1f}°) was less than target ROM ({target_rom_rule:.1f}°) by {current_deviation:.1f}° (more than {tolerance_degrees_rule:.1f}° tolerance)."
            
            if violation_type:
                # Use tolerance_degrees_rule from the ROM rule for severity calculation,
                # as it's specific to ROM deviation rather than general angle tolerance.
                severity = self.calculate_severity(current_deviation, tolerance_degrees_rule)
                
                # Use a representative timestamp, e.g., midpoint of the rep, or None
                # For simplicity, can use first_valid_timestamp if available, or None.
                # A more sophisticated approach might find the exact frame of min/max violation.
                representative_timestamp = first_valid_timestamp 

                issues.append({
                    "rule_type": "rom",
                    "joint_name": joint_name,
                    "details": issue_description,
                    "severity": severity,
                    "phase": "full_repetition", # ROM issues are typically for the whole rep
                    "rep_index": rep_index,
                    "frame_index_in_rep": None, # ROM is rep-level
                    "timestamp_in_video": representative_timestamp, 
                    "current_value": {"observed_min": observed_min_angle_for_joint, "observed_max": observed_max_angle_for_joint, "observed_rom": observed_rom_value},
                    "expected_value": expected_values_dict,
                    "deviation": current_deviation,
                    "violation_type": violation_type
                })
        
        if issues:
            logger.debug(f"Rep {rep_index}: Found {len(issues)} ROM issues.")
        return issues

    async def _apply_posture_rules(
        self,
        frame_data: Dict[str, Any], # CHANGED: Takes full frame_data now
        rep_index: int,
        current_phase_name: str,
        frame_timestamp: Optional[float],
        frame_index_in_rep: int,
        config: ExerciseConfig
    ) -> List[StructuredIssue]:
        logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep} ({current_phase_name}): Applying posture rules using ExerciseConfig ID {config.id}.")
        issues: List[StructuredIssue] = []

        if not config.posture_rules or not isinstance(config.posture_rules, list):
            logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep}: No posture_rules defined in config or not a list. Skipping posture checks.")
            return issues

        raw_landmarks_for_frame = frame_data.get('raw_landmarks') # Expect this key in frame_data
        if not raw_landmarks_for_frame or not isinstance(raw_landmarks_for_frame, list):
            logger.warning(f"Rep {rep_index}, Frame {frame_index_in_rep}: 'raw_landmarks' missing or not a list in frame_data. Cannot apply posture rules.")
            return issues

        for posture_rule_data in config.posture_rules:
            if not isinstance(posture_rule_data, dict):
                logger.warning(f"Rep {rep_index}, Frame {frame_index_in_rep}: Encountered a posture rule that is not a dictionary. Skipping: {posture_rule_data}")
                continue

            rule_name = posture_rule_data.get("rule_name", "Unnamed Posture Rule")
            applicable_phases = posture_rule_data.get("applicable_phases")
            conditions = posture_rule_data.get("conditions") # Expected to be List[Dict]

            if applicable_phases and isinstance(applicable_phases, list) and current_phase_name not in applicable_phases:
                continue # Rule not for this phase

            if not conditions or not isinstance(conditions, list):
                logger.warning(f"Rep {rep_index}, Frame {frame_index_in_rep}: Posture rule '{rule_name}' has no conditions or conditions not a list. Skipping.")
                continue

            for condition_data in conditions:
                if not isinstance(condition_data, dict):
                    logger.warning(f"Rep {rep_index}, Frame {frame_index_in_rep}: Posture rule '{rule_name}' has a condition that is not a dictionary. Skipping condition: {condition_data}")
                    continue

                condition_type = condition_data.get("condition_type")
                
                # --- Handle 'vector_angle_from_vertical' condition type ---
                if condition_type == "vector_angle_from_vertical":
                    keypoints_for_vector = condition_data.get("keypoints_for_vector")
                    expected_angle_deg_config = condition_data.get("expected_angle_degrees")
                    max_deviation_deg_config = condition_data.get("max_deviation_degrees")

                    if not (isinstance(keypoints_for_vector, list) and len(keypoints_for_vector) == 2 and
                            all(isinstance(kp, str) for kp in keypoints_for_vector) and
                            isinstance(expected_angle_deg_config, (int, float)) and
                            isinstance(max_deviation_deg_config, (int, float))):
                        logger.warning(f"Rep {rep_index}, Frame {frame_index_in_rep}: Posture rule '{rule_name}', condition '{condition_type}' has malformed parameters. Skipping condition. Data: {condition_data}")
                        continue

                    kp1_name, kp2_name = keypoints_for_vector[0], keypoints_for_vector[1]
                    
                    coords1 = self._get_keypoint_coords_by_name(kp1_name, raw_landmarks_for_frame)
                    coords2 = self._get_keypoint_coords_by_name(kp2_name, raw_landmarks_for_frame)

                    if not coords1 or not coords2:
                        logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep}: Could not get coordinates for keypoints '{kp1_name}' or '{kp2_name}' for posture rule '{rule_name}'. Skipping condition.")
                        continue
                    
                    x1, y1 = coords1
                    x2, y2 = coords2

                    dx = x2 - x1
                    dy = y2 - y1 # Positive dy means p2 is "below" p1 in image coordinates

                    if dx == 0 and dy == 0: # Points are the same
                        logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep}: Keypoints '{kp1_name}' and '{kp2_name}' for posture rule '{rule_name}' are at the same position. Skipping vector calculation.")
                        continue

                    # Angle of vector (p1->p2) with positive Y-axis (pointing downwards).
                    # Result is in radians, range -pi to pi.
                    # 0 rad: vector points straight down.
                    # pi/2 rad (90 deg): vector points to the right.
                    # -pi/2 rad (-90 deg): vector points to the left.
                    # pi or -pi rad (180 deg): vector points straight up.
                    observed_angle_rad = math.atan2(dx, dy)
                    observed_angle_deg = math.degrees(observed_angle_rad)

                    # Calculate angular difference, handling wrapping.
                    # diff = 180 - abs(abs(a1 - a2) - 180)
                    angular_diff = 180.0 - abs(abs(observed_angle_deg - expected_angle_deg_config) - 180.0)

                    if angular_diff > max_deviation_deg_config:
                        severity_str = posture_rule_data.get("severity", FeedbackSeverity.MEDIUM.value)
                        calculated_severity = self.calculate_severity(angular_diff, max_deviation_deg_config) # Use condition's max_dev for severity threshold

                        issue_description = (
                            f"Posture issue: '{rule_name}'. Vector '{kp1_name}' to '{kp2_name}' "
                            f"angle ({observed_angle_deg:.1f}°) deviates from expected ({expected_angle_deg_config:.1f}°) "
                            f"by {angular_diff:.1f}°, exceeding max deviation of {max_deviation_deg_config:.1f}°."
                        )
                        issues.append({
                            "rule_type": "posture",
                            "joint_name": None, # Posture might involve multiple points, not a single "joint"
                            "details": issue_description,
                            "severity": calculated_severity,
                            "phase": current_phase_name,
                            "rep_index": rep_index,
                            "frame_index_in_rep": frame_index_in_rep,
                            "timestamp_in_video": frame_timestamp,
                            "current_value": {"observed_vector_angle_from_vertical_degrees": observed_angle_deg},
                            "expected_value": {
                                "vector_defined_by": keypoints_for_vector,
                                "expected_angle_from_vertical_degrees": expected_angle_deg_config,
                                "max_deviation_degrees": max_deviation_deg_config
                            },
                            "deviation": angular_diff,
                            "violation_type": f"{rule_name}_deviation" # Specific posture violation
                        })
                # Add other condition_types for posture here (e.g., distance between keypoints, planarity)
                else:
                    logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep}: Posture rule '{rule_name}' has unknown condition_type '{condition_type}'. Skipping condition.")

        if issues:
            logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep} ({current_phase_name}): Found {len(issues)} posture issues.")
        return issues

    async def _apply_symmetry_rules(
        self,
        frame_angles: Dict[str, float],
        rep_index: int,
        current_phase_name: str,
        frame_timestamp: Optional[float],
        frame_index_in_rep: int,
        config: ExerciseConfig
    ) -> List[StructuredIssue]:
        logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep} ({current_phase_name}): Applying symmetry rules using ExerciseConfig ID {config.id}.")
        issues: List[StructuredIssue] = []

        if not config.symmetry_rules or not isinstance(config.symmetry_rules, list):
            logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep}: No symmetry_rules defined in config or not a list. Skipping symmetry checks.")
            return issues

        for symmetry_rule_data in config.symmetry_rules:
            if not isinstance(symmetry_rule_data, dict):
                logger.warning(f"Rep {rep_index}, Frame {frame_index_in_rep}: Encountered a symmetry rule that is not a dictionary. Skipping: {symmetry_rule_data}")
                continue

            joint_pair = symmetry_rule_data.get("joint_pair") # Expected: List[str, str] or Tuple[str, str]
            max_diff_degrees_config = symmetry_rule_data.get("max_difference_degrees")
            applicable_phases = symmetry_rule_data.get("applicable_phases")

            if applicable_phases and isinstance(applicable_phases, list) and current_phase_name not in applicable_phases:
                continue # Rule not for this phase

            if not (isinstance(joint_pair, (list, tuple)) and len(joint_pair) == 2 and
                    all(isinstance(jp, str) for jp in joint_pair) and
                    isinstance(max_diff_degrees_config, (int, float))):
                logger.warning(f"Rep {rep_index}, Frame {frame_index_in_rep}: Symmetry rule has malformed joint_pair or max_difference_degrees. Skipping rule. Data: {symmetry_rule_data}")
                continue
            
            joint1_name, joint2_name = joint_pair[0], joint_pair[1]

            angle1 = frame_angles.get(joint1_name)
            angle2 = frame_angles.get(joint2_name)

            if angle1 is None or angle2 is None:
                # If one angle is missing, we can't check symmetry for this pair in this frame.
                # Could log this, or create a specific type of issue if symmetry is critical.
                logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep}: Missing angle for '{joint1_name}' or '{joint2_name}' for symmetry check. Skipping pair.")
                continue
            
            abs_difference = abs(angle1 - angle2)

            if abs_difference > max_diff_degrees_config:
                severity_str = symmetry_rule_data.get("severity", FeedbackSeverity.MEDIUM.value) # Default severity if not in rule data
                # Use max_diff_degrees_config as the tolerance for severity calculation
                calculated_severity = self.calculate_severity(abs_difference, max_diff_degrees_config) 

                issue_description = (
                    f"Symmetry issue: Difference between {joint1_name} ({angle1:.1f}°) and {joint2_name} ({angle2:.1f}°) "
                    f"is {abs_difference:.1f}°, exceeding max allowed difference of {max_diff_degrees_config:.1f}°."
                )
                issues.append({
                    "rule_type": "symmetry",
                    "joint_name": joint1_name, # Primary joint for reporting, or could be a list/tuple
                    "compared_to_joint": joint2_name, # The other joint in the symmetric pair
                    "details": issue_description,
                    "severity": calculated_severity,
                    "phase": current_phase_name,
                    "rep_index": rep_index,
                    "frame_index_in_rep": frame_index_in_rep,
                    "timestamp_in_video": frame_timestamp,
                    "current_value": {"joint1_angle": angle1, "joint2_angle": angle2, "difference": abs_difference},
                    "expected_value": {"max_difference_degrees": max_diff_degrees_config},
                    "deviation": abs_difference - max_diff_degrees_config, # Positive value indicates how much it exceeded the threshold
                    "violation_type": f"asymmetry_{joint1_name}_{joint2_name}"
                })

        if issues:
            logger.debug(f"Rep {rep_index}, Frame {frame_index_in_rep} ({current_phase_name}): Found {len(issues)} symmetry issues.")
        return issues

    # --- END MODULAR RULE EVALUATOR STUBS ---

    async def evaluate_rep(
        self, 
        rep_angle_data: List[Dict[str, Any]], # List of frame data for one rep
                                             # Each frame_data dict should have 'frame_num', 'timestamp', 'angles', 'raw_landmarks'
        rep_index: int, # Added rep_index for context
        config: ExerciseConfig
    ) -> Tuple[List[StructuredIssue], float]: # MODIFIED: Returns List[StructuredIssue]
        """
        Evaluates a single repetition against the exercise configuration by orchestrating
        calls to modular rule evaluators.
        """
        logger.info(f"Evaluating Repetition {rep_index} with {len(rep_angle_data)} frames using config: {config.name}")
        all_rep_issues: List[StructuredIssue] = []

        if not rep_angle_data or not config:
            logger.warning(f"Rep {rep_index}: Insufficient data for rep evaluation: missing angle data or config.")
            return [], 0.0 # Default score 0 if no data

        # 1. Per-frame analysis: Iterate through each frame in the repetition
        for frame_idx, frame_data in enumerate(rep_angle_data): # frame_data is now the comprehensive dict
            # Ensure frame_data contains 'angles'; if not, it might be an empty frame from previous steps
            # Also, posture rules will need 'raw_landmarks' within frame_data
            if not frame_data:
                logger.warning(f"Rep {rep_index}, Frame {frame_idx}: Skipping frame due to empty frame_data.")
                continue
            
            frame_angles = frame_data.get("angles")
            if frame_angles is None: # Can be an empty dict, but not None
                logger.warning(f"Rep {rep_index}, Frame {frame_idx}: Skipping frame due to missing 'angles' in frame_data.")
                continue

            frame_timestamp = frame_data.get("timestamp") # Assuming timestamp is available per frame
            
            # 2. Detect movement phase for the current frame
            current_phase_name = self.detect_movement_phase(
                phases_config=config.movement_phases,
                joint_angles=frame_angles # detect_movement_phase uses angles
            )
            if current_phase_name == "unknown":
                logger.debug(f"Rep {rep_index}, Frame {frame_idx}: Phase could not be determined. Skipping rule checks for this frame.")
                continue
            
            logger.debug(f"Rep {rep_index}, Frame {frame_idx}: Detected phase: {current_phase_name}")

            # 3. Apply modular rule evaluators for the current frame
            all_rep_issues.extend(await self._apply_joint_angle_rules(
                frame_angles, rep_index, current_phase_name, frame_timestamp, frame_idx, config
            ))
            all_rep_issues.extend(await self._apply_posture_rules(
                frame_data, rep_index, current_phase_name, frame_timestamp, frame_idx, config # CHANGED: pass full frame_data
            ))
            all_rep_issues.extend(await self._apply_symmetry_rules(
                frame_angles, rep_index, current_phase_name, frame_timestamp, frame_idx, config
            ))

        # 4. Apply rules that evaluate the entire repetition (e.g., ROM)
        all_rep_issues.extend(await self._apply_rom_rules(
            rep_angle_data, rep_index, config
        ))
        
        # 5. Calculate score for the repetition based on aggregated issues
        # This scoring logic needs to be defined. For now, a simple placeholder.
        # Higher score is better. Start with 100 and deduct.
        current_rep_score = 100.0
        for issue in all_rep_issues:
            if issue.get("severity") == FeedbackSeverity.HIGH.value:
                current_rep_score -= 15
            elif issue.get("severity") == FeedbackSeverity.MEDIUM.value:
                current_rep_score -= 10
            elif issue.get("severity") == FeedbackSeverity.LOW.value:
                current_rep_score -= 5
        current_rep_score = max(0.0, current_rep_score) # Ensure score doesn't go below 0

        logger.info(f"Repetition {rep_index}: Evaluation complete. Found {len(all_rep_issues)} issues. Score: {current_rep_score:.2f}")
        
        # The old `generate_feedback` is now part of `analyze_form_dynamically` after collecting all issues.
        # `evaluate_rep` now returns the structured issues.
        return all_rep_issues, current_rep_score

    async def analyze_form_dynamically(
        self,
        video: Video
    ) -> FormCheck:
        """
        Analyze exercise form using dynamic configuration for a given video.
        Segments video into repetitions, evaluates each rep, aggregates feedback, and updates FormCheck.
        """
        logger.info(f"Starting dynamic form analysis for video ID: {video.id}")

        if not video.exercise_template_id:
            logger.error(f"Video {video.id} is missing exercise_template_id. Cannot perform dynamic analysis.")
            raise ValidationError("Video is missing exercise_template_id, required for dynamic analysis.")

        # Ensure both angle_data (calculated angles) and raw_pose_data (landmarks) are present
        if not video.angle_data or not isinstance(video.angle_data, list):
            logger.error(f"Video {video.id} has no angle_data or it's not a list. Cannot perform analysis.")
            raise ValidationError("Video calculated angle_data is missing or not a list.")
        
        if not video.raw_pose_data or not isinstance(video.raw_pose_data, list):
            logger.error(f"Video {video.id} has no raw_pose_data or it's not a list. Cannot perform analysis for posture rules.")
            # Depending on requirements, this could be a hard fail or allow proceeding without posture rules.
            # For now, making it a prerequisite for the enhanced analysis.
            raise ValidationError("Video raw_pose_data (landmarks) is missing or not a list.")

        # Ensure angle_data and raw_pose_data have the same length (represent the same frames)
        if len(video.angle_data) != len(video.raw_pose_data):
            logger.error(
                f"Mismatch in lengths for video {video.id}: angle_data has {len(video.angle_data)} frames, "
                f"raw_pose_data has {len(video.raw_pose_data)} frames. Cannot reconcile for analysis."
            )
            raise ValidationError("Frame count mismatch between calculated angles and raw pose data.")


        form_check = await self.form_check_service.get_or_create_form_check_for_video(video_id=video.id)
        logger.info(f"Using FormCheck ID: {form_check.id} for video ID: {video.id}")

        config = await self._get_exercise_config_model_async(video.exercise_template_id)
        
        if not config:
            logger.warning(f"No active ExerciseConfig found for exercise_template_id {video.exercise_template_id} (Video ID: {video.id}). Cannot perform analysis.")
            form_check.status = "analysis_failed"
            form_check.overall_feedback = "Analysis failed: No valid exercise configuration found."
            await self.db.commit()
            return form_check
            
        logger.info(f"Using ExerciseConfig: {config.name} (Version: {config.version}) for video ID: {video.id}")

        all_feedback_items_for_video: List[StructuredIssue] = [] # Changed from List[Dict] to List[StructuredIssue]
        total_score = 0
        num_reps = 0

        try:
            # --- Prepare enriched_frame_sequence --- 
            enriched_frame_sequence: List[Dict[str, Any]] = []
            video_fps = video.fps if video.fps and video.fps > 0 else 30.0 # Default FPS if not set

            # Assuming video.angle_data is List[Optional[Dict[str, float]]] and video.raw_pose_data is List[Optional[List[Dict[str,Any]]]]
            # Each element in these lists corresponds to a frame.
            for frame_idx, (angles_for_frame, landmarks_for_frame) in enumerate(zip(video.angle_data, video.raw_pose_data)):
                # angles_for_frame can be None if smoothing/calculation failed for it
                # landmarks_for_frame can be None if pose detection failed for it
                
                # Recheck if angle_data elements are dicts after smoothing (they should be, or None)
                # Smoothed angles (video.angle_data) might already contain 'frame_num' and 'timestamp'
                # If so, use them. Otherwise, calculate.
                frame_num_from_angles = None
                timestamp_from_angles = None
                actual_angles_dict = None

                if isinstance(angles_for_frame, dict):
                    # Check if it's the structure from smoothing: {'frame_num': X, 'timestamp': Y, 'angles': {...}}
                    # Or just the angles dict: {'LEFT_KNEE': 120.0, ...}
                    if "angles" in angles_for_frame and ("frame_num" in angles_for_frame or "timestamp" in angles_for_frame):
                        actual_angles_dict = angles_for_frame.get("angles") # This could be None if only metadata was kept
                        frame_num_from_angles = angles_for_frame.get("frame_num")
                        timestamp_from_angles = angles_for_frame.get("timestamp")
                    else:
                        # Assumed to be just the angles dict
                        actual_angles_dict = angles_for_frame
                elif angles_for_frame is None:
                    actual_angles_dict = None # Explicitly set to None
                else:
                    logger.warning(f"Video {video.id}, Frame {frame_idx}: Unexpected format for angles_for_frame. Type: {type(angles_for_frame)}. Skipping.")
                    actual_angles_dict = None # Treat as if no angles
                
                # Ensure actual_angles_dict is either a dict of angles or None
                if not isinstance(actual_angles_dict, dict) and actual_angles_dict is not None:
                    logger.warning(f"Video {video.id}, Frame {frame_idx}: actual_angles_dict is not a dict or None. Found: {type(actual_angles_dict)}. Treating as no angles.")
                    actual_angles_dict = None

                current_timestamp = timestamp_from_angles if timestamp_from_angles is not None else frame_idx / video_fps
                current_frame_num = frame_num_from_angles if frame_num_from_angles is not None else frame_idx

                enriched_frame_sequence.append({
                    "frame_num": current_frame_num,
                    "timestamp": current_timestamp,
                    "angles": actual_angles_dict, # This will be Dict[str, float] or None
                    "raw_landmarks": landmarks_for_frame # This will be List[Dict[str, Any]] or None
                })
            # --- End of enriched_frame_sequence preparation ---

            if not enriched_frame_sequence:
                logger.warning(f"Video {video.id}: Enriched frame sequence is empty. No data for segmentation.")
                form_check.overall_feedback = "Analysis failed: No frame data could be prepared."
                form_check.status = "analysis_failed"
                await self.db.commit()
                return form_check
            
            # Pass the enriched sequence to segmentation
            repetitions = await self.segment_repetitions(enriched_frame_sequence, config)
            num_reps = len(repetitions)
            logger.info(f"Segmented into {num_reps} repetitions for video ID: {video.id}")

            if not repetitions:
                logger.warning(f"No repetitions segmented for video ID: {video.id}. Analysis may be limited.")
                form_check.overall_feedback = "No repetitions were detected in the video."
                # No score change if no reps

            for i, rep_frames in enumerate(repetitions):
                logger.info(f"Evaluating Rep {i+1}/{num_reps} for video ID: {video.id}")
                # Pass rep_index (0-based) to evaluate_rep
                rep_structured_issues, rep_score = await self.evaluate_rep(rep_frames, i, config) # MODIFIED: pass rep_index
                
                # rep_structured_issues are now List[StructuredIssue]
                # These need to be transformed into FeedbackItem data by a new/modified generate_feedback_items_from_issues
                # For now, let's assume all_feedback_items_for_video will store these structured issues directly,
                # and the conversion happens before DB storage.
                all_feedback_items_for_video.extend(rep_structured_issues) # Storing structured issues for now
                total_score += rep_score
            
            if num_reps > 0:
                form_check.overall_score = total_score / num_reps
            else:
                form_check.overall_score = 0 # Or keep previous score / set to a specific value
            
            logger.info(f"Overall score for video ID {video.id}: {form_check.overall_score} based on {num_reps} reps.")

            # Persist feedback items
            if all_feedback_items_for_video:
                # Augment feedback items with form_check_id before saving
                
                formatted_feedback_for_db = []
                for issue_data in all_feedback_items_for_video: # issue_data is a StructuredIssue
                    # Map rule_type to FeedbackType enum
                    rule_type_str = issue_data.get("rule_type", "form").upper()
                    try:
                        feedback_type_enum_val = FeedbackType[rule_type_str]
                    except KeyError:
                        logger.warning(f"Unknown rule_type '{rule_type_str}' encountered. Defaulting to FeedbackType.FORM.")
                        feedback_type_enum_val = FeedbackType.FORM

                    # Map severity string to FeedbackSeverity enum
                    severity_str = issue_data.get("severity", FeedbackSeverity.LOW.value)
                    try:
                        feedback_severity_enum_val = FeedbackSeverity(severity_str)
                    except ValueError:
                        logger.warning(f"Unknown severity string '{severity_str}' encountered. Defaulting to FeedbackSeverity.LOW.")
                        feedback_severity_enum_val = FeedbackSeverity.LOW
                    
                    # Prepare the dictionary for FeedbackItem creation
                    # This matches the fields expected by create_feedback_items_in_db and the FeedbackItem model
                    db_fb_item_data = {
                        "form_check_id": form_check.id,
                        "feedback_text": issue_data.get("details", "Issue detected."),
                        "severity": feedback_severity_enum_val,
                        "type": feedback_type_enum_val,
                        "timestamp": issue_data.get("timestamp_in_video"), # REVERTED DIAGNOSTIC DEFAULT
                        
                        # New structured fields for FeedbackItem
                        "details_payload": issue_data, 
                        "rep_index": issue_data.get("rep_index"), 
                        "movement_phase": issue_data.get("phase"),
                        "joint_name": issue_data.get("joint_name")
                    }
                    formatted_feedback_for_db.append(db_fb_item_data)

                if formatted_feedback_for_db:
                    await self.create_feedback_items_in_db(form_check.id, formatted_feedback_for_db)
                    logger.info(f"Stored {len(formatted_feedback_for_db)} feedback items for FormCheck ID: {form_check.id}")
                else:
                    logger.info(f"No detailed feedback items to store for FormCheck ID: {form_check.id}")


            # Simple overall feedback
            if not all_feedback_items_for_video and num_reps > 0:
                form_check.overall_feedback = "Good form! No major issues detected."
            elif num_reps > 0 :
                form_check.overall_feedback = f"Found {len(all_feedback_items_for_video)} areas for improvement across {num_reps} repetitions. Overall score: {form_check.overall_score:.2f}"
            elif not form_check.overall_feedback: # If no reps and no specific message yet
                 form_check.overall_feedback = "Analysis complete. Could not detect repetitions to score."


            form_check.status = "analysis_complete"
            await self.db.commit()
            await self.db.refresh(form_check)
            logger.info(f"Dynamic form analysis completed for video ID: {video.id}. FormCheck ID: {form_check.id}, Status: {form_check.status}, Score: {form_check.overall_score}")

        except ValidationError as ve:
            logger.error(f"Validation error during analysis for video {video.id}: {ve}")
            form_check.status = "analysis_failed"
            form_check.overall_feedback = f"Analysis failed: {str(ve)}"
            await self.db.commit() # Save error state
            raise # Re-raise to be caught by Celery task
        except Exception as e:
            logger.error(f"Unexpected error during dynamic form analysis for video ID: {video.id}: {str(e)}", exc_info=True)
            if form_check: # form_check should be defined
                form_check.status = "analysis_failed"
                form_check.overall_feedback = f"An unexpected error occurred during analysis: {str(e)}" # UPDATED to include str(e)
                await self.db.commit()
            raise ServerErrorException(f"Dynamic form analysis failed for video {video.id}: {e}") from e
        
        return form_check
    
    def detect_movement_phase(
        self,
        phases_config: Any,
        joint_angles: Dict[str, float]
    ) -> str:
        """
        Detect the current movement phase based on joint angles.
        Accepts either a Pydantic model for phases (from ExerciseConfig) or a dict.
        """
        phase_items = []
        if hasattr(phases_config, 'items'):
            phase_items = phases_config.items()
        elif isinstance(phases_config, dict):
            phase_items = phases_config.items()
        else:
            logger.warning("Phases config is not a dictionary or Pydantic model. Cannot detect phase.")
            return "unknown"

        for phase_name, phase_data_model in phase_items:
            triggers_dict = {}
            if hasattr(phase_data_model, 'triggers') and phase_data_model.triggers:
                 if isinstance(phase_data_model.triggers, dict):
                    triggers_dict = phase_data_model.triggers
                 elif hasattr(phase_data_model.triggers, 'model_dump'):
                    triggers_dict = phase_data_model.triggers.model_dump()

            next_triggers_list = triggers_dict.get("next", [])
            if not next_triggers_list:
                continue

            all_satisfied = True
            for trigger_model in next_triggers_list:
                joint = trigger_model.joint if hasattr(trigger_model, 'joint') else trigger_model.get("joint")
                value = trigger_model.value if hasattr(trigger_model, 'value') else trigger_model.get("value")
                comparator = trigger_model.comparator if hasattr(trigger_model, 'comparator') else trigger_model.get("comparator")
                
                if not joint or joint not in joint_angles or value is None or not comparator:
                    all_satisfied = False
                    break 
                    
                angle = joint_angles[joint]
                
                satisfied = False
                if comparator == "<" and (angle < value): satisfied = True
                elif comparator == ">" and (angle > value): satisfied = True
                elif comparator == "==" and (angle == value): satisfied = True
                elif comparator == "<=" and (angle <= value): satisfied = True
                elif comparator == ">=" and (angle >= value): satisfied = True
                
                if not satisfied:
                    all_satisfied = False
                    break
            
            if all_satisfied:
                return phase_name
        
        return "unknown"
    
    def check_joint_angles(
        self,
        rules_config: Any,
        joint_angles: Dict[str, float],
        phase: str
    ) -> List[Dict[str, Any]]:
        """
        Check joint angles against phase-specific rules.
        Accepts Pydantic model for rules_config (from ExerciseConfig) or dict.
        """
        issues = []
        
        phases_rules_model = None
        if hasattr(rules_config, 'phases'):
            phases_rules_model = rules_config.phases 
        elif isinstance(rules_config, dict) and "phases" in rules_config:
             phases_rules_model = rules_config["phases"]
        else:
            logger.warning("Joint angle rules 'phases' structure not found in config.")
            return issues

        current_phase_rules_model = None
        if phases_rules_model and hasattr(phases_rules_model, 'get'):
            current_phase_rules_model = phases_rules_model.get(phase)
            if not current_phase_rules_model and "default" in phases_rules_model:
                 current_phase_rules_model = phases_rules_model.get("default")
        elif phases_rules_model and isinstance(phases_rules_model, dict):
            current_phase_rules_model = phases_rules_model.get(phase)
            if not current_phase_rules_model and "default" in phases_rules_model:
                 current_phase_rules_model = phases_rules_model.get("default")

        if not current_phase_rules_model:
            return issues
        
        angle_rules_map = {}
        if hasattr(current_phase_rules_model, 'angles'):
            angle_rules_map = current_phase_rules_model.angles
        elif isinstance(current_phase_rules_model, dict) and "angles" in current_phase_rules_model:
            angle_rules_map = current_phase_rules_model["angles"]

        if not angle_rules_map:
            return issues

        for joint, rule_model in angle_rules_map.items():
            if joint not in joint_angles:
                continue
                
            angle = joint_angles[joint]
            
            min_angle = rule_model.min_angle if hasattr(rule_model, 'min_angle') else rule_model.get("min_angle")
            max_angle = rule_model.max_angle if hasattr(rule_model, 'max_angle') else rule_model.get("max_angle")
            ideal_angle = rule_model.ideal_angle if hasattr(rule_model, 'ideal_angle') else rule_model.get("ideal_angle")
            tolerance_val = getattr(rule_model, 'tolerance', None) if hasattr(rule_model, 'tolerance') else rule_model.get("tolerance")
            tolerance = tolerance_val if tolerance_val is not None else 15.0


            current_deviation = 0.0
            issue_type = None
            expected_val_dict: Dict[str, Any] = {}


            if min_angle is not None and angle < min_angle:
                current_deviation = min_angle - angle
                issue_type = "below_min"
                expected_val_dict = {"min": min_angle}
            elif max_angle is not None and angle > max_angle:
                current_deviation = angle - max_angle
                issue_type = "above_max"
                expected_val_dict = {"max": max_angle}
            elif ideal_angle is not None and tolerance is not None:
                lower_bound_ideal = ideal_angle - tolerance
                upper_bound_ideal = ideal_angle + tolerance
                if angle < lower_bound_ideal or angle > upper_bound_ideal:
                    current_deviation = (lower_bound_ideal - angle) if angle < lower_bound_ideal else (angle - upper_bound_ideal)
                    issue_type = "non_ideal"
                    expected_val_dict = {"ideal": ideal_angle, "tolerance": tolerance}
            
            if issue_type:
                severity_tolerance_val = getattr(rule_model, 'severity_tolerance', tolerance)
                issues.append({
                    "joint": joint,
                    "actual": angle,
                    "expected": expected_val_dict,
                    "issue_type": issue_type,
                    "deviation": current_deviation,
                    "severity": self.calculate_severity(current_deviation, severity_tolerance_val)
                })
        
        return issues
    
    def calculate_severity(self, deviation: float, tolerance_for_severity: float) -> str:
        """
        Calculate severity based on deviation from expected angle.
        Tolerance here refers to how much deviation is allowed before it's considered an issue for severity calculation.
        """
        if tolerance_for_severity <= 0:
            tolerance_for_severity = 15.0

        abs_deviation = abs(deviation)

        if abs_deviation == 0:
            return FeedbackSeverity.NONE.value
        elif abs_deviation <= tolerance_for_severity / 2:
            return FeedbackSeverity.LOW.value
        elif abs_deviation <= tolerance_for_severity:
            return FeedbackSeverity.MEDIUM.value
        else:
            return FeedbackSeverity.HIGH.value

    def generate_feedback(
        self,
        templates_config: Any,
        issues: List[Dict[str, Any]],
        phase: str
    ) -> List[Dict[str, Any]]:
        """
        Generate specific feedback based on issues and templates.
        Accepts Pydantic model for templates_config (from ExerciseConfig) or dict.
        """
        feedback_list = []
        
        template_items = []
        if hasattr(templates_config, 'items'):
             template_items = templates_config.items()
        elif isinstance(templates_config, dict):
            template_items = templates_config.items()
        else:
            logger.warning("Feedback templates config is not a dictionary or Pydantic model.")
            for issue in issues:
                 feedback_list.append({
                    "message": f"Issue detected with {issue.get('joint', 'unknown joint')}: {issue.get('issue_type', 'general issue')}. Actual: {issue.get('actual', 0):.1f}, Expected: {issue.get('expected', {})}.",
                    "severity": issue.get("severity", FeedbackSeverity.LOW.value),
                    "type": FeedbackType.FORM.value,
                    "details": f"Phase: {phase}, Deviation: {issue.get('deviation', 0):.1f}"
                })
            return feedback_list

        for issue in issues:
            matched_template_key = None
            if not matched_template_key and issue.get("issue_type"):
                for key, template_model in template_items:
                    if key == f"{issue.get('joint')}_{issue.get('issue_type')}":
                        matched_template_key = key
                        break
                if not matched_template_key:
                    for key, template_model in template_items:
                        if key == issue.get("issue_type"):
                            matched_template_key = key
                            break


            if matched_template_key:
                template_model = templates_config.get(matched_template_key)
                if template_model:
                    message = getattr(template_model, 'message', "Template message missing")
                    severity = getattr(template_model, 'severity', FeedbackSeverity.LOW.value)
                    feedback_type = getattr(template_model, 'type', FeedbackType.FORM.value)
                    details = getattr(template_model, 'details', None)
                    
                    feedback_list.append({
                        "message": message.format(joint=issue.get('joint'), actual=issue.get('actual'), expected=issue.get('expected')),
                        "severity": severity,
                        "type": feedback_type,
                        "details": details,
                        "raw_issue": issue
                    })
            else:
                feedback_list.append({
                    "message": f"Issue with {issue.get('joint', 'N/A')}: {issue.get('issue_type', 'general issue')}. Actual: {issue.get('actual', 0):.1f}, Expected: {issue.get('expected', {})}.",
                    "severity": issue.get("severity", FeedbackSeverity.LOW.value),
                    "type": FeedbackType.FORM.value,
                    "details": f"Phase: {phase}, Deviation: {issue.get('deviation', 0):.1f}"
                })
        return feedback_list
    
    async def create_feedback_items_in_db(
        self,
        form_check_id: UUID,
        feedback_data_list: List[Dict[str, Any]]
    ) -> List[FeedbackItem]:
        """
        Create FeedbackItem records in the database.
        
        Args:
            form_check_id (UUID): The ID of the FormCheck this feedback belongs to.
            feedback_data_list (List[Dict[str, Any]]): List of feedback data dictionaries.
            
        Returns:
            List[FeedbackItem]: List of created FeedbackItem objects.
        """
        created_items: List[FeedbackItem] = []
        if not feedback_data_list:
            return created_items

        for feedback_data in feedback_data_list:
            severity_value = feedback_data.get("severity")
            type_value = feedback_data.get("type")

            try:
                severity_enum = FeedbackSeverity(severity_value) if isinstance(severity_value, str) else FeedbackSeverity.INFO
            except ValueError:
                logger.warning(f"Invalid severity value: {severity_value}, defaulting to INFO.")
                severity_enum = FeedbackSeverity.INFO
            
            try:
                type_enum = FeedbackType(type_value) if isinstance(type_value, str) else FeedbackType.GENERAL
            except ValueError:
                logger.warning(f"Invalid feedback type value: {type_value}, defaulting to GENERAL.")
                type_enum = FeedbackType.GENERAL

            db_item = FeedbackItem(
                form_check_id=form_check_id,
                message=feedback_data.get("feedback_text", "N/A"),
                type=feedback_data.get("type"), 
                severity=feedback_data.get("severity"), 
                timestamp=feedback_data.get("timestamp"),
                
                details_payload=feedback_data.get("details_payload"),
                issue_specific_timestamp=feedback_data.get("timestamp_in_video"), 
                rep_index=feedback_data.get("rep_index"),
                movement_phase=feedback_data.get("movement_phase"),
                joint_name=feedback_data.get("joint_name")
            )
            self.db.add(db_item)
            created_items.append(db_item)
        
        try:
            await self.db.flush()
            for item in created_items:
                await self.db.refresh(item)
        except Exception as e:
            logger.error(f"Error creating feedback items in DB: {str(e)}")
            await self.db.rollback()
            return []
            
        return created_items

    def _get_keypoint_coords_by_name(
        self,
        keypoint_name: str,
        raw_landmarks_for_frame: List[Dict[str, Any]],
        landmark_name_map: List[str] = POSE_LANDMARK_NAMES
    ) -> Optional[Tuple[float, float]]:
        """
        Retrieves (x, y) coordinates for a named keypoint from a list of raw landmarks.
        """
        if not raw_landmarks_for_frame:
            return None
        try:
            keypoint_index = landmark_name_map.index(keypoint_name.upper()) # Assuming names in map are uppercase
        except ValueError:
            logger.warning(f"Keypoint name '{keypoint_name}' not found in landmark_name_map.")
            return None

        if 0 <= keypoint_index < len(raw_landmarks_for_frame):
            landmark_data = raw_landmarks_for_frame[keypoint_index]
            if isinstance(landmark_data, dict) and "x" in landmark_data and "y" in landmark_data:
                # Assuming visibility checks etc., are handled upstream or by rule relevance
                return landmark_data["x"], landmark_data["y"]
            else:
                # logger.debug(f"Landmark data for '{keypoint_name}' (index {keypoint_index}) is malformed or missing x,y.")
                return None
        else:
            # logger.debug(f"Keypoint index {keypoint_index} for '{keypoint_name}' is out of bounds for raw_landmarks_for_frame (len {len(raw_landmarks_for_frame)}).")
            return None

from fastapi import Depends
try:
    from app.core.deps import get_async_exercise_config_service
    from app.core.deps import get_async_form_check_service
except ImportError:
    logger.warning("get_async_exercise_config_service or get_async_form_check_service not found in app.core.deps, using placeholder(s). Ensure they are registered in api/deps.py.")
    # Placeholder for get_async_exercise_config_service if it wasn't imported
    if 'get_async_exercise_config_service' not in locals():
        async def get_async_exercise_config_service_placeholder():
            raise NotImplementedError("get_async_exercise_config_service provider not found.")
        get_async_exercise_config_service = get_async_exercise_config_service_placeholder
    # Placeholder for get_async_form_check_service if it wasn't imported
    if 'get_async_form_check_service' not in locals():
        async def get_async_form_check_service_placeholder():
            raise NotImplementedError("get_async_form_check_service provider not found.")
        get_async_form_check_service = get_async_form_check_service_placeholder

async def get_async_dynamic_form_analysis_service(
    # db: AsyncSession = Depends(get_async_db), # Original problematic dependency
    # settings: Settings = Depends(get_settings), # Original problematic dependency
    exercise_config_service: ExerciseConfigService = Depends(get_async_exercise_config_service),
    form_check_service: FormCheckService = Depends(get_async_form_check_service)
) -> DynamicFormAnalysisService:
    """Get dynamic form analysis service instance asynchronously."""
    from app.core.deps import get_async_db, get_settings # RE-ADDING LOCAL IMPORTS
    from sqlalchemy.ext.asyncio import AsyncSession 
    from fastapi import Depends 
    
    db: AsyncSession = Depends(get_async_db)
    settings: Settings = Depends(get_settings)
    
    return DynamicFormAnalysisService(
        db=db, 
        settings=settings, 
        exercise_config_service=exercise_config_service, 
        form_check_service=form_check_service
    )

# Placeholder for dependent service getters if they were previously in this file
# and need to be defined/imported for get_async_dynamic_form_analysis_service
# e.g.
# async def get_async_exercise_config_service(): ...
# async def get_async_form_check_service(): ... 