"""Add rom_posture_symmetry_rules_to_exercise_config

Revision ID: 344ffaefc1ed
Revises: b010fd6fecc4
Create Date: 2025-05-30 11:00:53.926990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # Ensure this is available if needed for JSON types, though sa.JSON is standard

# revision identifiers, used by Alembic.
revision = '344ffaefc1ed'
down_revision = 'b010fd6fecc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_configs', sa.Column('rom_rules', sa.JSON(), nullable=True))
    op.add_column('exercise_configs', sa.Column('posture_rules', sa.JSON(), nullable=True))
    op.add_column('exercise_configs', sa.Column('symmetry_rules', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_configs', 'symmetry_rules')
    op.drop_column('exercise_configs', 'posture_rules')
    op.drop_column('exercise_configs', 'rom_rules')
    # ### end Alembic commands ### 