"""add_calculated_angles_to_video_model

Revision ID: 0a90690b0720
Revises: 8a2e9bac7b70
Create Date: 2025-05-18 12:29:26.319373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # For JSONB if needed


# revision identifiers, used by Alembic.
revision = '0a90690b0720'
down_revision = '8a2e9bac7b70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('calculated_angles', sa.JSON(), nullable=True))
    # For PostgreSQL, you might prefer JSONB:
    # bind = op.get_bind()
    # if bind.dialect.name == 'postgresql':
    #     op.alter_column('videos', 'calculated_angles', type_=postgresql.JSONB(astext_type=sa.Text()), existing_type=sa.JSON(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'calculated_angles')
    # ### end Alembic commands ### 