"""add_processed_object_key_and_rename_frame_paths_to_s3_keys_in_video

Revision ID: 8a2e9bac7b70
Revises: 402ef432b9b3
Create Date: 2025-05-18 12:22:54.785059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # Import if using JSONB or other PG specific types, though not strictly needed here for JSON


# revision identifiers, used by Alembic.
revision = '8a2e9bac7b70'
down_revision = '402ef432b9b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('processed_object_key', sa.String(), nullable=True))
    op.alter_column('videos', 'processed_frame_paths', new_column_name='processed_frame_s3_keys', existing_type=sa.JSON(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'processed_frame_s3_keys', new_column_name='processed_frame_paths', existing_type=sa.JSON(), nullable=True)
    op.drop_column('videos', 'processed_object_key')
    # ### end Alembic commands ### 