"""add_classified_exercise_to_form_check_and_deprecate_fields

Revision ID: e0391d619427
Revises: 344ffaefc1ed
Create Date: 2025-06-01 22:42:52.450556

This migration adds classified_exercise_slug and classification_confidence
to the form_checks table.
It also serves as a record that the 'feedback' and 'issues' columns
on form_checks are now considered deprecated and will be removed in a future migration.
The 'form_metadata' column's intended use is clarified (for aggregated UI data).
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # For UUID type if needed explicitly

# revision identifiers, used by Alembic.
revision = 'e0391d619427'
down_revision = '344ffaefc1ed' # Ensure this is the correct previous revision ID
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_checks', sa.Column('classified_exercise_slug', sa.String(), nullable=True))
    op.add_column('form_checks', sa.Column('classification_confidence', sa.Float(), nullable=True))
    
    # The following are notes about deprecated fields. Alembic doesn't have a standard
    # way to mark columns as "deprecated" directly in the schema in a way that all DBs recognize.
    # Actual removal would be a separate `op.drop_column` in a future migration.
    # For now, the model and Pydantic schema changes reflect this deprecation.
    # op.execute("COMMENT ON COLUMN form_checks.feedback IS 'DEPRECATED: Use overall_feedback for summary and FeedbackItem for specifics.'")
    # op.execute("COMMENT ON COLUMN form_checks.issues IS 'DEPRECATED: Use FeedbackItem with details_payload for structured issues.'")
    # op.execute("COMMENT ON COLUMN form_checks.form_metadata IS 'For aggregated scores_by_rep, issues_by_rep, and summary stats for UI.'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_checks', 'classification_confidence')
    op.drop_column('form_checks', 'classified_exercise_slug')
    
    # To revert comments if they were applied, though standard Alembic doesn't track these for removal easily.
    # op.execute("COMMENT ON COLUMN form_checks.feedback IS NULL") # Or revert to original if known
    # op.execute("COMMENT ON COLUMN form_checks.issues IS NULL")
    # op.execute("COMMENT ON COLUMN form_checks.form_metadata IS NULL")
    # ### end Alembic commands ### 