"""Add structured detail fields to FeedbackItem model

Revision ID: b010fd6fecc4
Revises: da0ece80c1d2
Create Date: 2025-05-30 10:35:23.688926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # Added for JSONB if needed, otherwise use sa.JSON


# revision identifiers, used by Alembic.
revision = 'b010fd6fecc4'
down_revision = 'da0ece80c1d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_item', sa.Column('details_payload', sa.JSON(), nullable=True))
    op.add_column('feedback_item', sa.Column('timestamp_in_video', sa.Float(), nullable=True))
    op.add_column('feedback_item', sa.Column('rep_index', sa.Integer(), nullable=True))
    op.add_column('feedback_item', sa.Column('movement_phase', sa.String(), nullable=True))
    op.add_column('feedback_item', sa.Column('joint_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_item', 'joint_name')
    op.drop_column('feedback_item', 'movement_phase')
    op.drop_column('feedback_item', 'rep_index')
    op.drop_column('feedback_item', 'timestamp_in_video')
    op.drop_column('feedback_item', 'details_payload')
    # ### end Alembic commands ### 