"""add_raw_pose_data_to_video_model

Revision ID: 5408027f4e1a
Revises: b0eba72b99a6
Create Date: 2025-05-10 14:40:26.065401

"""
from alembic import op
import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql # Not strictly needed for just adding/dropping a JSON column
# from sqlalchemy.dialects import sqlite # Not strictly needed

# revision identifiers, used by Alembic.
revision = '5408027f4e1a'
down_revision = 'b0eba72b99a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only adding the raw_pose_data column to the videos table
    op.add_column('videos', sa.Column('raw_pose_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only dropping the raw_pose_data column from the videos table
    op.drop_column('videos', 'raw_pose_data')
    # ### end Alembic commands ### 