"""align_video_model_error_field_and_json_type

Revision ID: 9815775ecbd4
Revises: 5408027f4e1a
Create Date: 2025-05-10 14:50:48.481135

"""
from alembic import op
import sqlalchemy as sa
# It's good practice to remove unused imports like:
# from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '9815775ecbd4'
down_revision = '5408027f4e1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The 'error_message' column is already absent from the 'videos' table according to the DB.
    # So, this is a no-op.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Re-adding the error_message column to the videos table as Text if we were to downgrade.
    op.add_column('videos', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ### 