"""reconcile schema with models: six missing indexes, videos column comments (G-38)

Hand-reviewed autogenerate output. Before this revision `alembic check` reported 45 operations
against a database at 0012; 23 of them were the models' fault and were fixed in the models
(`index=True` on primary keys asking for redundant ix_<table>_id indexes; ten indexes and one
unique constraint the database has carried since 0002-0009 that no model declared). What is
left is real and lands here:

- six indexes the models always declared and no migration ever created. Three are UNIQUE:
  users.email, users.username, user_sessions.session_id -- the application relied on
  uniqueness the database did not enforce. Checked before applying: 0 duplicate emails,
  0 duplicate usernames, 0 duplicate session ids.
- sixteen column comments on `videos` (documentation only; no data change).

Revision ID: 0013_reconcile_schema
Revises: 0012_label_store
Create Date: 2026-09-24 21:08:29.803170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0013_reconcile_schema'
down_revision = '0012_label_store'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_exercise_templates_name'), 'exercise_templates', ['name'], unique=False)
    op.create_index(op.f('ix_user_sessions_device_token'), 'user_sessions', ['device_token'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('videos', 'compressed_pose_data',
               existing_type=postgresql.BYTEA(),
               comment='Compressed pose sequence data',
               existing_nullable=True)
    op.alter_column('videos', 'pose_compression_method',
               existing_type=postgresql.ENUM('NONE', 'GZIP', 'LZ4', 'ZSTD', name='compressionmethod'),
               comment='Compression method used for pose data',
               existing_nullable=True)
    op.alter_column('videos', 'compressed_features',
               existing_type=postgresql.BYTEA(),
               comment='Compressed extracted features',
               existing_nullable=True)
    op.alter_column('videos', 'features_compression_method',
               existing_type=postgresql.ENUM('NONE', 'GZIP', 'LZ4', 'ZSTD', name='compressionmethod'),
               comment='Compression method used for features',
               existing_nullable=True)
    op.alter_column('videos', 'original_pose_size',
               existing_type=sa.INTEGER(),
               comment='Original size of pose data in bytes',
               existing_nullable=True)
    op.alter_column('videos', 'compressed_pose_size',
               existing_type=sa.INTEGER(),
               comment='Compressed size of pose data in bytes',
               existing_nullable=True)
    op.alter_column('videos', 'compression_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Compression ratio (compressed/original)',
               existing_nullable=True)
    op.alter_column('videos', 'compression_stats',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Detailed compression performance statistics',
               existing_nullable=True)
    op.alter_column('videos', 'optimized_pose_data',
               existing_type=postgresql.BYTEA(),
               comment='Optimized pose data in MessagePack/ProtoBuf format',
               existing_nullable=True)
    op.alter_column('videos', 'pose_storage_format',
               existing_type=postgresql.ENUM('JSON', 'MSGPACK', 'PROTOBUF', 'PICKLE', name='storageformat'),
               comment='Storage format used for optimized pose data',
               existing_nullable=True)
    op.alter_column('videos', 'optimized_features',
               existing_type=postgresql.BYTEA(),
               comment='Optimized features in MessagePack/ProtoBuf format',
               existing_nullable=True)
    op.alter_column('videos', 'features_storage_format',
               existing_type=postgresql.ENUM('JSON', 'MSGPACK', 'PROTOBUF', 'PICKLE', name='storageformat'),
               comment='Storage format used for optimized features',
               existing_nullable=True)
    op.alter_column('videos', 'original_json_size',
               existing_type=sa.INTEGER(),
               comment='Original JSON size in bytes before optimization',
               existing_nullable=True)
    op.alter_column('videos', 'optimized_size',
               existing_type=sa.INTEGER(),
               comment='Optimized storage size in bytes',
               existing_nullable=True)
    op.alter_column('videos', 'storage_optimization_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Storage optimization ratio (optimized/original)',
               existing_nullable=True)
    op.alter_column('videos', 'storage_optimization_stats',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Detailed storage optimization performance statistics',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'storage_optimization_stats',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Detailed storage optimization performance statistics',
               existing_nullable=True)
    op.alter_column('videos', 'storage_optimization_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Storage optimization ratio (optimized/original)',
               existing_nullable=True)
    op.alter_column('videos', 'optimized_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Optimized storage size in bytes',
               existing_nullable=True)
    op.alter_column('videos', 'original_json_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Original JSON size in bytes before optimization',
               existing_nullable=True)
    op.alter_column('videos', 'features_storage_format',
               existing_type=postgresql.ENUM('JSON', 'MSGPACK', 'PROTOBUF', 'PICKLE', name='storageformat'),
               comment=None,
               existing_comment='Storage format used for optimized features',
               existing_nullable=True)
    op.alter_column('videos', 'optimized_features',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment='Optimized features in MessagePack/ProtoBuf format',
               existing_nullable=True)
    op.alter_column('videos', 'pose_storage_format',
               existing_type=postgresql.ENUM('JSON', 'MSGPACK', 'PROTOBUF', 'PICKLE', name='storageformat'),
               comment=None,
               existing_comment='Storage format used for optimized pose data',
               existing_nullable=True)
    op.alter_column('videos', 'optimized_pose_data',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment='Optimized pose data in MessagePack/ProtoBuf format',
               existing_nullable=True)
    op.alter_column('videos', 'compression_stats',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Detailed compression performance statistics',
               existing_nullable=True)
    op.alter_column('videos', 'compression_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Compression ratio (compressed/original)',
               existing_nullable=True)
    op.alter_column('videos', 'compressed_pose_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Compressed size of pose data in bytes',
               existing_nullable=True)
    op.alter_column('videos', 'original_pose_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Original size of pose data in bytes',
               existing_nullable=True)
    op.alter_column('videos', 'features_compression_method',
               existing_type=postgresql.ENUM('NONE', 'GZIP', 'LZ4', 'ZSTD', name='compressionmethod'),
               comment=None,
               existing_comment='Compression method used for features',
               existing_nullable=True)
    op.alter_column('videos', 'compressed_features',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment='Compressed extracted features',
               existing_nullable=True)
    op.alter_column('videos', 'pose_compression_method',
               existing_type=postgresql.ENUM('NONE', 'GZIP', 'LZ4', 'ZSTD', name='compressionmethod'),
               comment=None,
               existing_comment='Compression method used for pose data',
               existing_nullable=True)
    op.alter_column('videos', 'compressed_pose_data',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment='Compressed pose sequence data',
               existing_nullable=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_device_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_exercise_templates_name'), table_name='exercise_templates')
    # ### end Alembic commands ### 