"""add additional_metadata to videos table

Revision ID: 013_add_additional_metadata_to_videos
Revises: 012_consolidate_object_key
Create Date: YYYY-MM-DD HH:MM:SS.MS

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '013_add_additional_metadata_to_videos'
down_revision = '012_consolidate_object_key'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('additional_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'additional_metadata')
    # ### end Alembic commands ### 