"""add pose_data to videos table

Revision ID: 014_add_pose_data_to_videos
Revises: 013_add_vid_add_meta
Create Date: YYYY-MM-DD HH:MM:SS.MS

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '014_add_pose_data_to_videos'
down_revision = '013_add_vid_add_meta'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('pose_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'pose_data')
    # ### end Alembic commands ### 