"""check_models_after_progress_model_fix

Revision ID: da0ece80c1d2
Revises: 86e626975c57
Create Date: 2025-05-24 16:45:36.547618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0ece80c1d2'
down_revision = '86e626975c57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 