"""check_video_model_after_head_upgrade

Revision ID: 86e626975c57
Revises: 6e68aabf6667
Create Date: 2025-05-24 14:24:10.672892

"""
from alembic import op
import sqlalchemy as sa
from app.models.base import SQLiteUUID


# revision identifiers, used by Alembic.
revision = '86e626975c57'
down_revision = '6e68aabf6667'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', SQLiteUUID(), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('form_score', sa.Float(), nullable=False),
    sa.Column('consistency_score', sa.Float(), nullable=False),
    sa.Column('total_reps', sa.Integer(), nullable=False),
    sa.Column('improvement_areas', sa.Text(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_progress_id'), 'exercise_progress', ['id'], unique=False)
    op.create_table('progress_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('progress_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('form_score', sa.Float(), nullable=False),
    sa.Column('consistency_score', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['progress_id'], ['exercise_progress.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_snapshots_id'), 'progress_snapshots', ['id'], unique=False)
    op.alter_column('exercises', 'workout_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('videos', sa.Column('celery_task_id', sa.String(), nullable=True))
    op.add_column('workout_plans', sa.Column('workout_id', SQLiteUUID(), nullable=False))
    op.add_column('workout_plans', sa.Column('frequency', sa.String(length=50), nullable=True))
    op.drop_index('ix_workout_plans_goal', table_name='workout_plans')
    op.drop_index('ix_workout_plans_user_id', table_name='workout_plans')
    op.create_foreign_key(None, 'workout_plans', 'workouts', ['workout_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workout_plans', 'goal')
    op.add_column('workouts', sa.Column('duration', sa.Integer(), nullable=True))
    op.drop_index('ix_workouts_goal', table_name='workouts')
    op.drop_index('ix_workouts_user_id', table_name='workouts')
    op.drop_column('workouts', 'goal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('goal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_workouts_user_id', 'workouts', ['user_id'], unique=False)
    op.create_index('ix_workouts_goal', 'workouts', ['goal'], unique=False)
    op.drop_column('workouts', 'duration')
    op.add_column('workout_plans', sa.Column('goal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'workout_plans', type_='foreignkey')
    op.create_index('ix_workout_plans_user_id', 'workout_plans', ['user_id'], unique=False)
    op.create_index('ix_workout_plans_goal', 'workout_plans', ['goal'], unique=False)
    op.drop_column('workout_plans', 'frequency')
    op.drop_column('workout_plans', 'workout_id')
    op.drop_column('videos', 'celery_task_id')
    op.alter_column('exercises', 'workout_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_progress_snapshots_id'), table_name='progress_snapshots')
    op.drop_table('progress_snapshots')
    op.drop_index(op.f('ix_exercise_progress_id'), table_name='exercise_progress')
    op.drop_table('exercise_progress')
    # ### end Alembic commands ### 