"""Add reps_detected and reps_per_minute to form_checks table

Revision ID: 202505190001
Revises: None # Replace with the actual previous revision ID if known
Create Date: 2025-05-19 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202505190001'
down_revision: Union[str, None] = '8a2e9bac7b70' # Manually setting based on last observed migration
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_checks', sa.Column('reps_detected', sa.Integer(), nullable=True))
    op.add_column('form_checks', sa.Column('reps_per_minute', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_checks', 'reps_per_minute')
    op.drop_column('form_checks', 'reps_detected')
    # ### end Alembic commands ### 