"""Add depth_score to FormCheck model

Revision ID: 5c2e8f9a1b4d
Revises: 2f77b166ffb4
Create Date: 2025-06-25 02:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2e8f9a1b4d'
down_revision = '2f77b166ffb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_checks', sa.Column('depth_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_checks', 'depth_score')
    # ### end Alembic commands ###