"""consolidate_user_session_model_and_align_with_postgres

Revision ID: d2b1e6dc2d42
Revises: 014_add_pose_data_to_videos
Create Date: 2025-05-14 22:21:43.344195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.models.base import SQLiteUUID

# revision identifiers, used by Alembic.
revision = 'd2b1e6dc2d42'
down_revision = '014_add_pose_data_to_videos'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_postgresql = bind.dialect.name == 'postgresql'
    
    current_timestamp_default = sa.text('now()') if is_postgresql else sa.text('CURRENT_TIMESTAMP')

    if is_postgresql:
        # Manually create ENUM types first using op.execute.
        op.execute("CREATE TYPE subscriptiontier AS ENUM ('FREE', 'BASIC', 'PRO', 'ENTERPRISE', 'PREMIUM')")
        op.execute("CREATE TYPE feedbacktype AS ENUM ('SUCCESS', 'WARNING', 'ERROR', 'FORM', 'TECHNIQUE', 'POSTURE', 'RANGE', 'SPEED', 'BALANCE')")
        op.execute("CREATE TYPE feedbackseverity AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')")
        op.execute("CREATE TYPE videostatus AS ENUM ('PENDING_UPLOAD', 'UPLOADED', 'PROCESSING', 'PROCESSED', 'PROCESSING_FAILED', 'PENDING_ANALYSIS', 'ANALYZING', 'ANALYSIS_COMPLETE', 'ANALYSIS_FAILED', 'PUBLISHED', 'ARCHIVED', 'ERROR', 'VIDEO_PROCESSING_FAILED', 'POSE_DETECTION_PENDING', 'POSE_DETECTION_IN_PROGRESS', 'POSE_DETECTED', 'POSE_DETECTION_FAILED')")

    op.create_table('exercise_templates',
    sa.Column('id', SQLiteUUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('muscle_group', sa.String(), nullable=False),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=current_timestamp_default, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=current_timestamp_default, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_templates_id'), 'exercise_templates', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_templates_name'), 'exercise_templates', ['name'], unique=False)
    
    op.create_table('exercise_configs',
    sa.Column('id', SQLiteUUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exercise_id', SQLiteUUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('joint_angle_rules', sa.JSON(), nullable=False),
    sa.Column('movement_phases', sa.JSON(), nullable=False),
    sa.Column('feedback_templates', sa.JSON(), nullable=False),
    sa.Column('classification_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=current_timestamp_default, nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=current_timestamp_default, onupdate=current_timestamp_default, nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_configs_id'), 'exercise_configs', ['id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('auth_method', sa.String(), nullable=True),
    sa.Column('device_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=current_timestamp_default, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=current_timestamp_default, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_device_token'), 'user_sessions', ['device_token'], unique=False)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', SQLiteUUID(), nullable=False),
    sa.Column('user_id', SQLiteUUID(), nullable=False),
    sa.Column('notifications', sa.JSON(), nullable=True),
    sa.Column('privacy', sa.JSON(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('exercise_preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=current_timestamp_default, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=current_timestamp_default, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)

    op.create_table('feedback_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_check_id', SQLiteUUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('SUCCESS', 'WARNING', 'ERROR', 'FORM', 'TECHNIQUE', 'POSTURE', 'RANGE', 'SPEED', 'BALANCE', name='feedbacktype', create_type=False), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('severity', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='feedbackseverity', create_type=False), nullable=False),
    sa.Column('joint_angles', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=current_timestamp_default, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=current_timestamp_default, nullable=False),
    sa.ForeignKeyConstraint(['form_check_id'], ['form_checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_items_id'), 'feedback_items', ['id'], unique=False)
    
    op.drop_index('ix_workout_plan_workouts_day_of_week', table_name='workout_plan_workouts')
    op.drop_index('ix_workout_plan_workouts_week_number', table_name='workout_plan_workouts')
    op.drop_index('ix_workout_plan_workouts_workout_id', table_name='workout_plan_workouts')
    op.drop_index('ix_workout_plan_workouts_workout_plan_id', table_name='workout_plan_workouts')
    op.drop_table('workout_plan_workouts')
    
    op.drop_index('ix_workout_exercises_exercise_id', table_name='workout_exercises')
    op.drop_index('ix_workout_exercises_order', table_name='workout_exercises')
    op.drop_index('ix_workout_exercises_workout_id', table_name='workout_exercises')
    op.drop_table('workout_exercises')
    
    if is_postgresql:
        op.add_column('exercises', sa.Column('workout_id', SQLiteUUID(), nullable=True))
        op.add_column('exercises', sa.Column('sets', sa.Integer(), nullable=True))
        op.add_column('exercises', sa.Column('reps', sa.Integer(), nullable=True))
        op.add_column('exercises', sa.Column('weight', sa.Float(), nullable=True))
        op.add_column('exercises', sa.Column('duration', sa.Integer(), nullable=True))
        op.add_column('exercises', sa.Column('rest_time', sa.Integer(), nullable=True))
        op.add_column('exercises', sa.Column('exercise_metadata', sa.JSON(), nullable=True))
        op.alter_column('exercises', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=True)
        op.create_foreign_key('fk_exercises_workout_id_workouts', 'exercises', 'workouts', ['workout_id'], ['id'], ondelete='CASCADE')
        op.drop_column('exercises', 'equipment')
        op.drop_column('exercises', 'muscle_group')
        op.drop_column('exercises', 'difficulty')
        op.drop_column('exercises', 'video_url')
    else:
        with op.batch_alter_table('exercises', schema=None) as batch_op:
            batch_op.add_column(sa.Column('workout_id', SQLiteUUID(), nullable=True))
            batch_op.add_column(sa.Column('sets', sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column('reps', sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
            batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column('rest_time', sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column('exercise_metadata', sa.JSON(), nullable=True))
            
            batch_op.alter_column('description',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=1024),
                   existing_nullable=True)
            
            batch_op.drop_column('video_url')
            batch_op.drop_column('difficulty')
            batch_op.drop_column('muscle_group')
            batch_op.drop_column('equipment')

            batch_op.create_foreign_key('fk_exercises_workout_id_workouts', 'workouts', ['workout_id'], ['id'], ondelete='CASCADE')

    # Index drops are now dialect-specific if needed, or handled by batch recreate for SQLite
    if is_postgresql:
        op.drop_index(op.f('ix_exercises_difficulty'), table_name='exercises')
        op.drop_index(op.f('ix_exercises_muscle_group'), table_name='exercises')
        op.drop_index(op.f('ix_exercises_name'), table_name='exercises')

    # This create_index is general, seems fine. It's on 'id'.
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)

    op.add_column('form_checks', sa.Column('video_id', SQLiteUUID(), nullable=True))
    op.add_column('form_checks', sa.Column('analysis_url', sa.String(length=1024), nullable=True))
    op.add_column('form_checks', sa.Column('overall_feedback', sa.String(length=2048), nullable=True))
    op.add_column('form_checks', sa.Column('issues', sa.JSON(), nullable=True))
    op.add_column('form_checks', sa.Column('processing_time', sa.Float(), nullable=True))
    op.add_column('form_checks', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('form_checks', sa.Column('form_metadata', sa.JSON(), nullable=True))
    op.add_column('form_checks', sa.Column('results', sa.JSON(), nullable=True))
    op.add_column('form_checks', sa.Column('configuration_id', SQLiteUUID(), nullable=True))

    if is_postgresql:
        op.alter_column('form_checks', 'feedback',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        op.alter_column('form_checks', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        op.alter_column('form_checks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
                   server_default=current_timestamp_default)
        op.alter_column('form_checks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
                   server_default=current_timestamp_default)
        op.drop_constraint('form_checks_exercise_id_fkey', 'form_checks', type_='foreignkey')
        op.drop_constraint('form_checks_user_id_fkey', 'form_checks', type_='foreignkey')
        op.create_foreign_key('fk_form_checks_video_id_videos', 'form_checks', 'videos', ['video_id'], ['id'])
        op.create_foreign_key('fk_form_checks_exercise_id_exercise_templates', 'form_checks', 'exercise_templates', ['exercise_id'], ['id'])
        op.create_foreign_key('fk_form_checks_configuration_id_exercise_configs', 'form_checks', 'exercise_configs', ['configuration_id'], ['id'], ondelete='SET NULL')
        op.create_foreign_key('fk_form_checks_user_id_users', 'form_checks', 'users', ['user_id'], ['id'])
    else:
        with op.batch_alter_table('form_checks', schema=None, reflect_args=[sa.ForeignKeyConstraint([], [])]) as batch_op:
            batch_op.alter_column('feedback',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
            batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(length=50),
                   nullable=True,
                   server_default=sa.text("'pending'"))
            batch_op.alter_column('created_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=True,
                   server_default=current_timestamp_default)
            batch_op.alter_column('updated_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=True,
                   server_default=current_timestamp_default)
            batch_op.create_foreign_key('fk_form_checks_video_id_videos', 'videos', ['video_id'], ['id'])
            batch_op.create_foreign_key('fk_form_checks_exercise_id_exercise_templates', 'exercise_templates', ['exercise_id'], ['id'])
            batch_op.create_foreign_key('fk_form_checks_configuration_id_exercise_configs', 'exercise_configs', ['configuration_id'], ['id'], ondelete='SET NULL')
            batch_op.create_foreign_key('fk_form_checks_user_id_users', 'users', ['user_id'], ['id'])

    op.drop_index('ix_form_checks_created_at', table_name='form_checks')
    op.drop_index('ix_form_checks_exercise_id', table_name='form_checks')
    op.drop_index('ix_form_checks_status', table_name='form_checks')
    op.drop_index('ix_form_checks_user_id', table_name='form_checks')
    op.create_index(op.f('ix_form_checks_configuration_id'), 'form_checks', ['configuration_id'], unique=False)
    op.create_index(op.f('ix_form_checks_id'), 'form_checks', ['id'], unique=False)

    op.add_column('subscriptions', sa.Column('tier', postgresql.ENUM('FREE', 'BASIC', 'PRO', 'ENTERPRISE', 'PREMIUM', name='subscriptiontier', create_type=False), nullable=False))
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('cancel_at_period_end', sa.String(length=50), nullable=False)) # Assuming was nullable=False based on later use
    
    op.drop_index('ix_subscriptions_end_date', table_name='subscriptions')
    op.drop_index('ix_subscriptions_plan_type', table_name='subscriptions')
    op.drop_index('ix_subscriptions_status', table_name='subscriptions')
    op.drop_index('ix_subscriptions_user_id', table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)

    if is_postgresql:
        op.drop_constraint('subscriptions_user_id_fkey', 'subscriptions', type_='foreignkey')
        op.create_unique_constraint('uq_subscriptions_stripe_subscription_id', 'subscriptions', ['stripe_subscription_id'])
        op.create_foreign_key('fk_subscriptions_user_id_users', 'subscriptions', 'users', ['user_id'], ['id'])
    else:
        with op.batch_alter_table('subscriptions', schema=None) as batch_op:
            batch_op.create_unique_constraint('uq_subscriptions_stripe_subscription_id', ['stripe_subscription_id'])
            batch_op.create_foreign_key('fk_subscriptions_user_id_users', 'users', ['user_id'], ['id'])
            
    op.drop_column('subscriptions', 'plan_type')
    
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('subscription_tier', postgresql.ENUM('FREE', 'BASIC', 'PRO', 'ENTERPRISE', 'PREMIUM', name='subscriptiontier', create_type=False), nullable=False))
    op.add_column('users', sa.Column('subscription_end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False, server_default=sa.text('false'))) # Provide default
    op.add_column('users', sa.Column('verification_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('false'))) # Provide default
    op.add_column('users', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True, server_default=sa.text('0'))) # Provide default
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    
    if is_postgresql:
        op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
                   server_default=current_timestamp_default)
        op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
                   server_default=current_timestamp_default)
        op.drop_constraint('users_email_key', 'users', type_='unique') # Assumes this was the name
        op.create_unique_constraint('uq_users_stripe_subscription_id', 'users', ['stripe_subscription_id'])
        op.create_unique_constraint('uq_users_stripe_customer_id', 'users', ['stripe_customer_id'])
    else: # SQLite
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.alter_column('full_name',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=True)
            batch_op.alter_column('is_active',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   server_default=sa.text('1')) # SQLite boolean true
            batch_op.alter_column('created_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   type_=sa.DateTime(),
                   nullable=True,
                   server_default=current_timestamp_default)
            batch_op.alter_column('updated_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   type_=sa.DateTime(),
                   nullable=True,
                   server_default=current_timestamp_default)
            batch_op.create_unique_constraint('uq_users_stripe_subscription_id', ['stripe_subscription_id'])
            batch_op.create_unique_constraint('uq_users_stripe_customer_id', ['stripe_customer_id'])

    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index('ix_users_email', table_name='users') # Old non-unique index if users_email_key was separate
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True) # New unique index for email
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    op.add_column('videos', sa.Column('pose_visualizations', sa.JSON(), nullable=True))
    op.add_column('videos', sa.Column('analysis_results', sa.JSON(), nullable=True))
    op.add_column('videos', sa.Column('stats', sa.JSON(), nullable=True))
    op.add_column('videos', sa.Column('feedback', sa.JSON(), nullable=True))

    # Handle videos.status ENUM and default for PG
    if is_postgresql:
        op.execute("ALTER TABLE videos ALTER COLUMN status DROP DEFAULT")
        op.alter_column('videos', 'status',
                   existing_type=postgresql.ENUM('uploaded', 'processing', 'processed', 'failed', 'archived', 'transcoding_failed', name='videostatus_new', create_type=False), # This old name seems unused if videostatus is the new one
                   type_=postgresql.ENUM('PENDING_UPLOAD', 'UPLOADED', 'PROCESSING', 'PROCESSED', 'PROCESSING_FAILED', 'PENDING_ANALYSIS', 'ANALYZING', 'ANALYSIS_COMPLETE', 'ANALYSIS_FAILED', 'PUBLISHED', 'ARCHIVED', 'ERROR', 'VIDEO_PROCESSING_FAILED', 'POSE_DETECTION_PENDING', 'POSE_DETECTION_IN_PROGRESS', 'POSE_DETECTED', 'POSE_DETECTION_FAILED', name='videostatus', create_type=False),
                   existing_nullable=False,
                   postgresql_using='status::text::videostatus')
        op.execute("ALTER TABLE videos ALTER COLUMN status SET DEFAULT 'UPLOADED'::videostatus")
    else: # SQLite
        # For SQLite, ENUMs are TEXT. Type change is effectively a no-op if underlying is TEXT.
        # Default needs to be set without casting.
        with op.batch_alter_table('videos', schema=None) as batch_op:
             batch_op.alter_column('status',
                existing_type=sa.VARCHAR(), # Assuming old was text-like
                type_=sa.VARCHAR(),        # New is also text-like
               existing_nullable=False,
                server_default='UPLOADED')


    if is_postgresql:
        op.alter_column('videos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
                server_default=current_timestamp_default)
        op.alter_column('videos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
                server_default=current_timestamp_default)
    else: # SQLite
        with op.batch_alter_table('videos', schema=None) as batch_op:
            batch_op.alter_column('created_at',
                existing_type=postgresql.TIMESTAMP(timezone=True), # Keep for context
                type_=sa.DateTime(),
                existing_nullable=False,
                server_default=current_timestamp_default)
            batch_op.alter_column('updated_at',
                existing_type=postgresql.TIMESTAMP(timezone=True), # Keep for context
                type_=sa.DateTime(),
                existing_nullable=False,
                server_default=current_timestamp_default)

    op.drop_column('videos', 'upload_expires_at')
    op.drop_column('videos', 'metadata') # Keeping this drop, assuming it's intended.
    op.drop_column('videos', 'frame_s3_keys')
    op.drop_column('videos', 'normalized_s3_object_key')

    op.add_column('workout_plans', sa.Column('goal', sa.String(), nullable=True))
    op.add_column('workout_plans', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workout_plans', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workout_plans', sa.Column('plan_metadata', sa.JSON(), nullable=True))

    if is_postgresql:
        op.alter_column('workout_plans', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=True)
    else:
        with op.batch_alter_table('workout_plans', schema=None) as batch_op:
            batch_op.alter_column('description',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=1024),
                   existing_nullable=True)
            
    op.drop_index('ix_workout_plans_difficulty', table_name='workout_plans')
    op.drop_index('ix_workout_plans_name', table_name='workout_plans')
    op.create_index(op.f('ix_workout_plans_goal'), 'workout_plans', ['goal'], unique=False)
    op.create_index(op.f('ix_workout_plans_id'), 'workout_plans', ['id'], unique=False)
    op.drop_column('workout_plans', 'duration_weeks')
    op.drop_column('workout_plans', 'difficulty')
    
    op.add_column('workouts', sa.Column('goal', sa.String(), nullable=True))
    op.add_column('workouts', sa.Column('calories_burned', sa.Integer(), nullable=True))
    op.add_column('workouts', sa.Column('workout_metadata', sa.JSON(), nullable=True))

    if is_postgresql:
        op.alter_column('workouts', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=True)
    else:
        with op.batch_alter_table('workouts', schema=None) as batch_op:
            batch_op.alter_column('description',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=1024),
                   existing_nullable=True)

    op.drop_index('ix_workouts_difficulty', table_name='workouts')
    op.drop_index('ix_workouts_name', table_name='workouts')
    op.create_index(op.f('ix_workouts_goal'), 'workouts', ['goal'], unique=False)
    op.create_index(op.f('ix_workouts_id'), 'workouts', ['id'], unique=False)
    op.drop_column('workouts', 'duration')
    op.drop_column('workouts', 'difficulty')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_postgresql = bind.dialect.name == 'postgresql'
    current_timestamp_default = sa.text('now()') if is_postgresql else sa.text('CURRENT_TIMESTAMP')

    op.add_column('workouts', sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=True)) # Adjusted to True to match table creation
    op.add_column('workouts', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_workouts_id'), table_name='workouts')
    op.drop_index(op.f('ix_workouts_goal'), table_name='workouts')
    op.create_index('ix_workouts_name', 'workouts', ['name'], unique=False)
    op.create_index('ix_workouts_difficulty', 'workouts', ['difficulty'], unique=False)

    if is_postgresql:
        op.alter_column('workouts', 'description',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=True)
    else:
        with op.batch_alter_table('workouts', schema=None) as batch_op:
            batch_op.alter_column('description',
                   existing_type=sa.String(length=1024),
                   type_=sa.TEXT(),
                   existing_nullable=True)
            
    op.drop_column('workouts', 'workout_metadata')
    op.drop_column('workouts', 'calories_burned')
    op.drop_column('workouts', 'goal')

    op.add_column('workout_plans', sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=True)) # Adjusted to True
    op.add_column('workout_plans', sa.Column('duration_weeks', sa.INTEGER(), autoincrement=False, nullable=True)) # Adjusted to True
    op.drop_index(op.f('ix_workout_plans_id'), table_name='workout_plans')
    op.drop_index(op.f('ix_workout_plans_goal'), table_name='workout_plans')
    op.create_index('ix_workout_plans_name', 'workout_plans', ['name'], unique=False)
    op.create_index('ix_workout_plans_difficulty', 'workout_plans', ['difficulty'], unique=False)

    if is_postgresql:
        op.alter_column('workout_plans', 'description',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=True)
    else:
        with op.batch_alter_table('workout_plans', schema=None) as batch_op:
            batch_op.alter_column('description',
                   existing_type=sa.String(length=1024),
                   type_=sa.TEXT(),
                   existing_nullable=True)

    op.drop_column('workout_plans', 'plan_metadata')
    op.drop_column('workout_plans', 'end_date')
    op.drop_column('workout_plans', 'start_date')
    op.drop_column('workout_plans', 'goal')
    
    op.add_column('videos', sa.Column('normalized_s3_object_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('frame_s3_keys', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('upload_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))

    if is_postgresql:
        op.alter_column('videos', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
                   server_default=sa.text('now()'))
        op.alter_column('videos', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
                   server_default=sa.text('now()'))
        # Handling videos.status ENUM and default for PG downgrade
        op.execute("ALTER TABLE videos ALTER COLUMN status DROP DEFAULT")
        op.alter_column('videos', 'status',
                existing_type=postgresql.ENUM('PENDING_UPLOAD', 'UPLOADED', 'PROCESSING', 'PROCESSED', 'PROCESSING_FAILED', 'PENDING_ANALYSIS', 'ANALYZING', 'ANALYSIS_COMPLETE', 'ANALYSIS_FAILED', 'PUBLISHED', 'ARCHIVED', 'ERROR', 'VIDEO_PROCESSING_FAILED', 'POSE_DETECTION_PENDING', 'POSE_DETECTION_IN_PROGRESS', 'POSE_DETECTED', 'POSE_DETECTION_FAILED', name='videostatus', create_type=False),
                type_=postgresql.ENUM('uploaded', 'processing', 'processed', 'failed', 'archived', 'transcoding_failed', name='videostatus_new', create_type=False), # Assuming videostatus_new was an old definition
                existing_nullable=False,
                postgresql_using='status::text::varchar::videostatus_new') # Example, adjust cast as needed
        # op.execute("ALTER TABLE videos ALTER COLUMN status SET DEFAULT 'uploaded'::videostatus_new") # If there was an old default
    else: # SQLite
        with op.batch_alter_table('videos', schema=None) as batch_op:
            batch_op.alter_column('updated_at',
                   existing_type=sa.DateTime(),
                   type_=postgresql.TIMESTAMP(timezone=True), # Type for context, SQLite uses DATETIME
                   existing_nullable=False,
                   server_default=current_timestamp_default) # Revert to dialect-aware default
            batch_op.alter_column('created_at',
                   existing_type=sa.DateTime(),
                   type_=postgresql.TIMESTAMP(timezone=True), # Type for context
                   existing_nullable=False,
                   server_default=current_timestamp_default) # Revert to dialect-aware default
            batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(), # Current is text-like
                   type_=sa.VARCHAR(),        # Old was also text-like
               existing_nullable=False,
                   server_default='uploaded') # Assuming 'uploaded' was old default

    op.drop_column('videos', 'feedback')
    op.drop_column('videos', 'stats')
    op.drop_column('videos', 'analysis_results')
    op.drop_column('videos', 'pose_visualizations')

    # Batch reverse operations for users table
    if is_postgresql:
        op.drop_constraint('uq_users_stripe_customer_id', 'users', type_='unique')
        op.drop_constraint('uq_users_stripe_subscription_id', 'users', type_='unique')
        # op.create_unique_constraint('users_email_key', 'users', ['email']) # This will be handled by create_index ix_users_email unique=True below
        op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    else: # SQLite
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.drop_constraint('uq_users_stripe_customer_id', type_='unique')
            batch_op.drop_constraint('uq_users_stripe_subscription_id', type_='unique')
            # Re-ensure unique constraint on email implicitly by how table is reconstructed or explicitly if needed.
            # The later op.create_index(..., unique=True) should handle for SQLite.
            # To be explicit within batch for email uniqueness:
            # batch_op.create_unique_constraint('users_email_key', ['email']) # Or (None, ['email'])
            batch_op.alter_column('updated_at',
                   existing_type=sa.DateTime(),
                   type_=postgresql.TIMESTAMP(timezone=True),
                   nullable=False,
                   server_default=current_timestamp_default)
            batch_op.alter_column('created_at',
                   existing_type=sa.DateTime(),
                   type_=postgresql.TIMESTAMP(timezone=True),
                   nullable=False,
                   server_default=current_timestamp_default)
            batch_op.alter_column('is_active',
                   existing_type=sa.BOOLEAN(),
                   nullable=False,
                   server_default=sa.text('1'))
            batch_op.alter_column('full_name',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=False)
            # Ensure email uniqueness is restored. If an index ix_users_email (unique=True) is created *after* this batch, it's fine.
            # If we want to ensure it during batch, add:
            # batch_op.create_unique_constraint('users_email_key', ['email']) # Or use None for auto-name

    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users') # Drop new unique index
    op.create_index('ix_users_email', 'users', ['email'], unique=True) # Original way to ensure email unique for PG (named constraint users_email_key likely tied to this)
    op.create_unique_constraint('users_email_key', 'users', ['email']) # Explicitly recreate named constraint for PG
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'verified_at')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'stripe_subscription_id')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'subscription_end_date')
    op.drop_column('users', 'subscription_tier')
    op.drop_column('users', 'username')

    op.add_column('subscriptions', sa.Column('plan_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    if is_postgresql:
        op.drop_constraint('fk_subscriptions_user_id_users', 'subscriptions', type_='foreignkey')
        op.drop_constraint('uq_subscriptions_stripe_subscription_id', 'subscriptions', type_='unique')
        op.create_foreign_key('subscriptions_user_id_fkey', 'subscriptions', 'users', ['user_id'], ['id']) # Recreate original
    else: # SQLite
        with op.batch_alter_table('subscriptions', schema=None) as batch_op:
            batch_op.drop_constraint('fk_subscriptions_user_id_users', type_='foreignkey')
            batch_op.drop_constraint('uq_subscriptions_stripe_subscription_id', type_='unique')
            batch_op.create_foreign_key('subscriptions_user_id_fkey', 'users', ['user_id'], ['id']) # Recreate original
            
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.create_index('ix_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_index('ix_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_index('ix_subscriptions_plan_type', 'subscriptions', ['plan_type'], unique=False)
    op.create_index('ix_subscriptions_end_date', 'subscriptions', ['end_date'], unique=False)
    op.drop_column('subscriptions', 'cancel_at_period_end')
    op.drop_column('subscriptions', 'stripe_customer_id')
    op.drop_column('subscriptions', 'stripe_subscription_id')
    op.drop_column('subscriptions', 'tier')

    # Batch reverse operations for form_checks constraints
    if is_postgresql:
        op.drop_constraint('fk_form_checks_user_id_users', 'form_checks', type_='foreignkey')
        op.drop_constraint('fk_form_checks_configuration_id_exercise_configs', 'form_checks', type_='foreignkey')
        op.drop_constraint('fk_form_checks_exercise_id_exercise_templates', 'form_checks', type_='foreignkey')
        op.drop_constraint('fk_form_checks_video_id_videos', 'form_checks', type_='foreignkey')
        op.create_foreign_key('form_checks_user_id_fkey', 'form_checks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        op.create_foreign_key('form_checks_exercise_id_fkey', 'form_checks', 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')
        op.alter_column('form_checks', 'status',
                   existing_type=sa.VARCHAR(length=50),
                   nullable=False,
                   existing_server_default=sa.text("'pending'::character varying"))
        op.alter_column('form_checks', 'created_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True), # In upgrade this was pg.TS, now reverting
                   nullable=False,
                   existing_server_default=sa.text('now()'))
        op.alter_column('form_checks', 'updated_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True), # In upgrade this was pg.TS, now reverting
                   nullable=False,
                   existing_server_default=sa.text('now()'))
        op.alter_column('form_checks', 'feedback',
                   existing_type=sa.String(),
                   type_=sa.TEXT(),
                   existing_nullable=True)
    else: # SQLite
        with op.batch_alter_table('form_checks', schema=None) as batch_op:
            batch_op.drop_constraint('fk_form_checks_user_id_users', type_='foreignkey')
            batch_op.drop_constraint('fk_form_checks_configuration_id_exercise_configs', type_='foreignkey')
            batch_op.drop_constraint('fk_form_checks_exercise_id_exercise_templates', type_='foreignkey')
            batch_op.drop_constraint('fk_form_checks_video_id_videos', type_='foreignkey')
            batch_op.create_foreign_key('form_checks_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
            batch_op.create_foreign_key('form_checks_exercise_id_fkey', 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')
            batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(length=50),
                   nullable=False,
                   server_default=sa.text("'pending'"))
            batch_op.alter_column('created_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=False,
                   server_default=current_timestamp_default)
            batch_op.alter_column('updated_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=False,
                   server_default=current_timestamp_default)
            batch_op.alter_column('feedback',
                   existing_type=sa.String(),
                   type_=sa.TEXT(),
                   existing_nullable=True)

    op.drop_index(op.f('ix_form_checks_id'), table_name='form_checks')
    op.drop_index(op.f('ix_form_checks_configuration_id'), table_name='form_checks')
    op.create_index('ix_form_checks_user_id', 'form_checks', ['user_id'], unique=False)
    op.create_index('ix_form_checks_status', 'form_checks', ['status'], unique=False)
    op.create_index('ix_form_checks_exercise_id', 'form_checks', ['exercise_id'], unique=False)
    op.create_index('ix_form_checks_created_at', 'form_checks', ['created_at'], unique=False)
    
    op.drop_column('form_checks', 'configuration_id')
    op.drop_column('form_checks', 'results')
    op.drop_column('form_checks', 'form_metadata')
    op.drop_column('form_checks', 'confidence_score')
    op.drop_column('form_checks', 'processing_time')
    op.drop_column('form_checks', 'issues')
    op.drop_column('form_checks', 'overall_feedback')
    op.drop_column('form_checks', 'analysis_url')
    op.drop_column('form_checks', 'video_id')

    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.create_index('ix_exercises_name', 'exercises', ['name'], unique=False)
    op.create_index('ix_exercises_muscle_group', 'exercises', ['muscle_group'], unique=False)
    op.create_index('ix_exercises_difficulty', 'exercises', ['difficulty'], unique=False)
    
    op.drop_column('exercises', 'exercise_metadata')
    op.drop_column('exercises', 'rest_time')
    op.drop_column('exercises', 'duration')
    op.drop_column('exercises', 'weight')
    op.drop_column('exercises', 'reps')
    op.drop_column('exercises', 'sets')
    op.drop_column('exercises', 'workout_id')
    
    op.create_table('workout_exercises',
    sa.Column('workout_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=True), # Assuming original was nullable
    sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=True), # Assuming original was nullable
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rest_period_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='workout_exercises_exercise_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name='workout_exercises_workout_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workout_id', 'exercise_id', 'order', name='workout_exercises_pkey')
    )
    op.create_index('ix_workout_exercises_workout_id', 'workout_exercises', ['workout_id'], unique=False)
    op.create_index('ix_workout_exercises_order', 'workout_exercises', ['order'], unique=False)
    op.create_index('ix_workout_exercises_exercise_id', 'workout_exercises', ['exercise_id'], unique=False)
    
    op.create_table('workout_plan_workouts',
    sa.Column('workout_plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workout_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('week_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name='workout_plan_workouts_workout_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plans.id'], name='workout_plan_workouts_workout_plan_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workout_plan_id', 'workout_id', 'week_number', 'day_of_week', name='workout_plan_workouts_pkey')
    )
    op.create_index('ix_workout_plan_workouts_workout_plan_id', 'workout_plan_workouts', ['workout_plan_id'], unique=False)
    op.create_index('ix_workout_plan_workouts_workout_id', 'workout_plan_workouts', ['workout_id'], unique=False)
    op.create_index('ix_workout_plan_workouts_week_number', 'workout_plan_workouts', ['week_number'], unique=False)
    op.create_index('ix_workout_plan_workouts_day_of_week', 'workout_plan_workouts', ['day_of_week'], unique=False)
    
    op.drop_index(op.f('ix_feedback_items_id'), table_name='feedback_items')
    op.drop_table('feedback_items')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_device_token'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_exercise_configs_id'), table_name='exercise_configs')
    op.drop_table('exercise_configs')
    op.drop_index(op.f('ix_exercise_templates_name'), table_name='exercise_templates')
    op.drop_index(op.f('ix_exercise_templates_id'), table_name='exercise_templates')
    op.drop_table('exercise_templates')
    
    if is_postgresql:
        op.execute("DROP TYPE videostatus")
        op.execute("DROP TYPE feedbackseverity")
        op.execute("DROP TYPE feedbacktype")
        op.execute("DROP TYPE subscriptiontier")
    # ### end Alembic commands ### 