"""add_videos_table_and_other_missing_schema

Revision ID: c7ffd09cdc07
Revises: 002
Create Date: 2025-05-08 12:42:31.352537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import func

# Define Python Enum type configurations (values and SQL names)
ENUM_DEFINITIONS = {
    'videostatus': ['PENDING', 'PROCESSING', 'READY', 'FAILED', 'DELETED'],
    'feedbacktype': ['SUCCESS', 'WARNING', 'ERROR', 'FORM', 'TECHNIQUE', 'POSTURE', 'RANGE', 'SPEED', 'BALANCE'],
    'feedbackseverity': ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'],
    'subscriptiontier': ['FREE', 'BASIC', 'PRO', 'ENTERPRISE', 'PREMIUM']
}

# Define ENUM types
subscriptiontier = sa.Enum('FREE', 'BASIC', 'PRO', 'ENTERPRISE', 'PREMIUM', name='subscriptiontier')
videostatus = sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', 'DELETED', name='videostatus')
feedbacktype = sa.Enum('SUCCESS', 'WARNING', 'ERROR', 'FORM', 'TECHNIQUE', 'POSTURE', 'RANGE', 'SPEED', 'BALANCE', name='feedbacktype')
feedbackseverity = sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='feedbackseverity')

# revision identifiers, used by Alembic.
revision = 'c7ffd09cdc07'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create feedback_item table (singular, to match the model name)
    op.create_table(
        'feedback_item',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('form_check_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('feedback_text', sa.Text(), nullable=False),
        sa.Column('severity', sa.String(length=50), nullable=False), # Example: "High", "Medium", "Low"
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=func.now(), nullable=False, onupdate=func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['form_check_id'], ['form_checks.id'], ondelete='CASCADE')
    )
    # Note: Other table creations that might have been intended for this migration are missing.
    # Only adding feedback_item as it's the current blocker.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_workouts_id'), table_name='workouts')
    op.alter_column('workouts', 'id',
               existing_type=sa.dialects.postgresql.UUID(as_uuid=True),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('workouts', 'description',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('workouts', 'user_id',
               existing_type=sa.dialects.postgresql.UUID(as_uuid=True),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('workouts', 'workout_metadata')
    op.drop_column('workouts', 'calories_burned')
    op.add_column('workout_plans', sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('workout_plans', sa.Column('duration_weeks', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workout_plans', type_='foreignkey')
    op.drop_index(op.f('ix_workout_plans_id'), table_name='workout_plans')
    op.alter_column('workout_plans', 'id',
               existing_type=sa.dialects.postgresql.UUID(as_uuid=True),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('workout_plans', 'description',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('workout_plans', 'user_id',
               existing_type=sa.dialects.postgresql.UUID(as_uuid=True),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('workout_plans', 'plan_metadata')
    op.drop_column('workout_plans', 'end_date')
    op.drop_column('workout_plans', 'start_date')
    op.drop_column('workout_plans', 'frequency')
    op.drop_column('workout_plans', 'workout_id')
    op.drop_constraint('uq_users_stripe_customer_id', 'users', type_='unique')
    op.drop_constraint('uq_users_stripe_subscription_id', 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.dialects.postgresql.UUID(as_uuid=True),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'verified_at')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'stripe_subscription_id')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'subscription_end_date')
    op.drop_column('users', 'subscription_tier')
    op.drop_column('users', 'username')
    op.add_column('subscriptions', sa.Column('plan_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key('subscriptions_user_id_fkey', 'subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_subscriptions_stripe_subscription_id', 'subscriptions', type_='unique')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.dialects.postgresql.UUID(as_uuid=True),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('subscriptions', 'id',
               existing_type=sa.dialects.postgresql.UUID(as_uuid=True),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('subscriptions', 'cancel_at_period_end')
    op.drop_column('subscriptions', 'stripe_customer_id')
    op.drop_column('subscriptions', 'stripe_subscription_id')
    op.drop_column('subscriptions', 'tier')
    op.drop_constraint(None, 'form_checks', type_='foreignkey')
    op.drop_constraint(None, 'form_checks', type_='foreignkey')
    op.drop_constraint(None, 'form_checks', type_='foreignkey')
    op.drop_constraint(None, 'form_checks', type_='foreignkey')
    op.create_foreign_key('form_checks_exercise_id_fkey', 'form_checks', 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('form_checks_user_id_fkey', 'form_checks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_form_checks_id'), table_name='form_checks')
    op.drop_index(op.f('ix_form_checks_configuration_id'), table_name='form_checks')
    op.alter_column('form_checks', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('form_checks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('form_checks', 'status',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('form_checks', 'feedback',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('form_checks', 'user_id',
               existing_type=sa.dialects.postgresql.UUID(as_uuid=True),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('form_checks', 'exercise_id',
               existing_type=sa.dialects.postgresql.UUID(as_uuid=True),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('form_checks', 'id',
               existing_type=sa.dialects.postgresql.UUID(as_uuid=True),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('form_checks', 'configuration_id')
    op.drop_column('form_checks', 'results')
    op.drop_column('form_checks', 'form_metadata')
    op.drop_column('form_checks', 'confidence_score')
    op.drop_column('form_checks', 'processing_time')
    op.drop_column('form_checks', 'issues')
    op.drop_column('form_checks', 'overall_feedback')
    op.drop_column('form_checks', 'analysis_url')
    op.drop_column('form_checks', 'video_id')
    op.add_column('exercises', sa.Column('equipment', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('muscle_group', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('exercises', sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('exercises', sa.Column('video_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.create_index('ix_exercises_name', 'exercises', ['name'], unique=False)
    op.create_index('ix_exercises_muscle_group', 'exercises', ['muscle_group'], unique=False)
    op.create_index('ix_exercises_difficulty', 'exercises', ['difficulty'], unique=False)
    op.alter_column('exercises', 'id',
               existing_type=sa.dialects.postgresql.UUID(as_uuid=True),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('exercises', 'description',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('exercises', 'exercise_metadata')
    op.drop_column('exercises', 'rest_time')
    op.drop_column('exercises', 'duration')
    op.drop_column('exercises', 'weight')
    op.drop_column('exercises', 'reps')
    op.drop_column('exercises', 'sets')
    op.drop_column('exercises', 'workout_id')
    op.create_table('workout_exercises',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('workout_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='workout_exercises_exercise_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name='workout_exercises_workout_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='workout_exercises_pkey')
    )
    op.create_index('ix_workout_exercises_workout_id', 'workout_exercises', ['workout_id'], unique=False)
    op.create_index('ix_workout_exercises_order', 'workout_exercises', ['order'], unique=False)
    op.create_index('ix_workout_exercises_exercise_id', 'workout_exercises', ['exercise_id'], unique=False)
    op.create_table('workout_plan_workouts',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('workout_plan_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('workout_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name='workout_plan_workouts_workout_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plans.id'], name='workout_plan_workouts_workout_plan_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='workout_plan_workouts_pkey')
    )
    op.create_index('ix_workout_plan_workouts_workout_plan_id', 'workout_plan_workouts', ['workout_plan_id'], unique=False)
    op.create_index('ix_workout_plan_workouts_workout_id', 'workout_plan_workouts', ['workout_id'], unique=False)
    op.create_index('ix_workout_plan_workouts_week_number', 'workout_plan_workouts', ['week_number'], unique=False)
    op.create_index('ix_workout_plan_workouts_day_of_week', 'workout_plan_workouts', ['day_of_week'], unique=False)
    op.drop_index(op.f('ix_feedback_items_id'), table_name='feedback_item')
    op.drop_table('feedback_item')
    # op.drop_table('videos') # Commented out
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_exercise_configs_id'), table_name='exercise_configs')
    op.drop_table('exercise_configs')
    # op.drop_index(op.f('ix_exercise_templates_name'), table_name='exercise_templates') # Also comment out related index drop
    # op.drop_index(op.f('ix_exercise_templates_id'), table_name='exercise_templates') # Also comment out related index drop
    # op.drop_table('exercise_templates') # COMMENT OUT THIS LINE
    # Drop ENUM types in reverse order of creation (or any order with IF EXISTS)
    for enum_name in reversed(list(ENUM_DEFINITIONS.keys())):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ### 