"""
PostureV2 feature specification — body joints only, camera-invariant.

STATUS: DRAFT. Nothing trains on this yet and nothing serves it. It exists so the
notebook, the bench scripts and the Celery worker can import ONE definition
instead of three, which is how v1 ended up with a manifest that disagreed with
its own code (AUDIT.md G-24).

Why v2 exists
-------------
v1 spends 87 of its 151 inputs on raw MediaPipe FACE coordinates (landmarks
0-10 = nose/eyes/ears/mouth; body starts at 11). Those carry real but accidental
signal: your head drops as you squat, so nose/eye y is a crude proxy for depth
and trunk lean. It is a shortcut, because the values are raw frame coordinates --
the same squat filmed two feet further back produces different numbers.

Measured (bench/results/2026-09-19-face-block-ablation.md, n=50) -- and that
baseline carries TWO defects, so this delta is indicative, not exact:
  * G-25: an n=50 balanced-fixture run is not comparable to a natural-prevalence
    number; the 0.769 headline was retracted on those grounds.
  * G-44: 7 of those 50 fixtures (14.0%) have a byte-identical twin in TRAIN, so
    they were not held out at all. The test that asserts they were checks split
    membership by NAME, not by content (G-45).
The ARGUMENT below survives both -- it is a relative comparison between two arms
scored on the same fixtures, and the contamination is common to both -- but the
absolute figures are upper bounds and are not re-measured.
    baseline                     F1 0.7692
    face block frozen [0:87]     F1 0.7170   (-0.052)
So the face block is worth ~0.05 F1. v2 does not simply delete it -- that would
leave a hole. It replaces it with body-joint features that measure the same
things (depth, lean) without depending on where the camera is.

Design rules
------------
1. BODY JOINTS ONLY. No face landmarks anywhere.
2. EVERY frame is normalised: translate so the hip midpoint is the origin, then
   divide by torso length. Camera distance and position drop out.
   LIMIT: this removes zoom and pan, NOT camera angle. Side vs front vs 45-degree
   views still change knee-valgus and trunk-lean readings, because those are
   measured in the image plane. Mirroring is also unhandled. Both are open
   problems for v2 -- a view-angle feature or per-view models -- not solved here.
   MediaPipe's z for image landmarks is the noisiest axis and is a candidate to
   drop entirely; it is currently included pending a measured comparison.
3. Temporal features are computed AFTER resampling to a fixed fps, so a 30fps
   and a 60fps recording of the same squat produce the same numbers.
4. Feature names are generated by the same code that computes the values, and
   `spec_hash()` fingerprints the spec so an artifact can refuse to load against
   a spec it was not trained on.
"""
from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np

# --------------------------------------------------------------------------
# Landmark map — MediaPipe Pose. Body only; 0-10 (face) deliberately excluded.
# --------------------------------------------------------------------------
L_SHOULDER, R_SHOULDER = 11, 12
L_ELBOW, R_ELBOW = 13, 14
L_WRIST, R_WRIST = 15, 16
L_HIP, R_HIP = 23, 24
L_KNEE, R_KNEE = 25, 26
L_ANKLE, R_ANKLE = 27, 28
L_HEEL, R_HEEL = 29, 30
L_FOOT, R_FOOT = 31, 32

BODY_JOINTS: Tuple[int, ...] = (
    L_SHOULDER, R_SHOULDER, L_ELBOW, R_ELBOW, L_WRIST, R_WRIST,
    L_HIP, R_HIP, L_KNEE, R_KNEE, L_ANKLE, R_ANKLE,
    L_HEEL, R_HEEL, L_FOOT, R_FOOT,
)
JOINT_NAMES: Dict[int, str] = {
    L_SHOULDER: "l_shoulder", R_SHOULDER: "r_shoulder",
    L_ELBOW: "l_elbow", R_ELBOW: "r_elbow",
    L_WRIST: "l_wrist", R_WRIST: "r_wrist",
    L_HIP: "l_hip", R_HIP: "r_hip",
    L_KNEE: "l_knee", R_KNEE: "r_knee",
    L_ANKLE: "l_ankle", R_ANKLE: "r_ankle",
    L_HEEL: "l_heel", R_HEEL: "r_foot_heel",
    L_FOOT: "l_foot_index", R_FOOT: "r_foot_index",
}

FIRST_BODY_LANDMARK = 11
TARGET_FPS = 30.0
SPEC_VERSION = "posture_v2_biomech_v1"
_EPS = 1e-8


# --------------------------------------------------------------------------
# Normalisation — the part that makes this camera-invariant
# --------------------------------------------------------------------------
def torso_length(frame: np.ndarray) -> float:
    """Hip-midpoint to shoulder-midpoint distance for one frame [33, 3]."""
    mid_hip = 0.5 * (frame[L_HIP] + frame[R_HIP])
    mid_sho = 0.5 * (frame[L_SHOULDER] + frame[R_SHOULDER])
    return float(np.linalg.norm(mid_sho[:2] - mid_hip[:2]))


def normalize_frames(keypoints: np.ndarray) -> np.ndarray:
    """
    Translate to the hip midpoint and scale by torso length, per frame.

    After this, a squat filmed close up and the same squat filmed from across the
    room produce the same coordinates. This is the single most important
    difference from v1, which fed raw frame coordinates straight to the model.

    Args:
        keypoints: [T, 33, 3]
    Returns:
        [T, 33, 3] normalised. Frames with a degenerate torso are zeroed.
    """
    kp = np.asarray(keypoints, dtype=np.float64)
    if kp.ndim != 3 or kp.shape[1] < 33 or kp.shape[2] < 3:
        raise ValueError(f"expected [T, 33, 3], got {kp.shape}")

    out = np.zeros_like(kp)
    for t in range(kp.shape[0]):
        frame = kp[t]
        scale = torso_length(frame)
        if not np.isfinite(scale) or scale < _EPS:
            continue  # unusable frame -> leave as zeros
        mid_hip = 0.5 * (frame[L_HIP] + frame[R_HIP])
        out[t] = (frame - mid_hip) / scale
    return out


def resample_to_fps(
    keypoints: np.ndarray, source_fps: float, target_fps: float = TARGET_FPS
) -> np.ndarray:
    """
    Linearly resample the sequence in time so tempo features are fps-independent.

    v1 computed temporal statistics on whatever fps the upload happened to have,
    so the same squat at 60fps produced different velocities than at 30fps.
    """
    kp = np.asarray(keypoints, dtype=np.float64)
    T = kp.shape[0]
    if T < 2 or source_fps <= 0 or abs(source_fps - target_fps) < 1e-6:
        return kp

    duration = (T - 1) / source_fps
    n_out = max(2, int(round(duration * target_fps)) + 1)
    src_t = np.arange(T) / source_fps
    dst_t = np.linspace(0.0, duration, n_out)

    flat = kp.reshape(T, -1)
    out = np.empty((n_out, flat.shape[1]), dtype=np.float64)
    for c in range(flat.shape[1]):
        out[:, c] = np.interp(dst_t, src_t, flat[:, c])
    return out.reshape(n_out, kp.shape[1], kp.shape[2])


# --------------------------------------------------------------------------
# Geometry
# --------------------------------------------------------------------------
def angle_3pts(a: np.ndarray, b: np.ndarray, c: np.ndarray) -> float:
    """Interior angle at vertex b, in degrees, using the xy plane."""
    v1, v2 = a[:2] - b[:2], c[:2] - b[:2]
    n1, n2 = np.linalg.norm(v1), np.linalg.norm(v2)
    if n1 < _EPS or n2 < _EPS:
        return float("nan")
    cos = float(np.clip(np.dot(v1, v2) / (n1 * n2), -1.0, 1.0))
    return float(np.degrees(np.arccos(cos)))


def trunk_angle_from_vertical(frame: np.ndarray) -> float:
    """Angle of the hip->shoulder vector away from vertical, in degrees."""
    mid_hip = 0.5 * (frame[L_HIP] + frame[R_HIP])
    mid_sho = 0.5 * (frame[L_SHOULDER] + frame[R_SHOULDER])
    v = mid_sho[:2] - mid_hip[:2]
    n = np.linalg.norm(v)
    if n < _EPS:
        return float("nan")
    # image coords: y grows downward, so "up" is (0, -1)
    cos = float(np.clip(np.dot(v / n, np.array([0.0, -1.0])), -1.0, 1.0))
    return float(np.degrees(np.arccos(cos)))


def _series(fn, kp: np.ndarray) -> np.ndarray:
    return np.array([fn(kp[t]) for t in range(kp.shape[0])], dtype=np.float64)


def _nan_stats(x: np.ndarray, prefix: str) -> Dict[str, float]:
    v = x[np.isfinite(x)]
    if v.size == 0:
        return {f"{prefix}_{s}": 0.0 for s in ("mean", "std", "min", "max", "range")}
    return {
        f"{prefix}_mean": float(v.mean()),
        f"{prefix}_std": float(v.std()),
        f"{prefix}_min": float(v.min()),
        f"{prefix}_max": float(v.max()),
        f"{prefix}_range": float(v.max() - v.min()),
    }


# --------------------------------------------------------------------------
# Phase segmentation — descent / bottom / ascent from hip height
# --------------------------------------------------------------------------
@dataclass
class Phases:
    descent: slice
    bottom: slice
    ascent: slice
    bottom_index: int


def segment_phases(kp: np.ndarray, bottom_frac: float = 0.15) -> Phases:
    """Split the rep using hip-midpoint y (image coords: larger y = lower)."""
    T = kp.shape[0]
    if T < 3:
        return Phases(slice(0, T), slice(0, T), slice(0, T), 0)
    hip_y = 0.5 * (kp[:, L_HIP, 1] + kp[:, R_HIP, 1])
    bottom = int(np.nanargmax(hip_y))
    pad = max(1, int(T * bottom_frac / 2))
    return Phases(
        descent=slice(0, max(1, bottom)),
        bottom=slice(max(0, bottom - pad), min(T, bottom + pad + 1)),
        ascent=slice(min(bottom + 1, T - 1), T),
        bottom_index=bottom,
    )


# --------------------------------------------------------------------------
# The feature vector
# --------------------------------------------------------------------------
def compute_features(
    keypoints: np.ndarray,
    source_fps: Optional[float] = None,
    already_normalized: bool = False,
) -> Tuple[np.ndarray, List[str]]:
    """
    Build the v2 feature vector.

    Args:
        keypoints: [T, 33, 3] raw MediaPipe (x, y, z), visibility already dropped.
        source_fps: if given, the sequence is resampled to TARGET_FPS first.
        already_normalized: skip normalisation (for tests that pass normalised input).

    Returns:
        (values [D], names [D]) -- always the same length and order.
    """
    kp = np.asarray(keypoints, dtype=np.float64)
    if kp.ndim != 3 or kp.shape[1] < 33:
        raise ValueError(f"expected [T, 33, 3], got {kp.shape}")

    if source_fps:
        kp = resample_to_fps(kp, source_fps)
    norm = kp if already_normalized else normalize_frames(kp)

    feats: Dict[str, float] = {}

    # --- 1. Per-joint position statistics, body joints only, torso-normalised ---
    for j in BODY_JOINTS:
        name = JOINT_NAMES[j]
        for ci, coord in enumerate("xyz"):
            s = norm[:, j, ci]
            s = s[np.isfinite(s)]
            if s.size == 0:
                feats[f"{name}_{coord}_mean"] = 0.0
                feats[f"{name}_{coord}_std"] = 0.0
                feats[f"{name}_{coord}_range"] = 0.0
            else:
                feats[f"{name}_{coord}_mean"] = float(s.mean())
                feats[f"{name}_{coord}_std"] = float(s.std())
                feats[f"{name}_{coord}_range"] = float(s.max() - s.min())

    # --- 2. Joint angles over the whole rep ---
    l_knee = _series(lambda f: angle_3pts(f[L_HIP], f[L_KNEE], f[L_ANKLE]), norm)
    r_knee = _series(lambda f: angle_3pts(f[R_HIP], f[R_KNEE], f[R_ANKLE]), norm)
    l_hip = _series(lambda f: angle_3pts(f[L_SHOULDER], f[L_HIP], f[L_KNEE]), norm)
    r_hip = _series(lambda f: angle_3pts(f[R_SHOULDER], f[R_HIP], f[R_KNEE]), norm)
    l_ank = _series(lambda f: angle_3pts(f[L_KNEE], f[L_ANKLE], f[L_FOOT]), norm)
    r_ank = _series(lambda f: angle_3pts(f[R_KNEE], f[R_ANKLE], f[R_FOOT]), norm)
    trunk = _series(trunk_angle_from_vertical, norm)

    for label, series in (
        ("l_knee_angle", l_knee), ("r_knee_angle", r_knee),
        ("l_hip_angle", l_hip), ("r_hip_angle", r_hip),
        ("l_ankle_angle", l_ank), ("r_ankle_angle", r_ank),
        ("trunk_angle", trunk),
    ):
        feats.update(_nan_stats(series, label))

    ph = segment_phases(norm)

    # --- 3. Depth ---
    _stack = np.vstack([l_knee, r_knee])
    with np.errstate(invalid="ignore"):
        # all-NaN columns are expected on degenerate frames; guarded below
        knee_mean = np.where(
            np.isfinite(_stack).any(axis=0), np.nanmean(np.where(np.isfinite(_stack), _stack, 0.0), axis=0), np.nan
        )
    feats["depth_min_knee_angle"] = float(np.nanmin(knee_mean)) if np.isfinite(knee_mean).any() else 0.0
    hip_y = 0.5 * (norm[:, L_HIP, 1] + norm[:, R_HIP, 1])
    knee_y = 0.5 * (norm[:, L_KNEE, 1] + norm[:, R_KNEE, 1])
    below = hip_y - knee_y  # >0 means hip is lower than knee (image coords)
    feats["depth_hip_below_knee_max"] = float(np.nanmax(below)) if np.isfinite(below).any() else 0.0
    feats["depth_hip_below_knee_flag"] = 1.0 if feats["depth_hip_below_knee_max"] > 0 else 0.0

    # --- 4. Trunk lean ---
    feats["trunk_max_lean_deg"] = float(np.nanmax(trunk)) if np.isfinite(trunk).any() else 0.0
    b = trunk[ph.bottom]
    feats["trunk_lean_at_bottom_deg"] = float(np.nanmean(b[np.isfinite(b)])) if np.isfinite(b).any() else 0.0
    d = trunk[ph.descent]
    feats["trunk_wobble_descent"] = float(np.nanstd(d[np.isfinite(d)])) if np.isfinite(d).any() else 0.0

    # --- 5. Knee valgus: knees tracking inside the ankles, torso-normalised ---
    l_val = norm[:, L_KNEE, 0] - norm[:, L_ANKLE, 0]
    r_val = norm[:, R_KNEE, 0] - norm[:, R_ANKLE, 0]
    inward = (r_val - l_val)  # positive => knees collapsing toward each other
    feats["valgus_mean"] = float(np.nanmean(inward)) if np.isfinite(inward).any() else 0.0
    ib = inward[ph.bottom]
    feats["valgus_at_bottom"] = float(np.nanmean(ib[np.isfinite(ib)])) if np.isfinite(ib).any() else 0.0
    feats["valgus_max"] = float(np.nanmax(inward)) if np.isfinite(inward).any() else 0.0

    # --- 6. Heel lift during descent ---
    heel_y = 0.5 * (norm[:, L_HEEL, 1] + norm[:, R_HEEL, 1])
    hd = heel_y[ph.descent]
    hd = hd[np.isfinite(hd)]
    feats["heel_lift_descent"] = float(hd.max() - hd.min()) if hd.size else 0.0
    ankle_y = 0.5 * (norm[:, L_ANKLE, 1] + norm[:, R_ANKLE, 1])
    ha = (heel_y - ankle_y)
    feats["heel_ankle_gap_std"] = float(np.nanstd(ha[np.isfinite(ha)])) if np.isfinite(ha).any() else 0.0

    # --- 7. Left/right symmetry ---
    for label, lhs, rhs in (("knee", l_knee, r_knee), ("hip", l_hip, r_hip), ("ankle", l_ank, r_ank)):
        diff = np.abs(lhs - rhs)
        v = diff[np.isfinite(diff)]
        feats[f"symmetry_{label}_mean_abs_diff"] = float(v.mean()) if v.size else 0.0
        feats[f"symmetry_{label}_max_abs_diff"] = float(v.max()) if v.size else 0.0
    db = np.abs(l_knee - r_knee)[ph.bottom]
    feats["symmetry_knee_at_bottom"] = float(np.nanmean(db[np.isfinite(db)])) if np.isfinite(db).any() else 0.0

    # --- 8. Tempo (frames; fps-independent because we resampled) ---
    T = norm.shape[0]
    n_desc = max(1, ph.descent.stop - ph.descent.start)
    n_asc = max(1, ph.ascent.stop - ph.ascent.start)
    feats["tempo_descent_frames"] = float(n_desc)
    feats["tempo_ascent_frames"] = float(n_asc)
    feats["tempo_ratio"] = float(n_desc / n_asc)
    feats["tempo_total_frames"] = float(T)

    names = sorted(feats)                      # deterministic, independent of insertion order
    values = np.array([feats[n] for n in names], dtype=np.float32)
    return values, names


def get_feature_names() -> List[str]:
    """Names in the exact order compute_features returns them."""
    dummy = np.zeros((4, 33, 3), dtype=np.float64)
    dummy[:, :, 1] = np.linspace(0.0, 1.0, 4)[:, None]   # give it some motion
    dummy[:, L_SHOULDER, 1] = -1.0
    dummy[:, R_SHOULDER, 1] = -1.0
    _, names = compute_features(dummy)
    return names


def feature_dim() -> int:
    return len(get_feature_names())


def spec_hash() -> str:
    """
    Fingerprint of (spec version, joint set, feature names).

    Bake this into the trained artifact and assert it at load time, so a model
    can refuse to run against a feature spec it was not trained on -- the class of
    silent mismatch that produced G-24 in v1.
    """
    payload = json.dumps(
        {
            "spec_version": SPEC_VERSION,
            "target_fps": TARGET_FPS,
            "body_joints": list(BODY_JOINTS),
            "feature_names": get_feature_names(),
        },
        sort_keys=True,
    ).encode()
    return hashlib.sha256(payload).hexdigest()


def build_manifest() -> Dict:
    """The manifest is GENERATED from this file -- never hand-written (G-24)."""
    names = get_feature_names()
    return {
        "spec_version": SPEC_VERSION,
        "spec_hash": spec_hash(),
        "feature_dim": len(names),
        "target_fps": TARGET_FPS,
        "normalization": "per-frame: translate to hip midpoint, divide by torso length",
        "body_joints": {str(j): JOINT_NAMES[j] for j in BODY_JOINTS},
        "excludes_face_landmarks": True,
        "first_body_landmark": FIRST_BODY_LANDMARK,
        "feature_names": names,
    }


if __name__ == "__main__":
    print(json.dumps(build_manifest(), indent=2))
